language: go
go:
  - "1.13"
sudo: false
before_install:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.20.0
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint
install:
  - $(go env GOPATH)/bin/golangci-lint --version
script:
  - $(go env GOPATH)/bin/golangci-lint run --disable wsl ./...
  - go clean
  - go build ./...
  - go test ./... --short -count=1

  - cd v2
  - $(go env GOPATH)/bin/golangci-lint run --disable wsl ./...
  - go clean
  - go build ./...
  - go test ./... --short -count=1
