// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpcapi.proto

package grpcapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ValueType int32

const (
	ValueType_NUMERIC       ValueType = 0
	ValueType_SINGLE_CHOICE ValueType = 1
	ValueType_MULTI_CHOICE  ValueType = 2
)

var ValueType_name = map[int32]string{
	0: "NUMERIC",
	1: "SINGLE_CHOICE",
	2: "MULTI_CHOICE",
}
var ValueType_value = map[string]int32{
	"NUMERIC":       0,
	"SINGLE_CHOICE": 1,
	"MULTI_CHOICE":  2,
}

func (x ValueType) String() string {
	return proto.EnumName(ValueType_name, int32(x))
}
func (ValueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_aeb914f4b76396b0, []int{0}
}

type Origin struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Provider             string   `protobuf:"bytes,3,opt,name=provider" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Origin) Reset()         { *m = Origin{} }
func (m *Origin) String() string { return proto.CompactTextString(m) }
func (*Origin) ProtoMessage()    {}
func (*Origin) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_aeb914f4b76396b0, []int{0}
}
func (m *Origin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Origin.Unmarshal(m, b)
}
func (m *Origin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Origin.Marshal(b, m, deterministic)
}
func (dst *Origin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Origin.Merge(dst, src)
}
func (m *Origin) XXX_Size() int {
	return xxx_messageInfo_Origin.Size(m)
}
func (m *Origin) XXX_DiscardUnknown() {
	xxx_messageInfo_Origin.DiscardUnknown(m)
}

var xxx_messageInfo_Origin proto.InternalMessageInfo

func (m *Origin) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Origin) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Origin) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

type MeasurementPoint struct {
	Angular              string   `protobuf:"bytes,1,opt,name=angular" json:"angular,omitempty"`
	Bearing              int32    `protobuf:"varint,3,opt,name=bearing" json:"bearing,omitempty"`
	MeasurementType      string   `protobuf:"bytes,4,opt,name=measurementType" json:"measurementType,omitempty"`
	Shaft                string   `protobuf:"bytes,5,opt,name=shaft" json:"shaft,omitempty"`
	ShaftSide            string   `protobuf:"bytes,6,opt,name=shaftSide" json:"shaftSide,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeasurementPoint) Reset()         { *m = MeasurementPoint{} }
func (m *MeasurementPoint) String() string { return proto.CompactTextString(m) }
func (*MeasurementPoint) ProtoMessage()    {}
func (*MeasurementPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_aeb914f4b76396b0, []int{1}
}
func (m *MeasurementPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeasurementPoint.Unmarshal(m, b)
}
func (m *MeasurementPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeasurementPoint.Marshal(b, m, deterministic)
}
func (dst *MeasurementPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeasurementPoint.Merge(dst, src)
}
func (m *MeasurementPoint) XXX_Size() int {
	return xxx_messageInfo_MeasurementPoint.Size(m)
}
func (m *MeasurementPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_MeasurementPoint.DiscardUnknown(m)
}

var xxx_messageInfo_MeasurementPoint proto.InternalMessageInfo

func (m *MeasurementPoint) GetAngular() string {
	if m != nil {
		return m.Angular
	}
	return ""
}

func (m *MeasurementPoint) GetBearing() int32 {
	if m != nil {
		return m.Bearing
	}
	return 0
}

func (m *MeasurementPoint) GetMeasurementType() string {
	if m != nil {
		return m.MeasurementType
	}
	return ""
}

func (m *MeasurementPoint) GetShaft() string {
	if m != nil {
		return m.Shaft
	}
	return ""
}

func (m *MeasurementPoint) GetShaftSide() string {
	if m != nil {
		return m.ShaftSide
	}
	return ""
}

type InspectionPoint struct {
	OBSOLETEValueType    string    `protobuf:"bytes,1,opt,name=OBSOLETE_valueType,json=OBSOLETEValueType" json:"OBSOLETE_valueType,omitempty"`
	ValueType            ValueType `protobuf:"varint,4,opt,name=valueType,enum=grpcapi.ValueType" json:"valueType,omitempty"`
	NumericUnit          string    `protobuf:"bytes,2,opt,name=numericUnit" json:"numericUnit,omitempty"`
	Answers              []string  `protobuf:"bytes,3,rep,name=answers" json:"answers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *InspectionPoint) Reset()         { *m = InspectionPoint{} }
func (m *InspectionPoint) String() string { return proto.CompactTextString(m) }
func (*InspectionPoint) ProtoMessage()    {}
func (*InspectionPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_aeb914f4b76396b0, []int{2}
}
func (m *InspectionPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InspectionPoint.Unmarshal(m, b)
}
func (m *InspectionPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InspectionPoint.Marshal(b, m, deterministic)
}
func (dst *InspectionPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InspectionPoint.Merge(dst, src)
}
func (m *InspectionPoint) XXX_Size() int {
	return xxx_messageInfo_InspectionPoint.Size(m)
}
func (m *InspectionPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_InspectionPoint.DiscardUnknown(m)
}

var xxx_messageInfo_InspectionPoint proto.InternalMessageInfo

func (m *InspectionPoint) GetOBSOLETEValueType() string {
	if m != nil {
		return m.OBSOLETEValueType
	}
	return ""
}

func (m *InspectionPoint) GetValueType() ValueType {
	if m != nil {
		return m.ValueType
	}
	return ValueType_NUMERIC
}

func (m *InspectionPoint) GetNumericUnit() string {
	if m != nil {
		return m.NumericUnit
	}
	return ""
}

func (m *InspectionPoint) GetAnswers() []string {
	if m != nil {
		return m.Answers
	}
	return nil
}

type AssetNode struct {
	Criticality          string   `protobuf:"bytes,1,opt,name=criticality" json:"criticality,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssetNode) Reset()         { *m = AssetNode{} }
func (m *AssetNode) String() string { return proto.CompactTextString(m) }
func (*AssetNode) ProtoMessage()    {}
func (*AssetNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_aeb914f4b76396b0, []int{3}
}
func (m *AssetNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetNode.Unmarshal(m, b)
}
func (m *AssetNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetNode.Marshal(b, m, deterministic)
}
func (dst *AssetNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetNode.Merge(dst, src)
}
func (m *AssetNode) XXX_Size() int {
	return xxx_messageInfo_AssetNode.Size(m)
}
func (m *AssetNode) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetNode.DiscardUnknown(m)
}

var xxx_messageInfo_AssetNode proto.InternalMessageInfo

func (m *AssetNode) GetCriticality() string {
	if m != nil {
		return m.Criticality
	}
	return ""
}

type Node struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Label                string            `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
	Description          string            `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Type                 string            `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
	Criticality          string            `protobuf:"bytes,5,opt,name=criticality" json:"criticality,omitempty"`
	SubType              string            `protobuf:"bytes,6,opt,name=subType" json:"subType,omitempty"`
	Origin               *Origin           `protobuf:"bytes,7,opt,name=origin" json:"origin,omitempty"`
	AssetNode            *AssetNode        `protobuf:"bytes,8,opt,name=assetNode" json:"assetNode,omitempty"`
	MeasurementPoint     *MeasurementPoint `protobuf:"bytes,9,opt,name=measurementPoint" json:"measurementPoint,omitempty"`
	InspectionPoint      *InspectionPoint  `protobuf:"bytes,10,opt,name=inspectionPoint" json:"inspectionPoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_aeb914f4b76396b0, []int{4}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Node) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Node) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Node) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Node) GetCriticality() string {
	if m != nil {
		return m.Criticality
	}
	return ""
}

func (m *Node) GetSubType() string {
	if m != nil {
		return m.SubType
	}
	return ""
}

func (m *Node) GetOrigin() *Origin {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (m *Node) GetAssetNode() *AssetNode {
	if m != nil {
		return m.AssetNode
	}
	return nil
}

func (m *Node) GetMeasurementPoint() *MeasurementPoint {
	if m != nil {
		return m.MeasurementPoint
	}
	return nil
}

func (m *Node) GetInspectionPoint() *InspectionPoint {
	if m != nil {
		return m.InspectionPoint
	}
	return nil
}

type Nodes struct {
	Nodes                []*Node  `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nodes) Reset()         { *m = Nodes{} }
func (m *Nodes) String() string { return proto.CompactTextString(m) }
func (*Nodes) ProtoMessage()    {}
func (*Nodes) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_aeb914f4b76396b0, []int{5}
}
func (m *Nodes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nodes.Unmarshal(m, b)
}
func (m *Nodes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nodes.Marshal(b, m, deterministic)
}
func (dst *Nodes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nodes.Merge(dst, src)
}
func (m *Nodes) XXX_Size() int {
	return xxx_messageInfo_Nodes.Size(m)
}
func (m *Nodes) XXX_DiscardUnknown() {
	xxx_messageInfo_Nodes.DiscardUnknown(m)
}

var xxx_messageInfo_Nodes proto.InternalMessageInfo

func (m *Nodes) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type GetEventsInput struct {
	Since                int64           `protobuf:"varint,1,opt,name=since" json:"since,omitempty"`
	Limit                *PrimitiveInt32 `protobuf:"bytes,2,opt,name=limit" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetEventsInput) Reset()         { *m = GetEventsInput{} }
func (m *GetEventsInput) String() string { return proto.CompactTextString(m) }
func (*GetEventsInput) ProtoMessage()    {}
func (*GetEventsInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_aeb914f4b76396b0, []int{6}
}
func (m *GetEventsInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsInput.Unmarshal(m, b)
}
func (m *GetEventsInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsInput.Marshal(b, m, deterministic)
}
func (dst *GetEventsInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsInput.Merge(dst, src)
}
func (m *GetEventsInput) XXX_Size() int {
	return xxx_messageInfo_GetEventsInput.Size(m)
}
func (m *GetEventsInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsInput proto.InternalMessageInfo

func (m *GetEventsInput) GetSince() int64 {
	if m != nil {
		return m.Since
	}
	return 0
}

func (m *GetEventsInput) GetLimit() *PrimitiveInt32 {
	if m != nil {
		return m.Limit
	}
	return nil
}

type GetEventsOutput struct {
	Events               []byte   `protobuf:"bytes,1,opt,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsOutput) Reset()         { *m = GetEventsOutput{} }
func (m *GetEventsOutput) String() string { return proto.CompactTextString(m) }
func (*GetEventsOutput) ProtoMessage()    {}
func (*GetEventsOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_aeb914f4b76396b0, []int{7}
}
func (m *GetEventsOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsOutput.Unmarshal(m, b)
}
func (m *GetEventsOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsOutput.Marshal(b, m, deterministic)
}
func (dst *GetEventsOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsOutput.Merge(dst, src)
}
func (m *GetEventsOutput) XXX_Size() int {
	return xxx_messageInfo_GetEventsOutput.Size(m)
}
func (m *GetEventsOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsOutput proto.InternalMessageInfo

func (m *GetEventsOutput) GetEvents() []byte {
	if m != nil {
		return m.Events
	}
	return nil
}

type SaveNodeInput struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
	Node                 *Node    `protobuf:"bytes,3,opt,name=node" json:"node,omitempty"`
	ParentId             string   `protobuf:"bytes,2,opt,name=parentId" json:"parentId,omitempty"`
	ParentOrigin         *Origin  `protobuf:"bytes,4,opt,name=parentOrigin" json:"parentOrigin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveNodeInput) Reset()         { *m = SaveNodeInput{} }
func (m *SaveNodeInput) String() string { return proto.CompactTextString(m) }
func (*SaveNodeInput) ProtoMessage()    {}
func (*SaveNodeInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_aeb914f4b76396b0, []int{8}
}
func (m *SaveNodeInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveNodeInput.Unmarshal(m, b)
}
func (m *SaveNodeInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveNodeInput.Marshal(b, m, deterministic)
}
func (dst *SaveNodeInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveNodeInput.Merge(dst, src)
}
func (m *SaveNodeInput) XXX_Size() int {
	return xxx_messageInfo_SaveNodeInput.Size(m)
}
func (m *SaveNodeInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveNodeInput.DiscardUnknown(m)
}

var xxx_messageInfo_SaveNodeInput proto.InternalMessageInfo

func (m *SaveNodeInput) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SaveNodeInput) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *SaveNodeInput) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *SaveNodeInput) GetParentOrigin() *Origin {
	if m != nil {
		return m.ParentOrigin
	}
	return nil
}

type DeleteNodeInput struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
	NodeId               string   `protobuf:"bytes,2,opt,name=nodeId" json:"nodeId,omitempty"`
	Origin               *Origin  `protobuf:"bytes,3,opt,name=origin" json:"origin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteNodeInput) Reset()         { *m = DeleteNodeInput{} }
func (m *DeleteNodeInput) String() string { return proto.CompactTextString(m) }
func (*DeleteNodeInput) ProtoMessage()    {}
func (*DeleteNodeInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_aeb914f4b76396b0, []int{9}
}
func (m *DeleteNodeInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNodeInput.Unmarshal(m, b)
}
func (m *DeleteNodeInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNodeInput.Marshal(b, m, deterministic)
}
func (dst *DeleteNodeInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNodeInput.Merge(dst, src)
}
func (m *DeleteNodeInput) XXX_Size() int {
	return xxx_messageInfo_DeleteNodeInput.Size(m)
}
func (m *DeleteNodeInput) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNodeInput.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNodeInput proto.InternalMessageInfo

func (m *DeleteNodeInput) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *DeleteNodeInput) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *DeleteNodeInput) GetOrigin() *Origin {
	if m != nil {
		return m.Origin
	}
	return nil
}

type GetAncestorsInput struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAncestorsInput) Reset()         { *m = GetAncestorsInput{} }
func (m *GetAncestorsInput) String() string { return proto.CompactTextString(m) }
func (*GetAncestorsInput) ProtoMessage()    {}
func (*GetAncestorsInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_aeb914f4b76396b0, []int{10}
}
func (m *GetAncestorsInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAncestorsInput.Unmarshal(m, b)
}
func (m *GetAncestorsInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAncestorsInput.Marshal(b, m, deterministic)
}
func (dst *GetAncestorsInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAncestorsInput.Merge(dst, src)
}
func (m *GetAncestorsInput) XXX_Size() int {
	return xxx_messageInfo_GetAncestorsInput.Size(m)
}
func (m *GetAncestorsInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAncestorsInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetAncestorsInput proto.InternalMessageInfo

func (m *GetAncestorsInput) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

type GetAncestorsOutput struct {
	Nodes                []*AncestorNode `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetAncestorsOutput) Reset()         { *m = GetAncestorsOutput{} }
func (m *GetAncestorsOutput) String() string { return proto.CompactTextString(m) }
func (*GetAncestorsOutput) ProtoMessage()    {}
func (*GetAncestorsOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_aeb914f4b76396b0, []int{11}
}
func (m *GetAncestorsOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAncestorsOutput.Unmarshal(m, b)
}
func (m *GetAncestorsOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAncestorsOutput.Marshal(b, m, deterministic)
}
func (dst *GetAncestorsOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAncestorsOutput.Merge(dst, src)
}
func (m *GetAncestorsOutput) XXX_Size() int {
	return xxx_messageInfo_GetAncestorsOutput.Size(m)
}
func (m *GetAncestorsOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAncestorsOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetAncestorsOutput proto.InternalMessageInfo

func (m *GetAncestorsOutput) GetNodes() []*AncestorNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type AncestorNode struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Origin               *Origin  `protobuf:"bytes,2,opt,name=origin" json:"origin,omitempty"`
	Label                string   `protobuf:"bytes,3,opt,name=label" json:"label,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=type" json:"type,omitempty"`
	SubType              string   `protobuf:"bytes,6,opt,name=subType" json:"subType,omitempty"`
	ParentId             string   `protobuf:"bytes,7,opt,name=parentId" json:"parentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AncestorNode) Reset()         { *m = AncestorNode{} }
func (m *AncestorNode) String() string { return proto.CompactTextString(m) }
func (*AncestorNode) ProtoMessage()    {}
func (*AncestorNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_aeb914f4b76396b0, []int{12}
}
func (m *AncestorNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AncestorNode.Unmarshal(m, b)
}
func (m *AncestorNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AncestorNode.Marshal(b, m, deterministic)
}
func (dst *AncestorNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AncestorNode.Merge(dst, src)
}
func (m *AncestorNode) XXX_Size() int {
	return xxx_messageInfo_AncestorNode.Size(m)
}
func (m *AncestorNode) XXX_DiscardUnknown() {
	xxx_messageInfo_AncestorNode.DiscardUnknown(m)
}

var xxx_messageInfo_AncestorNode proto.InternalMessageInfo

func (m *AncestorNode) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AncestorNode) GetOrigin() *Origin {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (m *AncestorNode) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *AncestorNode) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AncestorNode) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AncestorNode) GetSubType() string {
	if m != nil {
		return m.SubType
	}
	return ""
}

func (m *AncestorNode) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

type FaultFrequencies struct {
	NodeId               string            `protobuf:"bytes,1,opt,name=nodeId" json:"nodeId,omitempty"`
	Faultfrequencies     []*FaultFrequency `protobuf:"bytes,2,rep,name=faultfrequencies" json:"faultfrequencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FaultFrequencies) Reset()         { *m = FaultFrequencies{} }
func (m *FaultFrequencies) String() string { return proto.CompactTextString(m) }
func (*FaultFrequencies) ProtoMessage()    {}
func (*FaultFrequencies) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_aeb914f4b76396b0, []int{13}
}
func (m *FaultFrequencies) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FaultFrequencies.Unmarshal(m, b)
}
func (m *FaultFrequencies) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FaultFrequencies.Marshal(b, m, deterministic)
}
func (dst *FaultFrequencies) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaultFrequencies.Merge(dst, src)
}
func (m *FaultFrequencies) XXX_Size() int {
	return xxx_messageInfo_FaultFrequencies.Size(m)
}
func (m *FaultFrequencies) XXX_DiscardUnknown() {
	xxx_messageInfo_FaultFrequencies.DiscardUnknown(m)
}

var xxx_messageInfo_FaultFrequencies proto.InternalMessageInfo

func (m *FaultFrequencies) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *FaultFrequencies) GetFaultfrequencies() []*FaultFrequency {
	if m != nil {
		return m.Faultfrequencies
	}
	return nil
}

type FaultFrequency struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Manufacturer         string   `protobuf:"bytes,4,opt,name=manufacturer" json:"manufacturer,omitempty"`
	FamilyType           string   `protobuf:"bytes,5,opt,name=familyType" json:"familyType,omitempty"`
	BPFO                 float64  `protobuf:"fixed64,6,opt,name=BPFO" json:"BPFO,omitempty"`
	BPFI                 float64  `protobuf:"fixed64,7,opt,name=BPFI" json:"BPFI,omitempty"`
	BSF                  float64  `protobuf:"fixed64,8,opt,name=BSF" json:"BSF,omitempty"`
	FTF                  float64  `protobuf:"fixed64,9,opt,name=FTF" json:"FTF,omitempty"`
	RPM                  float64  `protobuf:"fixed64,10,opt,name=RPM" json:"RPM,omitempty"`
	Type                 int32    `protobuf:"varint,11,opt,name=type" json:"type,omitempty"`
	Multiple             int32    `protobuf:"varint,12,opt,name=multiple" json:"multiple,omitempty"`
	Bandwidth            int32    `protobuf:"varint,13,opt,name=bandwidth" json:"bandwidth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FaultFrequency) Reset()         { *m = FaultFrequency{} }
func (m *FaultFrequency) String() string { return proto.CompactTextString(m) }
func (*FaultFrequency) ProtoMessage()    {}
func (*FaultFrequency) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_aeb914f4b76396b0, []int{14}
}
func (m *FaultFrequency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FaultFrequency.Unmarshal(m, b)
}
func (m *FaultFrequency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FaultFrequency.Marshal(b, m, deterministic)
}
func (dst *FaultFrequency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaultFrequency.Merge(dst, src)
}
func (m *FaultFrequency) XXX_Size() int {
	return xxx_messageInfo_FaultFrequency.Size(m)
}
func (m *FaultFrequency) XXX_DiscardUnknown() {
	xxx_messageInfo_FaultFrequency.DiscardUnknown(m)
}

var xxx_messageInfo_FaultFrequency proto.InternalMessageInfo

func (m *FaultFrequency) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FaultFrequency) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FaultFrequency) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *FaultFrequency) GetManufacturer() string {
	if m != nil {
		return m.Manufacturer
	}
	return ""
}

func (m *FaultFrequency) GetFamilyType() string {
	if m != nil {
		return m.FamilyType
	}
	return ""
}

func (m *FaultFrequency) GetBPFO() float64 {
	if m != nil {
		return m.BPFO
	}
	return 0
}

func (m *FaultFrequency) GetBPFI() float64 {
	if m != nil {
		return m.BPFI
	}
	return 0
}

func (m *FaultFrequency) GetBSF() float64 {
	if m != nil {
		return m.BSF
	}
	return 0
}

func (m *FaultFrequency) GetFTF() float64 {
	if m != nil {
		return m.FTF
	}
	return 0
}

func (m *FaultFrequency) GetRPM() float64 {
	if m != nil {
		return m.RPM
	}
	return 0
}

func (m *FaultFrequency) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *FaultFrequency) GetMultiple() int32 {
	if m != nil {
		return m.Multiple
	}
	return 0
}

func (m *FaultFrequency) GetBandwidth() int32 {
	if m != nil {
		return m.Bandwidth
	}
	return 0
}

type PrimitiveString struct {
	Value                string   `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimitiveString) Reset()         { *m = PrimitiveString{} }
func (m *PrimitiveString) String() string { return proto.CompactTextString(m) }
func (*PrimitiveString) ProtoMessage()    {}
func (*PrimitiveString) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_aeb914f4b76396b0, []int{15}
}
func (m *PrimitiveString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimitiveString.Unmarshal(m, b)
}
func (m *PrimitiveString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimitiveString.Marshal(b, m, deterministic)
}
func (dst *PrimitiveString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimitiveString.Merge(dst, src)
}
func (m *PrimitiveString) XXX_Size() int {
	return xxx_messageInfo_PrimitiveString.Size(m)
}
func (m *PrimitiveString) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimitiveString.DiscardUnknown(m)
}

var xxx_messageInfo_PrimitiveString proto.InternalMessageInfo

func (m *PrimitiveString) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PrimitiveInt32 struct {
	Value                int32    `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimitiveInt32) Reset()         { *m = PrimitiveInt32{} }
func (m *PrimitiveInt32) String() string { return proto.CompactTextString(m) }
func (*PrimitiveInt32) ProtoMessage()    {}
func (*PrimitiveInt32) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_aeb914f4b76396b0, []int{16}
}
func (m *PrimitiveInt32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimitiveInt32.Unmarshal(m, b)
}
func (m *PrimitiveInt32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimitiveInt32.Marshal(b, m, deterministic)
}
func (dst *PrimitiveInt32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimitiveInt32.Merge(dst, src)
}
func (m *PrimitiveInt32) XXX_Size() int {
	return xxx_messageInfo_PrimitiveInt32.Size(m)
}
func (m *PrimitiveInt32) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimitiveInt32.DiscardUnknown(m)
}

var xxx_messageInfo_PrimitiveInt32 proto.InternalMessageInfo

func (m *PrimitiveInt32) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type PrimitiveBytes struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimitiveBytes) Reset()         { *m = PrimitiveBytes{} }
func (m *PrimitiveBytes) String() string { return proto.CompactTextString(m) }
func (*PrimitiveBytes) ProtoMessage()    {}
func (*PrimitiveBytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_aeb914f4b76396b0, []int{17}
}
func (m *PrimitiveBytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimitiveBytes.Unmarshal(m, b)
}
func (m *PrimitiveBytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimitiveBytes.Marshal(b, m, deterministic)
}
func (dst *PrimitiveBytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimitiveBytes.Merge(dst, src)
}
func (m *PrimitiveBytes) XXX_Size() int {
	return xxx_messageInfo_PrimitiveBytes.Size(m)
}
func (m *PrimitiveBytes) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimitiveBytes.DiscardUnknown(m)
}

var xxx_messageInfo_PrimitiveBytes proto.InternalMessageInfo

func (m *PrimitiveBytes) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type PrimitiveVoid struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimitiveVoid) Reset()         { *m = PrimitiveVoid{} }
func (m *PrimitiveVoid) String() string { return proto.CompactTextString(m) }
func (*PrimitiveVoid) ProtoMessage()    {}
func (*PrimitiveVoid) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_aeb914f4b76396b0, []int{18}
}
func (m *PrimitiveVoid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimitiveVoid.Unmarshal(m, b)
}
func (m *PrimitiveVoid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimitiveVoid.Marshal(b, m, deterministic)
}
func (dst *PrimitiveVoid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimitiveVoid.Merge(dst, src)
}
func (m *PrimitiveVoid) XXX_Size() int {
	return xxx_messageInfo_PrimitiveVoid.Size(m)
}
func (m *PrimitiveVoid) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimitiveVoid.DiscardUnknown(m)
}

var xxx_messageInfo_PrimitiveVoid proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Origin)(nil), "grpcapi.Origin")
	proto.RegisterType((*MeasurementPoint)(nil), "grpcapi.MeasurementPoint")
	proto.RegisterType((*InspectionPoint)(nil), "grpcapi.InspectionPoint")
	proto.RegisterType((*AssetNode)(nil), "grpcapi.AssetNode")
	proto.RegisterType((*Node)(nil), "grpcapi.Node")
	proto.RegisterType((*Nodes)(nil), "grpcapi.Nodes")
	proto.RegisterType((*GetEventsInput)(nil), "grpcapi.GetEventsInput")
	proto.RegisterType((*GetEventsOutput)(nil), "grpcapi.GetEventsOutput")
	proto.RegisterType((*SaveNodeInput)(nil), "grpcapi.SaveNodeInput")
	proto.RegisterType((*DeleteNodeInput)(nil), "grpcapi.DeleteNodeInput")
	proto.RegisterType((*GetAncestorsInput)(nil), "grpcapi.GetAncestorsInput")
	proto.RegisterType((*GetAncestorsOutput)(nil), "grpcapi.GetAncestorsOutput")
	proto.RegisterType((*AncestorNode)(nil), "grpcapi.AncestorNode")
	proto.RegisterType((*FaultFrequencies)(nil), "grpcapi.FaultFrequencies")
	proto.RegisterType((*FaultFrequency)(nil), "grpcapi.FaultFrequency")
	proto.RegisterType((*PrimitiveString)(nil), "grpcapi.PrimitiveString")
	proto.RegisterType((*PrimitiveInt32)(nil), "grpcapi.PrimitiveInt32")
	proto.RegisterType((*PrimitiveBytes)(nil), "grpcapi.PrimitiveBytes")
	proto.RegisterType((*PrimitiveVoid)(nil), "grpcapi.PrimitiveVoid")
	proto.RegisterEnum("grpcapi.ValueType", ValueType_name, ValueType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HierarchyClient is the client API for Hierarchy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HierarchyClient interface {
	DeepPing(ctx context.Context, in *PrimitiveVoid, opts ...grpc.CallOption) (*PrimitiveString, error)
	GetNode(ctx context.Context, in *PrimitiveString, opts ...grpc.CallOption) (*Node, error)
	GetNodes(ctx context.Context, in *PrimitiveString, opts ...grpc.CallOption) (*Nodes, error)
	GetChildNodes(ctx context.Context, in *PrimitiveString, opts ...grpc.CallOption) (*Nodes, error)
	GetParentNode(ctx context.Context, in *PrimitiveString, opts ...grpc.CallOption) (*Node, error)
	GetAncestors(ctx context.Context, in *GetAncestorsInput, opts ...grpc.CallOption) (*GetAncestorsOutput, error)
	GetNodeIdByOrigin(ctx context.Context, in *Origin, opts ...grpc.CallOption) (*PrimitiveString, error)
	SaveNode(ctx context.Context, in *SaveNodeInput, opts ...grpc.CallOption) (*PrimitiveString, error)
	DeleteNode(ctx context.Context, in *DeleteNodeInput, opts ...grpc.CallOption) (*PrimitiveVoid, error)
	GetEvents(ctx context.Context, in *GetEventsInput, opts ...grpc.CallOption) (*GetEventsOutput, error)
	GetFaultFrequencies(ctx context.Context, in *PrimitiveString, opts ...grpc.CallOption) (*FaultFrequencies, error)
	SetFaultFrequencies(ctx context.Context, in *FaultFrequencies, opts ...grpc.CallOption) (*PrimitiveVoid, error)
}

type hierarchyClient struct {
	cc *grpc.ClientConn
}

func NewHierarchyClient(cc *grpc.ClientConn) HierarchyClient {
	return &hierarchyClient{cc}
}

func (c *hierarchyClient) DeepPing(ctx context.Context, in *PrimitiveVoid, opts ...grpc.CallOption) (*PrimitiveString, error) {
	out := new(PrimitiveString)
	err := c.cc.Invoke(ctx, "/grpcapi.Hierarchy/DeepPing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyClient) GetNode(ctx context.Context, in *PrimitiveString, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := c.cc.Invoke(ctx, "/grpcapi.Hierarchy/GetNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyClient) GetNodes(ctx context.Context, in *PrimitiveString, opts ...grpc.CallOption) (*Nodes, error) {
	out := new(Nodes)
	err := c.cc.Invoke(ctx, "/grpcapi.Hierarchy/GetNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyClient) GetChildNodes(ctx context.Context, in *PrimitiveString, opts ...grpc.CallOption) (*Nodes, error) {
	out := new(Nodes)
	err := c.cc.Invoke(ctx, "/grpcapi.Hierarchy/GetChildNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyClient) GetParentNode(ctx context.Context, in *PrimitiveString, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := c.cc.Invoke(ctx, "/grpcapi.Hierarchy/GetParentNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyClient) GetAncestors(ctx context.Context, in *GetAncestorsInput, opts ...grpc.CallOption) (*GetAncestorsOutput, error) {
	out := new(GetAncestorsOutput)
	err := c.cc.Invoke(ctx, "/grpcapi.Hierarchy/GetAncestors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyClient) GetNodeIdByOrigin(ctx context.Context, in *Origin, opts ...grpc.CallOption) (*PrimitiveString, error) {
	out := new(PrimitiveString)
	err := c.cc.Invoke(ctx, "/grpcapi.Hierarchy/GetNodeIdByOrigin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyClient) SaveNode(ctx context.Context, in *SaveNodeInput, opts ...grpc.CallOption) (*PrimitiveString, error) {
	out := new(PrimitiveString)
	err := c.cc.Invoke(ctx, "/grpcapi.Hierarchy/SaveNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyClient) DeleteNode(ctx context.Context, in *DeleteNodeInput, opts ...grpc.CallOption) (*PrimitiveVoid, error) {
	out := new(PrimitiveVoid)
	err := c.cc.Invoke(ctx, "/grpcapi.Hierarchy/DeleteNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyClient) GetEvents(ctx context.Context, in *GetEventsInput, opts ...grpc.CallOption) (*GetEventsOutput, error) {
	out := new(GetEventsOutput)
	err := c.cc.Invoke(ctx, "/grpcapi.Hierarchy/GetEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyClient) GetFaultFrequencies(ctx context.Context, in *PrimitiveString, opts ...grpc.CallOption) (*FaultFrequencies, error) {
	out := new(FaultFrequencies)
	err := c.cc.Invoke(ctx, "/grpcapi.Hierarchy/GetFaultFrequencies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyClient) SetFaultFrequencies(ctx context.Context, in *FaultFrequencies, opts ...grpc.CallOption) (*PrimitiveVoid, error) {
	out := new(PrimitiveVoid)
	err := c.cc.Invoke(ctx, "/grpcapi.Hierarchy/SetFaultFrequencies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HierarchyServer is the server API for Hierarchy service.
type HierarchyServer interface {
	DeepPing(context.Context, *PrimitiveVoid) (*PrimitiveString, error)
	GetNode(context.Context, *PrimitiveString) (*Node, error)
	GetNodes(context.Context, *PrimitiveString) (*Nodes, error)
	GetChildNodes(context.Context, *PrimitiveString) (*Nodes, error)
	GetParentNode(context.Context, *PrimitiveString) (*Node, error)
	GetAncestors(context.Context, *GetAncestorsInput) (*GetAncestorsOutput, error)
	GetNodeIdByOrigin(context.Context, *Origin) (*PrimitiveString, error)
	SaveNode(context.Context, *SaveNodeInput) (*PrimitiveString, error)
	DeleteNode(context.Context, *DeleteNodeInput) (*PrimitiveVoid, error)
	GetEvents(context.Context, *GetEventsInput) (*GetEventsOutput, error)
	GetFaultFrequencies(context.Context, *PrimitiveString) (*FaultFrequencies, error)
	SetFaultFrequencies(context.Context, *FaultFrequencies) (*PrimitiveVoid, error)
}

func RegisterHierarchyServer(s *grpc.Server, srv HierarchyServer) {
	s.RegisterService(&_Hierarchy_serviceDesc, srv)
}

func _Hierarchy_DeepPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimitiveVoid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServer).DeepPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Hierarchy/DeepPing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServer).DeepPing(ctx, req.(*PrimitiveVoid))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hierarchy_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimitiveString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Hierarchy/GetNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServer).GetNode(ctx, req.(*PrimitiveString))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hierarchy_GetNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimitiveString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServer).GetNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Hierarchy/GetNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServer).GetNodes(ctx, req.(*PrimitiveString))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hierarchy_GetChildNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimitiveString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServer).GetChildNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Hierarchy/GetChildNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServer).GetChildNodes(ctx, req.(*PrimitiveString))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hierarchy_GetParentNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimitiveString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServer).GetParentNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Hierarchy/GetParentNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServer).GetParentNode(ctx, req.(*PrimitiveString))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hierarchy_GetAncestors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAncestorsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServer).GetAncestors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Hierarchy/GetAncestors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServer).GetAncestors(ctx, req.(*GetAncestorsInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hierarchy_GetNodeIdByOrigin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Origin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServer).GetNodeIdByOrigin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Hierarchy/GetNodeIdByOrigin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServer).GetNodeIdByOrigin(ctx, req.(*Origin))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hierarchy_SaveNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveNodeInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServer).SaveNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Hierarchy/SaveNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServer).SaveNode(ctx, req.(*SaveNodeInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hierarchy_DeleteNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodeInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServer).DeleteNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Hierarchy/DeleteNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServer).DeleteNode(ctx, req.(*DeleteNodeInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hierarchy_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Hierarchy/GetEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServer).GetEvents(ctx, req.(*GetEventsInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hierarchy_GetFaultFrequencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimitiveString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServer).GetFaultFrequencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Hierarchy/GetFaultFrequencies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServer).GetFaultFrequencies(ctx, req.(*PrimitiveString))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hierarchy_SetFaultFrequencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FaultFrequencies)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServer).SetFaultFrequencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Hierarchy/SetFaultFrequencies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServer).SetFaultFrequencies(ctx, req.(*FaultFrequencies))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hierarchy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapi.Hierarchy",
	HandlerType: (*HierarchyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeepPing",
			Handler:    _Hierarchy_DeepPing_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _Hierarchy_GetNode_Handler,
		},
		{
			MethodName: "GetNodes",
			Handler:    _Hierarchy_GetNodes_Handler,
		},
		{
			MethodName: "GetChildNodes",
			Handler:    _Hierarchy_GetChildNodes_Handler,
		},
		{
			MethodName: "GetParentNode",
			Handler:    _Hierarchy_GetParentNode_Handler,
		},
		{
			MethodName: "GetAncestors",
			Handler:    _Hierarchy_GetAncestors_Handler,
		},
		{
			MethodName: "GetNodeIdByOrigin",
			Handler:    _Hierarchy_GetNodeIdByOrigin_Handler,
		},
		{
			MethodName: "SaveNode",
			Handler:    _Hierarchy_SaveNode_Handler,
		},
		{
			MethodName: "DeleteNode",
			Handler:    _Hierarchy_DeleteNode_Handler,
		},
		{
			MethodName: "GetEvents",
			Handler:    _Hierarchy_GetEvents_Handler,
		},
		{
			MethodName: "GetFaultFrequencies",
			Handler:    _Hierarchy_GetFaultFrequencies_Handler,
		},
		{
			MethodName: "SetFaultFrequencies",
			Handler:    _Hierarchy_SetFaultFrequencies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcapi.proto",
}

func init() { proto.RegisterFile("grpcapi.proto", fileDescriptor_grpcapi_aeb914f4b76396b0) }

var fileDescriptor_grpcapi_aeb914f4b76396b0 = []byte{
	// 1138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0x5b, 0x6f, 0xe3, 0x44,
	0x14, 0x8e, 0x73, 0x6d, 0x4e, 0xae, 0x9d, 0x2d, 0xad, 0x37, 0x20, 0x54, 0x8c, 0xc4, 0x16, 0xd8,
	0xae, 0x50, 0x8a, 0x78, 0x00, 0xb1, 0xda, 0xa6, 0x9b, 0xa4, 0x46, 0x6d, 0x13, 0x39, 0xed, 0xbe,
	0x56, 0x6e, 0x3c, 0x6d, 0x07, 0x39, 0x4e, 0xb0, 0xc7, 0x5d, 0xe5, 0x9d, 0x7f, 0x81, 0x78, 0xe3,
	0x99, 0x9f, 0x81, 0xc4, 0xbf, 0x5a, 0xcd, 0xf1, 0x64, 0x6c, 0xe7, 0xa6, 0xdd, 0xb7, 0x39, 0x57,
	0x9f, 0xf9, 0xce, 0x37, 0xe7, 0x24, 0x50, 0x7b, 0xf0, 0x67, 0x63, 0x7b, 0xc6, 0x5e, 0xcd, 0xfc,
	0x29, 0x9f, 0x92, 0x92, 0x14, 0x8d, 0x73, 0x28, 0x0e, 0x7c, 0xf6, 0xc0, 0x3c, 0x52, 0x87, 0x2c,
	0x73, 0x74, 0xed, 0x50, 0x3b, 0x2a, 0x5b, 0x59, 0xe6, 0x10, 0x02, 0x79, 0x3e, 0x9f, 0x51, 0x3d,
	0x8b, 0x1a, 0x3c, 0x93, 0x16, 0xec, 0xcc, 0xfc, 0xe9, 0x13, 0x73, 0xa8, 0xaf, 0xe7, 0x50, 0xaf,
	0x64, 0xe3, 0x1f, 0x0d, 0x9a, 0x97, 0xd4, 0x0e, 0x42, 0x9f, 0x4e, 0xa8, 0xc7, 0x87, 0x53, 0xe6,
	0x71, 0xa2, 0x43, 0xc9, 0xf6, 0x1e, 0x42, 0xd7, 0xf6, 0x65, 0xe6, 0x85, 0x28, 0x2c, 0x77, 0xd4,
	0xf6, 0x99, 0xf7, 0x80, 0x99, 0x0a, 0xd6, 0x42, 0x24, 0x47, 0xd0, 0x98, 0xc4, 0x79, 0xae, 0x45,
	0x0d, 0x79, 0x8c, 0x5d, 0x56, 0x93, 0x3d, 0x28, 0x04, 0x8f, 0xf6, 0x3d, 0xd7, 0x0b, 0x68, 0x8f,
	0x04, 0xf2, 0x05, 0x94, 0xf1, 0x30, 0x62, 0x0e, 0xd5, 0x8b, 0x68, 0x89, 0x15, 0xc6, 0xbf, 0x1a,
	0x34, 0x4c, 0x2f, 0x98, 0xd1, 0x31, 0x67, 0x53, 0x2f, 0xaa, 0xf2, 0x18, 0xc8, 0xa0, 0x33, 0x1a,
	0x5c, 0x74, 0xaf, 0xbb, 0xb7, 0x4f, 0xb6, 0x1b, 0x52, 0xfc, 0x68, 0x54, 0xf0, 0xee, 0xc2, 0xf2,
	0x6e, 0x61, 0x20, 0x3f, 0x40, 0x39, 0xf6, 0x12, 0xa5, 0xd5, 0xdb, 0xe4, 0xd5, 0x02, 0x5f, 0xe5,
	0x66, 0xc5, 0x4e, 0xe4, 0x10, 0x2a, 0x5e, 0x38, 0xa1, 0x3e, 0x1b, 0xdf, 0x78, 0x8c, 0x4b, 0x48,
	0x93, 0xaa, 0x08, 0xa8, 0xe0, 0x3d, 0xf5, 0x03, 0x3d, 0x77, 0x98, 0x8b, 0x80, 0x42, 0xd1, 0x38,
	0x86, 0xf2, 0x69, 0x10, 0x50, 0x7e, 0x35, 0x75, 0x30, 0xd1, 0xd8, 0x67, 0x9c, 0x8d, 0x6d, 0x97,
	0xf1, 0xb9, 0x2c, 0x31, 0xa9, 0x32, 0xfe, 0xcc, 0x41, 0x1e, 0x5d, 0x97, 0xfb, 0xb9, 0x07, 0x05,
	0xd7, 0xbe, 0xa3, 0xae, 0xfc, 0x7a, 0x24, 0x88, 0x84, 0x0e, 0x0d, 0xc6, 0x3e, 0x9b, 0x09, 0x38,
	0x64, 0x53, 0x93, 0x2a, 0xc5, 0x83, 0x7c, 0x82, 0x07, 0x4b, 0x65, 0x14, 0x56, 0xca, 0x10, 0xf7,
	0x09, 0xc2, 0x3b, 0x44, 0x28, 0x6a, 0xc1, 0x42, 0x24, 0x2f, 0xa0, 0x38, 0x45, 0xc6, 0xe9, 0xa5,
	0x43, 0xed, 0xa8, 0xd2, 0x6e, 0x28, 0xe8, 0x22, 0x22, 0x5a, 0xd2, 0x2c, 0x60, 0xb6, 0x17, 0x17,
	0xd7, 0x77, 0xd0, 0x37, 0x86, 0x59, 0x41, 0x62, 0xc5, 0x4e, 0xa4, 0x0b, 0xcd, 0xc9, 0x12, 0x03,
	0xf5, 0x32, 0x06, 0x3e, 0x57, 0x81, 0xcb, 0x14, 0xb5, 0x56, 0x42, 0x48, 0x07, 0x1a, 0x2c, 0xcd,
	0x10, 0x1d, 0x30, 0x8b, 0xae, 0xb2, 0x2c, 0x31, 0xc8, 0x5a, 0x0e, 0x30, 0x5e, 0x42, 0x41, 0x94,
	0x14, 0x90, 0xaf, 0xa1, 0xe0, 0x89, 0x83, 0xae, 0x1d, 0xe6, 0x8e, 0x2a, 0xed, 0x9a, 0x4a, 0x81,
	0xc5, 0x47, 0x36, 0xe3, 0x06, 0xea, 0x7d, 0xca, 0xbb, 0x4f, 0xd4, 0xe3, 0x81, 0xe9, 0xcd, 0x42,
	0x8e, 0xd4, 0x66, 0xde, 0x38, 0x62, 0x61, 0xce, 0x8a, 0x04, 0x72, 0x0c, 0x05, 0x97, 0x4d, 0x24,
	0x83, 0x2a, 0xed, 0x03, 0x95, 0x6c, 0xe8, 0x0b, 0x35, 0x7b, 0xa2, 0xa6, 0xc7, 0x4f, 0xda, 0x56,
	0xe4, 0x65, 0x7c, 0x0b, 0x0d, 0x95, 0x76, 0x10, 0x72, 0x91, 0x77, 0x1f, 0x8a, 0x14, 0x65, 0x4c,
	0x5c, 0xb5, 0xa4, 0x64, 0xfc, 0xa5, 0x41, 0x6d, 0x64, 0x3f, 0x51, 0x51, 0x55, 0x54, 0xc1, 0x3e,
	0x14, 0xc3, 0x80, 0xfa, 0xe6, 0x82, 0x43, 0x52, 0x22, 0x5f, 0x41, 0x5e, 0x14, 0x8d, 0x54, 0x59,
	0xb9, 0x0f, 0x9a, 0x70, 0x4c, 0xd8, 0x3e, 0xf5, 0xb8, 0xe9, 0x48, 0xb6, 0x29, 0x99, 0x9c, 0x40,
	0x35, 0x3a, 0x47, 0xdd, 0x46, 0x5a, 0xad, 0x21, 0x41, 0xca, 0xc9, 0xf8, 0x1d, 0x1a, 0x6f, 0xa9,
	0x4b, 0xf9, 0x47, 0x94, 0xb7, 0x0f, 0x45, 0x51, 0x83, 0xfa, 0xb2, 0x94, 0x12, 0xb4, 0xcb, 0x6d,
	0xa5, 0x9d, 0xf1, 0x12, 0x76, 0xfb, 0x94, 0x9f, 0x7a, 0x63, 0x1a, 0xf0, 0xa9, 0x2f, 0xdb, 0x71,
	0x00, 0x25, 0x91, 0xe7, 0x56, 0xbd, 0x28, 0x99, 0xd6, 0x38, 0x05, 0x92, 0xf4, 0x96, 0x28, 0x7f,
	0x9f, 0x6e, 0xfa, 0x67, 0x31, 0x6d, 0xa5, 0x63, 0xb2, 0xf9, 0xff, 0x6b, 0x50, 0x4d, 0xea, 0x57,
	0x5e, 0x6e, 0x5c, 0x7a, 0x76, 0xfb, 0x8b, 0x51, 0x4f, 0x3c, 0xb7, 0xe5, 0x89, 0xe7, 0x37, 0x3f,
	0xf1, 0x42, 0xe2, 0x89, 0x6f, 0x7e, 0xc0, 0xc9, 0xee, 0x96, 0xd2, 0xdd, 0x35, 0xa6, 0xd0, 0xec,
	0xd9, 0xa1, 0xcb, 0x7b, 0x3e, 0xfd, 0x23, 0xa4, 0xde, 0x98, 0xd1, 0x20, 0xd1, 0x91, 0x14, 0x74,
	0xe4, 0x0c, 0x9a, 0xf7, 0xc2, 0xf7, 0x3e, 0xf6, 0xd5, 0xb3, 0x88, 0x57, 0xcc, 0xeb, 0x54, 0xb2,
	0xb9, 0xb5, 0x12, 0x60, 0xfc, 0x97, 0x85, 0x7a, 0xda, 0x69, 0xdd, 0x22, 0xf3, 0xec, 0x89, 0x5a,
	0x64, 0xe2, 0xfc, 0x11, 0x63, 0xcf, 0x80, 0xea, 0xc4, 0xf6, 0xc2, 0x7b, 0x7b, 0xcc, 0x43, 0x9f,
	0xfa, 0x12, 0xb6, 0x94, 0x8e, 0x7c, 0x09, 0x70, 0x6f, 0x4f, 0x98, 0x3b, 0xbf, 0x8e, 0xd1, 0x4b,
	0x68, 0xc4, 0x97, 0x3b, 0xc3, 0xde, 0x00, 0x01, 0xd4, 0x2c, 0x3c, 0x4b, 0x9d, 0x89, 0xc8, 0x45,
	0x3a, 0x93, 0x34, 0x21, 0xd7, 0x19, 0xf5, 0x70, 0xc6, 0x69, 0x96, 0x38, 0x0a, 0x4d, 0xef, 0xba,
	0x87, 0xc3, 0x4b, 0xb3, 0xc4, 0x51, 0x68, 0xac, 0xe1, 0x25, 0x0e, 0x22, 0xcd, 0x12, 0x47, 0xd5,
	0xb5, 0x0a, 0xae, 0x4f, 0xb5, 0xa0, 0x27, 0xa1, 0xcb, 0xd9, 0xcc, 0xa5, 0x7a, 0x15, 0xf5, 0x4a,
	0x16, 0x7b, 0xf1, 0xce, 0xf6, 0x9c, 0xf7, 0xcc, 0xe1, 0x8f, 0x7a, 0x0d, 0x8d, 0xb1, 0xc2, 0x78,
	0x01, 0x0d, 0x35, 0x44, 0x46, 0x1c, 0x17, 0xf1, 0x1e, 0x14, 0x70, 0x85, 0x49, 0x2c, 0x23, 0xc1,
	0xf8, 0x06, 0xea, 0xe9, 0x69, 0x93, 0xf6, 0x2b, 0xac, 0xf3, 0xeb, 0xcc, 0x39, 0x0d, 0xd2, 0x7e,
	0xd5, 0x85, 0x5f, 0x03, 0x6a, 0xca, 0xef, 0xdd, 0x94, 0x39, 0xdf, 0xfd, 0x0a, 0xe5, 0x78, 0xd7,
	0x56, 0xa0, 0x74, 0x75, 0x73, 0xd9, 0xb5, 0xcc, 0xb3, 0x66, 0x86, 0xec, 0x42, 0x6d, 0x64, 0x5e,
	0xf5, 0x2f, 0xba, 0xb7, 0x67, 0xe7, 0x03, 0xf3, 0xac, 0xdb, 0xd4, 0x48, 0x13, 0xaa, 0x97, 0x37,
	0x17, 0xd7, 0xe6, 0x42, 0x93, 0x6d, 0xff, 0x5d, 0x84, 0xf2, 0x39, 0xa3, 0xbe, 0xed, 0x8f, 0x1f,
	0xe7, 0xe4, 0x35, 0xec, 0xbc, 0xa5, 0x74, 0x36, 0x14, 0xf7, 0xd9, 0x5f, 0x1d, 0x97, 0xe2, 0x83,
	0x2d, 0x7d, 0x55, 0x1f, 0x21, 0x60, 0x64, 0xc8, 0x8f, 0x50, 0xea, 0xcb, 0xed, 0xb2, 0xd1, 0xad,
	0x95, 0x1e, 0x82, 0x46, 0x86, 0xfc, 0x04, 0x3b, 0x32, 0x2a, 0xd8, 0x12, 0x56, 0x4f, 0x85, 0x05,
	0x46, 0x86, 0xfc, 0x02, 0xb5, 0x3e, 0xe5, 0x67, 0x8f, 0xcc, 0x75, 0x3e, 0x3d, 0xf8, 0x67, 0x0c,
	0x1e, 0xe2, 0x53, 0xfc, 0xd4, 0x82, 0x4d, 0xa8, 0x26, 0xc7, 0x18, 0x69, 0x29, 0x87, 0x95, 0x59,
	0xd8, 0xfa, 0x7c, 0xad, 0x2d, 0x9a, 0x7c, 0x46, 0x86, 0xbc, 0xc1, 0xf9, 0x89, 0x83, 0xda, 0xe9,
	0xcc, 0xe5, 0x8f, 0xcb, 0xe5, 0x91, 0xb5, 0x15, 0xf3, 0xd7, 0xb0, 0xb3, 0x58, 0x45, 0x89, 0x9e,
	0xa5, 0xb6, 0xd3, 0xd6, 0xf8, 0x37, 0x00, 0xf1, 0xb6, 0x48, 0xa0, 0xb0, 0xb4, 0x42, 0x5a, 0x1b,
	0xf8, 0x80, 0x19, 0xca, 0x6a, 0x71, 0x92, 0x83, 0xe4, 0x7d, 0x13, 0x3b, 0x3a, 0x51, 0xc3, 0xd2,
	0x96, 0x35, 0x32, 0xe4, 0x02, 0x9e, 0xf5, 0x29, 0x5f, 0x99, 0x85, 0x9b, 0x5b, 0xf2, 0x7c, 0xfd,
	0xcc, 0x63, 0xd8, 0xda, 0xdf, 0xe0, 0xd9, 0x68, 0x4d, 0xb6, 0xcd, 0x31, 0x9b, 0xef, 0x76, 0x57,
	0xc4, 0x7f, 0x00, 0x27, 0x1f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa2, 0xa8, 0x9b, 0x0d, 0x12, 0x0c,
	0x00, 0x00,
}
