// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpcapi.proto

/*
Package grpcapi is a generated protocol buffer package.

It is generated from these files:
	grpcapi.proto

It has these top-level messages:
	Origin
	MeasurementPoint
	InspectionPoint
	AssetNode
	Node
	Nodes
	GetEventsInput
	GetEventsOutput
	SaveNodeInput
	DeleteNodeInput
	PrimitiveString
	PrimitiveInt32
	PrimitiveBytes
	PrimitiveVoid
*/
package grpcapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Origin struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type     string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Provider string `protobuf:"bytes,3,opt,name=provider" json:"provider,omitempty"`
}

func (m *Origin) Reset()                    { *m = Origin{} }
func (m *Origin) String() string            { return proto.CompactTextString(m) }
func (*Origin) ProtoMessage()               {}
func (*Origin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Origin) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Origin) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Origin) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

type MeasurementPoint struct {
	Angular         string `protobuf:"bytes,1,opt,name=angular" json:"angular,omitempty"`
	Bearing         int32  `protobuf:"varint,3,opt,name=bearing" json:"bearing,omitempty"`
	MeasurementType string `protobuf:"bytes,4,opt,name=measurementType" json:"measurementType,omitempty"`
	Shaft           string `protobuf:"bytes,5,opt,name=shaft" json:"shaft,omitempty"`
	ShaftSide       string `protobuf:"bytes,6,opt,name=shaftSide" json:"shaftSide,omitempty"`
}

func (m *MeasurementPoint) Reset()                    { *m = MeasurementPoint{} }
func (m *MeasurementPoint) String() string            { return proto.CompactTextString(m) }
func (*MeasurementPoint) ProtoMessage()               {}
func (*MeasurementPoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MeasurementPoint) GetAngular() string {
	if m != nil {
		return m.Angular
	}
	return ""
}

func (m *MeasurementPoint) GetBearing() int32 {
	if m != nil {
		return m.Bearing
	}
	return 0
}

func (m *MeasurementPoint) GetMeasurementType() string {
	if m != nil {
		return m.MeasurementType
	}
	return ""
}

func (m *MeasurementPoint) GetShaft() string {
	if m != nil {
		return m.Shaft
	}
	return ""
}

func (m *MeasurementPoint) GetShaftSide() string {
	if m != nil {
		return m.ShaftSide
	}
	return ""
}

type InspectionPoint struct {
	ValueType   string `protobuf:"bytes,1,opt,name=valueType" json:"valueType,omitempty"`
	NumericUnit string `protobuf:"bytes,2,opt,name=numericUnit" json:"numericUnit,omitempty"`
}

func (m *InspectionPoint) Reset()                    { *m = InspectionPoint{} }
func (m *InspectionPoint) String() string            { return proto.CompactTextString(m) }
func (*InspectionPoint) ProtoMessage()               {}
func (*InspectionPoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *InspectionPoint) GetValueType() string {
	if m != nil {
		return m.ValueType
	}
	return ""
}

func (m *InspectionPoint) GetNumericUnit() string {
	if m != nil {
		return m.NumericUnit
	}
	return ""
}

type AssetNode struct {
	Criticality string `protobuf:"bytes,1,opt,name=criticality" json:"criticality,omitempty"`
}

func (m *AssetNode) Reset()                    { *m = AssetNode{} }
func (m *AssetNode) String() string            { return proto.CompactTextString(m) }
func (*AssetNode) ProtoMessage()               {}
func (*AssetNode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AssetNode) GetCriticality() string {
	if m != nil {
		return m.Criticality
	}
	return ""
}

type Node struct {
	Id               string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Label            string            `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
	Description      string            `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Type             string            `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
	Criticality      string            `protobuf:"bytes,5,opt,name=criticality" json:"criticality,omitempty"`
	SubType          string            `protobuf:"bytes,6,opt,name=subType" json:"subType,omitempty"`
	Origin           *Origin           `protobuf:"bytes,7,opt,name=origin" json:"origin,omitempty"`
	AssetNode        *AssetNode        `protobuf:"bytes,8,opt,name=assetNode" json:"assetNode,omitempty"`
	MeasurementPoint *MeasurementPoint `protobuf:"bytes,9,opt,name=measurementPoint" json:"measurementPoint,omitempty"`
	InspectionPoint  *InspectionPoint  `protobuf:"bytes,10,opt,name=inspectionPoint" json:"inspectionPoint,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Node) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Node) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Node) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Node) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Node) GetCriticality() string {
	if m != nil {
		return m.Criticality
	}
	return ""
}

func (m *Node) GetSubType() string {
	if m != nil {
		return m.SubType
	}
	return ""
}

func (m *Node) GetOrigin() *Origin {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (m *Node) GetAssetNode() *AssetNode {
	if m != nil {
		return m.AssetNode
	}
	return nil
}

func (m *Node) GetMeasurementPoint() *MeasurementPoint {
	if m != nil {
		return m.MeasurementPoint
	}
	return nil
}

func (m *Node) GetInspectionPoint() *InspectionPoint {
	if m != nil {
		return m.InspectionPoint
	}
	return nil
}

type Nodes struct {
	Nodes []*Node `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *Nodes) Reset()                    { *m = Nodes{} }
func (m *Nodes) String() string            { return proto.CompactTextString(m) }
func (*Nodes) ProtoMessage()               {}
func (*Nodes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Nodes) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type GetEventsInput struct {
	Since int64           `protobuf:"varint,1,opt,name=since" json:"since,omitempty"`
	Limit *PrimitiveInt32 `protobuf:"bytes,2,opt,name=limit" json:"limit,omitempty"`
}

func (m *GetEventsInput) Reset()                    { *m = GetEventsInput{} }
func (m *GetEventsInput) String() string            { return proto.CompactTextString(m) }
func (*GetEventsInput) ProtoMessage()               {}
func (*GetEventsInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetEventsInput) GetSince() int64 {
	if m != nil {
		return m.Since
	}
	return 0
}

func (m *GetEventsInput) GetLimit() *PrimitiveInt32 {
	if m != nil {
		return m.Limit
	}
	return nil
}

type GetEventsOutput struct {
	Events []byte `protobuf:"bytes,1,opt,name=events,proto3" json:"events,omitempty"`
}

func (m *GetEventsOutput) Reset()                    { *m = GetEventsOutput{} }
func (m *GetEventsOutput) String() string            { return proto.CompactTextString(m) }
func (*GetEventsOutput) ProtoMessage()               {}
func (*GetEventsOutput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetEventsOutput) GetEvents() []byte {
	if m != nil {
		return m.Events
	}
	return nil
}

type SaveNodeInput struct {
	UserId       string  `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
	Node         *Node   `protobuf:"bytes,3,opt,name=node" json:"node,omitempty"`
	ParentId     string  `protobuf:"bytes,2,opt,name=parentId" json:"parentId,omitempty"`
	ParentOrigin *Origin `protobuf:"bytes,4,opt,name=parentOrigin" json:"parentOrigin,omitempty"`
}

func (m *SaveNodeInput) Reset()                    { *m = SaveNodeInput{} }
func (m *SaveNodeInput) String() string            { return proto.CompactTextString(m) }
func (*SaveNodeInput) ProtoMessage()               {}
func (*SaveNodeInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *SaveNodeInput) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SaveNodeInput) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *SaveNodeInput) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *SaveNodeInput) GetParentOrigin() *Origin {
	if m != nil {
		return m.ParentOrigin
	}
	return nil
}

type DeleteNodeInput struct {
	UserId string  `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
	NodeId string  `protobuf:"bytes,2,opt,name=nodeId" json:"nodeId,omitempty"`
	Origin *Origin `protobuf:"bytes,3,opt,name=origin" json:"origin,omitempty"`
}

func (m *DeleteNodeInput) Reset()                    { *m = DeleteNodeInput{} }
func (m *DeleteNodeInput) String() string            { return proto.CompactTextString(m) }
func (*DeleteNodeInput) ProtoMessage()               {}
func (*DeleteNodeInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DeleteNodeInput) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *DeleteNodeInput) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *DeleteNodeInput) GetOrigin() *Origin {
	if m != nil {
		return m.Origin
	}
	return nil
}

type PrimitiveString struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *PrimitiveString) Reset()                    { *m = PrimitiveString{} }
func (m *PrimitiveString) String() string            { return proto.CompactTextString(m) }
func (*PrimitiveString) ProtoMessage()               {}
func (*PrimitiveString) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *PrimitiveString) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PrimitiveInt32 struct {
	Value int32 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *PrimitiveInt32) Reset()                    { *m = PrimitiveInt32{} }
func (m *PrimitiveInt32) String() string            { return proto.CompactTextString(m) }
func (*PrimitiveInt32) ProtoMessage()               {}
func (*PrimitiveInt32) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *PrimitiveInt32) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type PrimitiveBytes struct {
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *PrimitiveBytes) Reset()                    { *m = PrimitiveBytes{} }
func (m *PrimitiveBytes) String() string            { return proto.CompactTextString(m) }
func (*PrimitiveBytes) ProtoMessage()               {}
func (*PrimitiveBytes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *PrimitiveBytes) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type PrimitiveVoid struct {
}

func (m *PrimitiveVoid) Reset()                    { *m = PrimitiveVoid{} }
func (m *PrimitiveVoid) String() string            { return proto.CompactTextString(m) }
func (*PrimitiveVoid) ProtoMessage()               {}
func (*PrimitiveVoid) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func init() {
	proto.RegisterType((*Origin)(nil), "grpcapi.Origin")
	proto.RegisterType((*MeasurementPoint)(nil), "grpcapi.MeasurementPoint")
	proto.RegisterType((*InspectionPoint)(nil), "grpcapi.InspectionPoint")
	proto.RegisterType((*AssetNode)(nil), "grpcapi.AssetNode")
	proto.RegisterType((*Node)(nil), "grpcapi.Node")
	proto.RegisterType((*Nodes)(nil), "grpcapi.Nodes")
	proto.RegisterType((*GetEventsInput)(nil), "grpcapi.GetEventsInput")
	proto.RegisterType((*GetEventsOutput)(nil), "grpcapi.GetEventsOutput")
	proto.RegisterType((*SaveNodeInput)(nil), "grpcapi.SaveNodeInput")
	proto.RegisterType((*DeleteNodeInput)(nil), "grpcapi.DeleteNodeInput")
	proto.RegisterType((*PrimitiveString)(nil), "grpcapi.PrimitiveString")
	proto.RegisterType((*PrimitiveInt32)(nil), "grpcapi.PrimitiveInt32")
	proto.RegisterType((*PrimitiveBytes)(nil), "grpcapi.PrimitiveBytes")
	proto.RegisterType((*PrimitiveVoid)(nil), "grpcapi.PrimitiveVoid")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Hierarchy service

type HierarchyClient interface {
	DeepPing(ctx context.Context, in *PrimitiveVoid, opts ...grpc.CallOption) (*PrimitiveString, error)
	GetNode(ctx context.Context, in *PrimitiveString, opts ...grpc.CallOption) (*Node, error)
	GetNodes(ctx context.Context, in *PrimitiveString, opts ...grpc.CallOption) (*Nodes, error)
	SaveNode(ctx context.Context, in *SaveNodeInput, opts ...grpc.CallOption) (*PrimitiveString, error)
	DeleteNode(ctx context.Context, in *DeleteNodeInput, opts ...grpc.CallOption) (*PrimitiveVoid, error)
	GetEvents(ctx context.Context, in *GetEventsInput, opts ...grpc.CallOption) (*GetEventsOutput, error)
	GetEventStream(ctx context.Context, in *PrimitiveVoid, opts ...grpc.CallOption) (Hierarchy_GetEventStreamClient, error)
}

type hierarchyClient struct {
	cc *grpc.ClientConn
}

func NewHierarchyClient(cc *grpc.ClientConn) HierarchyClient {
	return &hierarchyClient{cc}
}

func (c *hierarchyClient) DeepPing(ctx context.Context, in *PrimitiveVoid, opts ...grpc.CallOption) (*PrimitiveString, error) {
	out := new(PrimitiveString)
	err := grpc.Invoke(ctx, "/grpcapi.Hierarchy/DeepPing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyClient) GetNode(ctx context.Context, in *PrimitiveString, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := grpc.Invoke(ctx, "/grpcapi.Hierarchy/GetNode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyClient) GetNodes(ctx context.Context, in *PrimitiveString, opts ...grpc.CallOption) (*Nodes, error) {
	out := new(Nodes)
	err := grpc.Invoke(ctx, "/grpcapi.Hierarchy/GetNodes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyClient) SaveNode(ctx context.Context, in *SaveNodeInput, opts ...grpc.CallOption) (*PrimitiveString, error) {
	out := new(PrimitiveString)
	err := grpc.Invoke(ctx, "/grpcapi.Hierarchy/SaveNode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyClient) DeleteNode(ctx context.Context, in *DeleteNodeInput, opts ...grpc.CallOption) (*PrimitiveVoid, error) {
	out := new(PrimitiveVoid)
	err := grpc.Invoke(ctx, "/grpcapi.Hierarchy/DeleteNode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyClient) GetEvents(ctx context.Context, in *GetEventsInput, opts ...grpc.CallOption) (*GetEventsOutput, error) {
	out := new(GetEventsOutput)
	err := grpc.Invoke(ctx, "/grpcapi.Hierarchy/GetEvents", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyClient) GetEventStream(ctx context.Context, in *PrimitiveVoid, opts ...grpc.CallOption) (Hierarchy_GetEventStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Hierarchy_serviceDesc.Streams[0], c.cc, "/grpcapi.Hierarchy/GetEventStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &hierarchyGetEventStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Hierarchy_GetEventStreamClient interface {
	Recv() (*PrimitiveBytes, error)
	grpc.ClientStream
}

type hierarchyGetEventStreamClient struct {
	grpc.ClientStream
}

func (x *hierarchyGetEventStreamClient) Recv() (*PrimitiveBytes, error) {
	m := new(PrimitiveBytes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Hierarchy service

type HierarchyServer interface {
	DeepPing(context.Context, *PrimitiveVoid) (*PrimitiveString, error)
	GetNode(context.Context, *PrimitiveString) (*Node, error)
	GetNodes(context.Context, *PrimitiveString) (*Nodes, error)
	SaveNode(context.Context, *SaveNodeInput) (*PrimitiveString, error)
	DeleteNode(context.Context, *DeleteNodeInput) (*PrimitiveVoid, error)
	GetEvents(context.Context, *GetEventsInput) (*GetEventsOutput, error)
	GetEventStream(*PrimitiveVoid, Hierarchy_GetEventStreamServer) error
}

func RegisterHierarchyServer(s *grpc.Server, srv HierarchyServer) {
	s.RegisterService(&_Hierarchy_serviceDesc, srv)
}

func _Hierarchy_DeepPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimitiveVoid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServer).DeepPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Hierarchy/DeepPing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServer).DeepPing(ctx, req.(*PrimitiveVoid))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hierarchy_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimitiveString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Hierarchy/GetNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServer).GetNode(ctx, req.(*PrimitiveString))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hierarchy_GetNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimitiveString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServer).GetNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Hierarchy/GetNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServer).GetNodes(ctx, req.(*PrimitiveString))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hierarchy_SaveNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveNodeInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServer).SaveNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Hierarchy/SaveNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServer).SaveNode(ctx, req.(*SaveNodeInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hierarchy_DeleteNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodeInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServer).DeleteNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Hierarchy/DeleteNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServer).DeleteNode(ctx, req.(*DeleteNodeInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hierarchy_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.Hierarchy/GetEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServer).GetEvents(ctx, req.(*GetEventsInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hierarchy_GetEventStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimitiveVoid)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HierarchyServer).GetEventStream(m, &hierarchyGetEventStreamServer{stream})
}

type Hierarchy_GetEventStreamServer interface {
	Send(*PrimitiveBytes) error
	grpc.ServerStream
}

type hierarchyGetEventStreamServer struct {
	grpc.ServerStream
}

func (x *hierarchyGetEventStreamServer) Send(m *PrimitiveBytes) error {
	return x.ServerStream.SendMsg(m)
}

var _Hierarchy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapi.Hierarchy",
	HandlerType: (*HierarchyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeepPing",
			Handler:    _Hierarchy_DeepPing_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _Hierarchy_GetNode_Handler,
		},
		{
			MethodName: "GetNodes",
			Handler:    _Hierarchy_GetNodes_Handler,
		},
		{
			MethodName: "SaveNode",
			Handler:    _Hierarchy_SaveNode_Handler,
		},
		{
			MethodName: "DeleteNode",
			Handler:    _Hierarchy_DeleteNode_Handler,
		},
		{
			MethodName: "GetEvents",
			Handler:    _Hierarchy_GetEvents_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEventStream",
			Handler:       _Hierarchy_GetEventStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpcapi.proto",
}

func init() { proto.RegisterFile("grpcapi.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 761 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x5d, 0x6f, 0xda, 0x48,
	0x14, 0xc5, 0x01, 0x03, 0xbe, 0x04, 0x1c, 0x8d, 0x22, 0xd6, 0x8b, 0x22, 0x2d, 0x3b, 0x2b, 0x6d,
	0x58, 0x69, 0x83, 0x22, 0xb2, 0xda, 0xc7, 0xd5, 0x16, 0x25, 0x4a, 0x78, 0x68, 0x43, 0x4d, 0xd3,
	0x77, 0x63, 0x4f, 0xc8, 0xb4, 0x66, 0x6c, 0x8d, 0xc7, 0x48, 0xbc, 0xf7, 0x5f, 0xf4, 0xb5, 0x3f,
	0xa5, 0x3f, 0xac, 0xf2, 0x78, 0xfc, 0x49, 0x12, 0xf5, 0xcd, 0xe7, 0xce, 0xbd, 0x67, 0xce, 0xdc,
	0x7b, 0x2e, 0x40, 0x7f, 0xc3, 0x43, 0xd7, 0x09, 0xe9, 0x34, 0xe4, 0x81, 0x08, 0x50, 0x47, 0x41,
	0x7c, 0x07, 0xed, 0x7b, 0x4e, 0x37, 0x94, 0xa1, 0x01, 0x1c, 0x51, 0xcf, 0xd2, 0xc6, 0xda, 0xc4,
	0xb0, 0x8f, 0xa8, 0x87, 0x10, 0xb4, 0xc4, 0x3e, 0x24, 0xd6, 0x91, 0x8c, 0xc8, 0x6f, 0x34, 0x82,
	0x6e, 0xc8, 0x83, 0x1d, 0xf5, 0x08, 0xb7, 0x9a, 0x32, 0x9e, 0x63, 0xfc, 0x4d, 0x83, 0x93, 0xb7,
	0xc4, 0x89, 0x62, 0x4e, 0xb6, 0x84, 0x89, 0x65, 0x40, 0x99, 0x40, 0x16, 0x74, 0x1c, 0xb6, 0x89,
	0x7d, 0x87, 0x2b, 0xe6, 0x0c, 0x26, 0x27, 0x6b, 0xe2, 0x70, 0xca, 0x36, 0x92, 0x49, 0xb7, 0x33,
	0x88, 0x26, 0x60, 0x6e, 0x0b, 0x9e, 0x0f, 0x89, 0x86, 0x96, 0xac, 0xad, 0x87, 0xd1, 0x29, 0xe8,
	0xd1, 0x93, 0xf3, 0x28, 0x2c, 0x5d, 0x9e, 0xa7, 0x00, 0x9d, 0x81, 0x21, 0x3f, 0x56, 0xd4, 0x23,
	0x56, 0x5b, 0x9e, 0x14, 0x01, 0xfc, 0x1e, 0xcc, 0x05, 0x8b, 0x42, 0xe2, 0x0a, 0x1a, 0xb0, 0x54,
	0xe4, 0x19, 0x18, 0x3b, 0xc7, 0x8f, 0x89, 0xbc, 0x2a, 0x95, 0x59, 0x04, 0xd0, 0x18, 0x7a, 0x2c,
	0xde, 0x12, 0x4e, 0xdd, 0x07, 0x46, 0x85, 0x6a, 0x47, 0x39, 0x84, 0x2f, 0xc0, 0x78, 0x13, 0x45,
	0x44, 0xbc, 0x0b, 0x3c, 0x99, 0xee, 0x72, 0x2a, 0xa8, 0xeb, 0xf8, 0x54, 0xec, 0x15, 0x5d, 0x39,
	0x84, 0xbf, 0x34, 0xa1, 0x25, 0x53, 0xeb, 0x1d, 0x3f, 0x05, 0xdd, 0x77, 0xd6, 0xc4, 0x57, 0x77,
	0xa4, 0x20, 0x21, 0xf4, 0x48, 0xe4, 0x72, 0x1a, 0x26, 0x8a, 0x55, 0xdb, 0xcb, 0xa1, 0x7c, 0x52,
	0xad, 0xd2, 0xa4, 0x6a, 0x32, 0xf4, 0x03, 0x19, 0xc9, 0x00, 0xa2, 0x78, 0x2d, 0xdf, 0x9c, 0x36,
	0x29, 0x83, 0xe8, 0x1c, 0xda, 0x81, 0xf4, 0x84, 0xd5, 0x19, 0x6b, 0x93, 0xde, 0xcc, 0x9c, 0x66,
	0xe6, 0x49, 0xad, 0x62, 0xab, 0x63, 0x74, 0x09, 0x86, 0x93, 0x3d, 0xdc, 0xea, 0xca, 0x5c, 0x94,
	0xe7, 0xe6, 0x2d, 0xb1, 0x8b, 0x24, 0x74, 0x03, 0x27, 0xdb, 0x9a, 0x47, 0x2c, 0x43, 0x16, 0xfe,
	0x9a, 0x17, 0xd6, 0x4d, 0x64, 0x1f, 0x94, 0xa0, 0x39, 0x98, 0xb4, 0x3a, 0x44, 0x0b, 0x24, 0x8b,
	0x95, 0xb3, 0xd4, 0x86, 0x6c, 0xd7, 0x0b, 0xf0, 0xdf, 0xa0, 0x27, 0x92, 0x22, 0xf4, 0x07, 0xe8,
	0x2c, 0xf9, 0xb0, 0xb4, 0x71, 0x73, 0xd2, 0x9b, 0xf5, 0x73, 0x0a, 0x29, 0x3e, 0x3d, 0xc3, 0x0f,
	0x30, 0xb8, 0x25, 0xe2, 0x66, 0x47, 0x98, 0x88, 0x16, 0x2c, 0x8c, 0x85, 0x34, 0x1f, 0x65, 0x6e,
	0xea, 0x98, 0xa6, 0x9d, 0x02, 0x74, 0x01, 0xba, 0x4f, 0xb7, 0xca, 0x27, 0xbd, 0xd9, 0x2f, 0x39,
	0xd9, 0x92, 0x27, 0x61, 0xba, 0x23, 0x0b, 0x26, 0xae, 0x66, 0x76, 0x9a, 0x85, 0xff, 0x02, 0x33,
	0xa7, 0xbd, 0x8f, 0x45, 0xc2, 0x3b, 0x84, 0x36, 0x91, 0x58, 0x12, 0x1f, 0xdb, 0x0a, 0xe1, 0xaf,
	0x1a, 0xf4, 0x57, 0xce, 0x8e, 0x24, 0xaa, 0x52, 0x05, 0x43, 0x68, 0xc7, 0x11, 0xe1, 0x8b, 0xcc,
	0x43, 0x0a, 0xa1, 0xdf, 0xa1, 0x95, 0x88, 0x96, 0x56, 0x39, 0x78, 0x8f, 0x3c, 0x92, 0x8b, 0xec,
	0x70, 0xc2, 0xc4, 0xc2, 0x53, 0x6e, 0xcb, 0x31, 0xba, 0x82, 0xe3, 0xf4, 0x3b, 0x9d, 0xb6, 0xb4,
	0xd5, 0x33, 0x26, 0xa8, 0x24, 0xe1, 0x4f, 0x60, 0x5e, 0x13, 0x9f, 0x88, 0x9f, 0x90, 0x37, 0x84,
	0x76, 0xa2, 0x21, 0xbf, 0x59, 0xa1, 0x92, 0xed, 0x9a, 0xaf, 0xda, 0x0e, 0x9f, 0x83, 0x99, 0x77,
	0x73, 0x25, 0xe4, 0x6f, 0xc6, 0x29, 0xe8, 0x72, 0x63, 0xd5, 0x55, 0x29, 0xc0, 0x7f, 0xc2, 0xa0,
	0xda, 0xf6, 0x6a, 0x9e, 0xfe, 0x5c, 0xde, 0x7c, 0x2f, 0x48, 0x54, 0xcd, 0x3b, 0xce, 0xf2, 0x4c,
	0xe8, 0xe7, 0x79, 0x1f, 0x03, 0xea, 0xcd, 0xbe, 0x37, 0xc1, 0xb8, 0xa3, 0x84, 0x3b, 0xdc, 0x7d,
	0xda, 0xa3, 0xff, 0xa0, 0x7b, 0x4d, 0x48, 0xb8, 0x4c, 0x04, 0x0d, 0x0f, 0x07, 0x9f, 0x54, 0x8c,
	0xac, 0xc3, 0x78, 0xfa, 0x04, 0xdc, 0x40, 0xff, 0x40, 0xe7, 0x56, 0xed, 0xc9, 0x8b, 0x69, 0xa3,
	0xea, 0x38, 0x71, 0x03, 0xfd, 0x0b, 0x5d, 0x55, 0x15, 0xbd, 0x52, 0x36, 0xa8, 0x94, 0x45, 0xb8,
	0x91, 0xa8, 0xcd, 0xec, 0x54, 0x52, 0x5b, 0x71, 0xd8, 0xab, 0x6a, 0xff, 0x07, 0x28, 0x26, 0x5e,
	0xba, 0xb9, 0x66, 0x83, 0xd1, 0x0b, 0x9d, 0x90, 0x0c, 0x46, 0x6e, 0x7e, 0x54, 0x6c, 0x4a, 0x75,
	0xcf, 0x4a, 0x1a, 0x6a, 0x9b, 0x82, 0x1b, 0xe8, 0xa6, 0xd8, 0xca, 0x95, 0xe0, 0xc4, 0xd9, 0xbe,
	0xd8, 0xf7, 0x67, 0x16, 0x51, 0x4e, 0x1a, 0x37, 0x2e, 0xb5, 0xf9, 0x14, 0x7e, 0x73, 0x83, 0xed,
	0x34, 0xfa, 0xfc, 0x38, 0x25, 0xcc, 0xa7, 0x9b, 0x27, 0x31, 0x15, 0x24, 0x12, 0x94, 0x6d, 0xb2,
	0xaa, 0x79, 0x31, 0xe6, 0xa5, 0xb6, 0x6e, 0xcb, 0x3f, 0xd1, 0xab, 0x1f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x14, 0x23, 0x0d, 0xff, 0x55, 0x07, 0x00, 0x00,
}
