// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/pas/pasapi/grpcapi.proto

package pasapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AlarmStatus int32

const (
	AlarmStatus_NOT_CONFIGURED AlarmStatus = 0
	AlarmStatus_NO_DATA        AlarmStatus = 1
	AlarmStatus_GOOD           AlarmStatus = 2
	AlarmStatus_ALERT          AlarmStatus = 3
	AlarmStatus_DANGER         AlarmStatus = 4
)

var AlarmStatus_name = map[int32]string{
	0: "NOT_CONFIGURED",
	1: "NO_DATA",
	2: "GOOD",
	3: "ALERT",
	4: "DANGER",
}
var AlarmStatus_value = map[string]int32{
	"NOT_CONFIGURED": 0,
	"NO_DATA":        1,
	"GOOD":           2,
	"ALERT":          3,
	"DANGER":         4,
}

func (x AlarmStatus) String() string {
	return proto.EnumName(AlarmStatus_name, int32(x))
}
func (AlarmStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_ba0af4031c0d6da8, []int{0}
}

// https://en.wikipedia.org/wiki/Interval_(mathematics)#Classification_of_intervals
type IntervalType int32

const (
	IntervalType_BOUNDED_OPEN                              IntervalType = 0
	IntervalType_BOUNDED_CLOSED                            IntervalType = 1
	IntervalType_BOUNDED_LEFT_OPEN_RIGHT_CLOSED            IntervalType = 2
	IntervalType_BOUNDED_LEFT_CLOSED_RIGHT_OPEN            IntervalType = 3
	IntervalType_LEFT_UNBOUNDED_RIGHT_BOUNDED_RIGHT_OPEN   IntervalType = 4
	IntervalType_LEFT_UNBOUNDED_RIGHT_BOUNDED_RIGHT_CLOSED IntervalType = 5
	IntervalType_LEFT_BOUNDED_RIGHT_UNBOUNDED_LEFT_OPEN    IntervalType = 6
	IntervalType_LEFT_BOUNDED_RIGHT_UNBOUNDED_LEFT_CLOSED  IntervalType = 7
)

var IntervalType_name = map[int32]string{
	0: "BOUNDED_OPEN",
	1: "BOUNDED_CLOSED",
	2: "BOUNDED_LEFT_OPEN_RIGHT_CLOSED",
	3: "BOUNDED_LEFT_CLOSED_RIGHT_OPEN",
	4: "LEFT_UNBOUNDED_RIGHT_BOUNDED_RIGHT_OPEN",
	5: "LEFT_UNBOUNDED_RIGHT_BOUNDED_RIGHT_CLOSED",
	6: "LEFT_BOUNDED_RIGHT_UNBOUNDED_LEFT_OPEN",
	7: "LEFT_BOUNDED_RIGHT_UNBOUNDED_LEFT_CLOSED",
}
var IntervalType_value = map[string]int32{
	"BOUNDED_OPEN":                              0,
	"BOUNDED_CLOSED":                            1,
	"BOUNDED_LEFT_OPEN_RIGHT_CLOSED":            2,
	"BOUNDED_LEFT_CLOSED_RIGHT_OPEN":            3,
	"LEFT_UNBOUNDED_RIGHT_BOUNDED_RIGHT_OPEN":   4,
	"LEFT_UNBOUNDED_RIGHT_BOUNDED_RIGHT_CLOSED": 5,
	"LEFT_BOUNDED_RIGHT_UNBOUNDED_LEFT_OPEN":    6,
	"LEFT_BOUNDED_RIGHT_UNBOUNDED_LEFT_CLOSED":  7,
}

func (x IntervalType) String() string {
	return proto.EnumName(IntervalType_name, int32(x))
}
func (IntervalType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_ba0af4031c0d6da8, []int{1}
}

// DeepPing Messages
type DeepPingOutput struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeepPingOutput) Reset()         { *m = DeepPingOutput{} }
func (m *DeepPingOutput) String() string { return proto.CompactTextString(m) }
func (*DeepPingOutput) ProtoMessage()    {}
func (*DeepPingOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_ba0af4031c0d6da8, []int{0}
}
func (m *DeepPingOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeepPingOutput.Unmarshal(m, b)
}
func (m *DeepPingOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeepPingOutput.Marshal(b, m, deterministic)
}
func (dst *DeepPingOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeepPingOutput.Merge(dst, src)
}
func (m *DeepPingOutput) XXX_Size() int {
	return xxx_messageInfo_DeepPingOutput.Size(m)
}
func (m *DeepPingOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_DeepPingOutput.DiscardUnknown(m)
}

var xxx_messageInfo_DeepPingOutput proto.InternalMessageInfo

func (m *DeepPingOutput) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// SetPointThreshold Messages
type SetPointThresholdInput struct {
	NodeId               string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	UserId               string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Intervals            []*AlarmStatusInterval `protobuf:"bytes,3,rep,name=intervals,proto3" json:"intervals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SetPointThresholdInput) Reset()         { *m = SetPointThresholdInput{} }
func (m *SetPointThresholdInput) String() string { return proto.CompactTextString(m) }
func (*SetPointThresholdInput) ProtoMessage()    {}
func (*SetPointThresholdInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_ba0af4031c0d6da8, []int{1}
}
func (m *SetPointThresholdInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPointThresholdInput.Unmarshal(m, b)
}
func (m *SetPointThresholdInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPointThresholdInput.Marshal(b, m, deterministic)
}
func (dst *SetPointThresholdInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPointThresholdInput.Merge(dst, src)
}
func (m *SetPointThresholdInput) XXX_Size() int {
	return xxx_messageInfo_SetPointThresholdInput.Size(m)
}
func (m *SetPointThresholdInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPointThresholdInput.DiscardUnknown(m)
}

var xxx_messageInfo_SetPointThresholdInput proto.InternalMessageInfo

func (m *SetPointThresholdInput) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *SetPointThresholdInput) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SetPointThresholdInput) GetIntervals() []*AlarmStatusInterval {
	if m != nil {
		return m.Intervals
	}
	return nil
}

type SetPointThresholdOutput struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPointThresholdOutput) Reset()         { *m = SetPointThresholdOutput{} }
func (m *SetPointThresholdOutput) String() string { return proto.CompactTextString(m) }
func (*SetPointThresholdOutput) ProtoMessage()    {}
func (*SetPointThresholdOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_ba0af4031c0d6da8, []int{2}
}
func (m *SetPointThresholdOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPointThresholdOutput.Unmarshal(m, b)
}
func (m *SetPointThresholdOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPointThresholdOutput.Marshal(b, m, deterministic)
}
func (dst *SetPointThresholdOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPointThresholdOutput.Merge(dst, src)
}
func (m *SetPointThresholdOutput) XXX_Size() int {
	return xxx_messageInfo_SetPointThresholdOutput.Size(m)
}
func (m *SetPointThresholdOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPointThresholdOutput.DiscardUnknown(m)
}

var xxx_messageInfo_SetPointThresholdOutput proto.InternalMessageInfo

// GetPointThreshold Messages
type GetPointThresholdInput struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPointThresholdInput) Reset()         { *m = GetPointThresholdInput{} }
func (m *GetPointThresholdInput) String() string { return proto.CompactTextString(m) }
func (*GetPointThresholdInput) ProtoMessage()    {}
func (*GetPointThresholdInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_ba0af4031c0d6da8, []int{3}
}
func (m *GetPointThresholdInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPointThresholdInput.Unmarshal(m, b)
}
func (m *GetPointThresholdInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPointThresholdInput.Marshal(b, m, deterministic)
}
func (dst *GetPointThresholdInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPointThresholdInput.Merge(dst, src)
}
func (m *GetPointThresholdInput) XXX_Size() int {
	return xxx_messageInfo_GetPointThresholdInput.Size(m)
}
func (m *GetPointThresholdInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPointThresholdInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetPointThresholdInput proto.InternalMessageInfo

func (m *GetPointThresholdInput) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

type GetPointThresholdOutput struct {
	Intervals            *AlarmStatusIntervals `protobuf:"bytes,1,opt,name=intervals,proto3" json:"intervals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetPointThresholdOutput) Reset()         { *m = GetPointThresholdOutput{} }
func (m *GetPointThresholdOutput) String() string { return proto.CompactTextString(m) }
func (*GetPointThresholdOutput) ProtoMessage()    {}
func (*GetPointThresholdOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_ba0af4031c0d6da8, []int{4}
}
func (m *GetPointThresholdOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPointThresholdOutput.Unmarshal(m, b)
}
func (m *GetPointThresholdOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPointThresholdOutput.Marshal(b, m, deterministic)
}
func (dst *GetPointThresholdOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPointThresholdOutput.Merge(dst, src)
}
func (m *GetPointThresholdOutput) XXX_Size() int {
	return xxx_messageInfo_GetPointThresholdOutput.Size(m)
}
func (m *GetPointThresholdOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPointThresholdOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetPointThresholdOutput proto.InternalMessageInfo

func (m *GetPointThresholdOutput) GetIntervals() *AlarmStatusIntervals {
	if m != nil {
		return m.Intervals
	}
	return nil
}

// SetPointStatus Messages
type SetPointStatusInput struct {
	NodeId               string      `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AlarmStatus          AlarmStatus `protobuf:"varint,2,opt,name=alarm_status,json=alarmStatus,proto3,enum=pasapi.AlarmStatus" json:"alarm_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SetPointStatusInput) Reset()         { *m = SetPointStatusInput{} }
func (m *SetPointStatusInput) String() string { return proto.CompactTextString(m) }
func (*SetPointStatusInput) ProtoMessage()    {}
func (*SetPointStatusInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_ba0af4031c0d6da8, []int{5}
}
func (m *SetPointStatusInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPointStatusInput.Unmarshal(m, b)
}
func (m *SetPointStatusInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPointStatusInput.Marshal(b, m, deterministic)
}
func (dst *SetPointStatusInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPointStatusInput.Merge(dst, src)
}
func (m *SetPointStatusInput) XXX_Size() int {
	return xxx_messageInfo_SetPointStatusInput.Size(m)
}
func (m *SetPointStatusInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPointStatusInput.DiscardUnknown(m)
}

var xxx_messageInfo_SetPointStatusInput proto.InternalMessageInfo

func (m *SetPointStatusInput) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *SetPointStatusInput) GetAlarmStatus() AlarmStatus {
	if m != nil {
		return m.AlarmStatus
	}
	return AlarmStatus_NOT_CONFIGURED
}

type SetPointStatusOutput struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPointStatusOutput) Reset()         { *m = SetPointStatusOutput{} }
func (m *SetPointStatusOutput) String() string { return proto.CompactTextString(m) }
func (*SetPointStatusOutput) ProtoMessage()    {}
func (*SetPointStatusOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_ba0af4031c0d6da8, []int{6}
}
func (m *SetPointStatusOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPointStatusOutput.Unmarshal(m, b)
}
func (m *SetPointStatusOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPointStatusOutput.Marshal(b, m, deterministic)
}
func (dst *SetPointStatusOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPointStatusOutput.Merge(dst, src)
}
func (m *SetPointStatusOutput) XXX_Size() int {
	return xxx_messageInfo_SetPointStatusOutput.Size(m)
}
func (m *SetPointStatusOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPointStatusOutput.DiscardUnknown(m)
}

var xxx_messageInfo_SetPointStatusOutput proto.InternalMessageInfo

// GetPointStatus Messages
type GetPointStatusInput struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPointStatusInput) Reset()         { *m = GetPointStatusInput{} }
func (m *GetPointStatusInput) String() string { return proto.CompactTextString(m) }
func (*GetPointStatusInput) ProtoMessage()    {}
func (*GetPointStatusInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_ba0af4031c0d6da8, []int{7}
}
func (m *GetPointStatusInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPointStatusInput.Unmarshal(m, b)
}
func (m *GetPointStatusInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPointStatusInput.Marshal(b, m, deterministic)
}
func (dst *GetPointStatusInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPointStatusInput.Merge(dst, src)
}
func (m *GetPointStatusInput) XXX_Size() int {
	return xxx_messageInfo_GetPointStatusInput.Size(m)
}
func (m *GetPointStatusInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPointStatusInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetPointStatusInput proto.InternalMessageInfo

func (m *GetPointStatusInput) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

type GetPointStatusOutput struct {
	AlarmStatus          AlarmStatus `protobuf:"varint,1,opt,name=alarm_status,json=alarmStatus,proto3,enum=pasapi.AlarmStatus" json:"alarm_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetPointStatusOutput) Reset()         { *m = GetPointStatusOutput{} }
func (m *GetPointStatusOutput) String() string { return proto.CompactTextString(m) }
func (*GetPointStatusOutput) ProtoMessage()    {}
func (*GetPointStatusOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_ba0af4031c0d6da8, []int{8}
}
func (m *GetPointStatusOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPointStatusOutput.Unmarshal(m, b)
}
func (m *GetPointStatusOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPointStatusOutput.Marshal(b, m, deterministic)
}
func (dst *GetPointStatusOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPointStatusOutput.Merge(dst, src)
}
func (m *GetPointStatusOutput) XXX_Size() int {
	return xxx_messageInfo_GetPointStatusOutput.Size(m)
}
func (m *GetPointStatusOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPointStatusOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetPointStatusOutput proto.InternalMessageInfo

func (m *GetPointStatusOutput) GetAlarmStatus() AlarmStatus {
	if m != nil {
		return m.AlarmStatus
	}
	return AlarmStatus_NOT_CONFIGURED
}

// GetPointStatusStream Messages
type GetPointStatusStreamInput struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPointStatusStreamInput) Reset()         { *m = GetPointStatusStreamInput{} }
func (m *GetPointStatusStreamInput) String() string { return proto.CompactTextString(m) }
func (*GetPointStatusStreamInput) ProtoMessage()    {}
func (*GetPointStatusStreamInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_ba0af4031c0d6da8, []int{9}
}
func (m *GetPointStatusStreamInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPointStatusStreamInput.Unmarshal(m, b)
}
func (m *GetPointStatusStreamInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPointStatusStreamInput.Marshal(b, m, deterministic)
}
func (dst *GetPointStatusStreamInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPointStatusStreamInput.Merge(dst, src)
}
func (m *GetPointStatusStreamInput) XXX_Size() int {
	return xxx_messageInfo_GetPointStatusStreamInput.Size(m)
}
func (m *GetPointStatusStreamInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPointStatusStreamInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetPointStatusStreamInput proto.InternalMessageInfo

type GetPointStatusStreamOutput struct {
	NodeId               string      `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AlarmStatus          AlarmStatus `protobuf:"varint,2,opt,name=alarm_status,json=alarmStatus,proto3,enum=pasapi.AlarmStatus" json:"alarm_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetPointStatusStreamOutput) Reset()         { *m = GetPointStatusStreamOutput{} }
func (m *GetPointStatusStreamOutput) String() string { return proto.CompactTextString(m) }
func (*GetPointStatusStreamOutput) ProtoMessage()    {}
func (*GetPointStatusStreamOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_ba0af4031c0d6da8, []int{10}
}
func (m *GetPointStatusStreamOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPointStatusStreamOutput.Unmarshal(m, b)
}
func (m *GetPointStatusStreamOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPointStatusStreamOutput.Marshal(b, m, deterministic)
}
func (dst *GetPointStatusStreamOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPointStatusStreamOutput.Merge(dst, src)
}
func (m *GetPointStatusStreamOutput) XXX_Size() int {
	return xxx_messageInfo_GetPointStatusStreamOutput.Size(m)
}
func (m *GetPointStatusStreamOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPointStatusStreamOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetPointStatusStreamOutput proto.InternalMessageInfo

func (m *GetPointStatusStreamOutput) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *GetPointStatusStreamOutput) GetAlarmStatus() AlarmStatus {
	if m != nil {
		return m.AlarmStatus
	}
	return AlarmStatus_NOT_CONFIGURED
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_ba0af4031c0d6da8, []int{11}
}
func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (dst *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(dst, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

type AlarmStatusInterval struct {
	LeftBound            float64      `protobuf:"fixed64,1,opt,name=left_bound,json=leftBound,proto3" json:"left_bound,omitempty"`
	RightBound           float64      `protobuf:"fixed64,2,opt,name=right_bound,json=rightBound,proto3" json:"right_bound,omitempty"`
	Type                 IntervalType `protobuf:"varint,3,opt,name=type,proto3,enum=pasapi.IntervalType" json:"type,omitempty"`
	AlarmStatus          AlarmStatus  `protobuf:"varint,4,opt,name=alarm_status,json=alarmStatus,proto3,enum=pasapi.AlarmStatus" json:"alarm_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AlarmStatusInterval) Reset()         { *m = AlarmStatusInterval{} }
func (m *AlarmStatusInterval) String() string { return proto.CompactTextString(m) }
func (*AlarmStatusInterval) ProtoMessage()    {}
func (*AlarmStatusInterval) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_ba0af4031c0d6da8, []int{12}
}
func (m *AlarmStatusInterval) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlarmStatusInterval.Unmarshal(m, b)
}
func (m *AlarmStatusInterval) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlarmStatusInterval.Marshal(b, m, deterministic)
}
func (dst *AlarmStatusInterval) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlarmStatusInterval.Merge(dst, src)
}
func (m *AlarmStatusInterval) XXX_Size() int {
	return xxx_messageInfo_AlarmStatusInterval.Size(m)
}
func (m *AlarmStatusInterval) XXX_DiscardUnknown() {
	xxx_messageInfo_AlarmStatusInterval.DiscardUnknown(m)
}

var xxx_messageInfo_AlarmStatusInterval proto.InternalMessageInfo

func (m *AlarmStatusInterval) GetLeftBound() float64 {
	if m != nil {
		return m.LeftBound
	}
	return 0
}

func (m *AlarmStatusInterval) GetRightBound() float64 {
	if m != nil {
		return m.RightBound
	}
	return 0
}

func (m *AlarmStatusInterval) GetType() IntervalType {
	if m != nil {
		return m.Type
	}
	return IntervalType_BOUNDED_OPEN
}

func (m *AlarmStatusInterval) GetAlarmStatus() AlarmStatus {
	if m != nil {
		return m.AlarmStatus
	}
	return AlarmStatus_NOT_CONFIGURED
}

type AlarmStatusIntervals struct {
	List                 []*AlarmStatusInterval `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *AlarmStatusIntervals) Reset()         { *m = AlarmStatusIntervals{} }
func (m *AlarmStatusIntervals) String() string { return proto.CompactTextString(m) }
func (*AlarmStatusIntervals) ProtoMessage()    {}
func (*AlarmStatusIntervals) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_ba0af4031c0d6da8, []int{13}
}
func (m *AlarmStatusIntervals) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlarmStatusIntervals.Unmarshal(m, b)
}
func (m *AlarmStatusIntervals) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlarmStatusIntervals.Marshal(b, m, deterministic)
}
func (dst *AlarmStatusIntervals) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlarmStatusIntervals.Merge(dst, src)
}
func (m *AlarmStatusIntervals) XXX_Size() int {
	return xxx_messageInfo_AlarmStatusIntervals.Size(m)
}
func (m *AlarmStatusIntervals) XXX_DiscardUnknown() {
	xxx_messageInfo_AlarmStatusIntervals.DiscardUnknown(m)
}

var xxx_messageInfo_AlarmStatusIntervals proto.InternalMessageInfo

func (m *AlarmStatusIntervals) GetList() []*AlarmStatusInterval {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*DeepPingOutput)(nil), "pasapi.DeepPingOutput")
	proto.RegisterType((*SetPointThresholdInput)(nil), "pasapi.SetPointThresholdInput")
	proto.RegisterType((*SetPointThresholdOutput)(nil), "pasapi.SetPointThresholdOutput")
	proto.RegisterType((*GetPointThresholdInput)(nil), "pasapi.GetPointThresholdInput")
	proto.RegisterType((*GetPointThresholdOutput)(nil), "pasapi.GetPointThresholdOutput")
	proto.RegisterType((*SetPointStatusInput)(nil), "pasapi.SetPointStatusInput")
	proto.RegisterType((*SetPointStatusOutput)(nil), "pasapi.SetPointStatusOutput")
	proto.RegisterType((*GetPointStatusInput)(nil), "pasapi.GetPointStatusInput")
	proto.RegisterType((*GetPointStatusOutput)(nil), "pasapi.GetPointStatusOutput")
	proto.RegisterType((*GetPointStatusStreamInput)(nil), "pasapi.GetPointStatusStreamInput")
	proto.RegisterType((*GetPointStatusStreamOutput)(nil), "pasapi.GetPointStatusStreamOutput")
	proto.RegisterType((*Void)(nil), "pasapi.Void")
	proto.RegisterType((*AlarmStatusInterval)(nil), "pasapi.AlarmStatusInterval")
	proto.RegisterType((*AlarmStatusIntervals)(nil), "pasapi.AlarmStatusIntervals")
	proto.RegisterEnum("pasapi.AlarmStatus", AlarmStatus_name, AlarmStatus_value)
	proto.RegisterEnum("pasapi.IntervalType", IntervalType_name, IntervalType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PointAlarmStatusClient is the client API for PointAlarmStatus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PointAlarmStatusClient interface {
	DeepPing(ctx context.Context, in *Void, opts ...grpc.CallOption) (*DeepPingOutput, error)
	SetPointThreshold(ctx context.Context, in *SetPointThresholdInput, opts ...grpc.CallOption) (*SetPointThresholdOutput, error)
	GetPointThreshold(ctx context.Context, in *GetPointThresholdInput, opts ...grpc.CallOption) (*GetPointThresholdOutput, error)
	SetPointStatus(ctx context.Context, in *SetPointStatusInput, opts ...grpc.CallOption) (*SetPointStatusOutput, error)
	GetPointStatus(ctx context.Context, in *GetPointStatusInput, opts ...grpc.CallOption) (*GetPointStatusOutput, error)
	GetPointStatusStream(ctx context.Context, in *GetPointStatusStreamInput, opts ...grpc.CallOption) (PointAlarmStatus_GetPointStatusStreamClient, error)
}

type pointAlarmStatusClient struct {
	cc *grpc.ClientConn
}

func NewPointAlarmStatusClient(cc *grpc.ClientConn) PointAlarmStatusClient {
	return &pointAlarmStatusClient{cc}
}

func (c *pointAlarmStatusClient) DeepPing(ctx context.Context, in *Void, opts ...grpc.CallOption) (*DeepPingOutput, error) {
	out := new(DeepPingOutput)
	err := c.cc.Invoke(ctx, "/pasapi.PointAlarmStatus/DeepPing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointAlarmStatusClient) SetPointThreshold(ctx context.Context, in *SetPointThresholdInput, opts ...grpc.CallOption) (*SetPointThresholdOutput, error) {
	out := new(SetPointThresholdOutput)
	err := c.cc.Invoke(ctx, "/pasapi.PointAlarmStatus/SetPointThreshold", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointAlarmStatusClient) GetPointThreshold(ctx context.Context, in *GetPointThresholdInput, opts ...grpc.CallOption) (*GetPointThresholdOutput, error) {
	out := new(GetPointThresholdOutput)
	err := c.cc.Invoke(ctx, "/pasapi.PointAlarmStatus/GetPointThreshold", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointAlarmStatusClient) SetPointStatus(ctx context.Context, in *SetPointStatusInput, opts ...grpc.CallOption) (*SetPointStatusOutput, error) {
	out := new(SetPointStatusOutput)
	err := c.cc.Invoke(ctx, "/pasapi.PointAlarmStatus/SetPointStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointAlarmStatusClient) GetPointStatus(ctx context.Context, in *GetPointStatusInput, opts ...grpc.CallOption) (*GetPointStatusOutput, error) {
	out := new(GetPointStatusOutput)
	err := c.cc.Invoke(ctx, "/pasapi.PointAlarmStatus/GetPointStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointAlarmStatusClient) GetPointStatusStream(ctx context.Context, in *GetPointStatusStreamInput, opts ...grpc.CallOption) (PointAlarmStatus_GetPointStatusStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PointAlarmStatus_serviceDesc.Streams[0], "/pasapi.PointAlarmStatus/GetPointStatusStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &pointAlarmStatusGetPointStatusStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PointAlarmStatus_GetPointStatusStreamClient interface {
	Recv() (*GetPointStatusStreamOutput, error)
	grpc.ClientStream
}

type pointAlarmStatusGetPointStatusStreamClient struct {
	grpc.ClientStream
}

func (x *pointAlarmStatusGetPointStatusStreamClient) Recv() (*GetPointStatusStreamOutput, error) {
	m := new(GetPointStatusStreamOutput)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PointAlarmStatusServer is the server API for PointAlarmStatus service.
type PointAlarmStatusServer interface {
	DeepPing(context.Context, *Void) (*DeepPingOutput, error)
	SetPointThreshold(context.Context, *SetPointThresholdInput) (*SetPointThresholdOutput, error)
	GetPointThreshold(context.Context, *GetPointThresholdInput) (*GetPointThresholdOutput, error)
	SetPointStatus(context.Context, *SetPointStatusInput) (*SetPointStatusOutput, error)
	GetPointStatus(context.Context, *GetPointStatusInput) (*GetPointStatusOutput, error)
	GetPointStatusStream(*GetPointStatusStreamInput, PointAlarmStatus_GetPointStatusStreamServer) error
}

func RegisterPointAlarmStatusServer(s *grpc.Server, srv PointAlarmStatusServer) {
	s.RegisterService(&_PointAlarmStatus_serviceDesc, srv)
}

func _PointAlarmStatus_DeepPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointAlarmStatusServer).DeepPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pasapi.PointAlarmStatus/DeepPing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointAlarmStatusServer).DeepPing(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _PointAlarmStatus_SetPointThreshold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPointThresholdInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointAlarmStatusServer).SetPointThreshold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pasapi.PointAlarmStatus/SetPointThreshold",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointAlarmStatusServer).SetPointThreshold(ctx, req.(*SetPointThresholdInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _PointAlarmStatus_GetPointThreshold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPointThresholdInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointAlarmStatusServer).GetPointThreshold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pasapi.PointAlarmStatus/GetPointThreshold",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointAlarmStatusServer).GetPointThreshold(ctx, req.(*GetPointThresholdInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _PointAlarmStatus_SetPointStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPointStatusInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointAlarmStatusServer).SetPointStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pasapi.PointAlarmStatus/SetPointStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointAlarmStatusServer).SetPointStatus(ctx, req.(*SetPointStatusInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _PointAlarmStatus_GetPointStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPointStatusInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointAlarmStatusServer).GetPointStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pasapi.PointAlarmStatus/GetPointStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointAlarmStatusServer).GetPointStatus(ctx, req.(*GetPointStatusInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _PointAlarmStatus_GetPointStatusStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetPointStatusStreamInput)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PointAlarmStatusServer).GetPointStatusStream(m, &pointAlarmStatusGetPointStatusStreamServer{stream})
}

type PointAlarmStatus_GetPointStatusStreamServer interface {
	Send(*GetPointStatusStreamOutput) error
	grpc.ServerStream
}

type pointAlarmStatusGetPointStatusStreamServer struct {
	grpc.ServerStream
}

func (x *pointAlarmStatusGetPointStatusStreamServer) Send(m *GetPointStatusStreamOutput) error {
	return x.ServerStream.SendMsg(m)
}

var _PointAlarmStatus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pasapi.PointAlarmStatus",
	HandlerType: (*PointAlarmStatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeepPing",
			Handler:    _PointAlarmStatus_DeepPing_Handler,
		},
		{
			MethodName: "SetPointThreshold",
			Handler:    _PointAlarmStatus_SetPointThreshold_Handler,
		},
		{
			MethodName: "GetPointThreshold",
			Handler:    _PointAlarmStatus_GetPointThreshold_Handler,
		},
		{
			MethodName: "SetPointStatus",
			Handler:    _PointAlarmStatus_SetPointStatus_Handler,
		},
		{
			MethodName: "GetPointStatus",
			Handler:    _PointAlarmStatus_GetPointStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetPointStatusStream",
			Handler:       _PointAlarmStatus_GetPointStatusStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "services/pas/pasapi/grpcapi.proto",
}

func init() {
	proto.RegisterFile("services/pas/pasapi/grpcapi.proto", fileDescriptor_grpcapi_ba0af4031c0d6da8)
}

var fileDescriptor_grpcapi_ba0af4031c0d6da8 = []byte{
	// 675 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdf, 0x4f, 0xda, 0x50,
	0x14, 0xb6, 0x50, 0x51, 0x0e, 0x84, 0x74, 0x07, 0x82, 0x88, 0xce, 0x1f, 0x7d, 0x70, 0xcc, 0x6d,
	0xb8, 0xb1, 0x64, 0xc9, 0xf6, 0x86, 0xb6, 0xde, 0x91, 0xb8, 0xd6, 0x94, 0xe2, 0x6b, 0x53, 0xe5,
	0xaa, 0x4d, 0x90, 0x36, 0x6d, 0x31, 0xf1, 0x0f, 0xd8, 0x3f, 0xb4, 0x97, 0xfd, 0x69, 0x7b, 0x5d,
	0x7a, 0xdb, 0x3b, 0x8b, 0x14, 0xc4, 0x64, 0x0f, 0x3c, 0x9c, 0xf3, 0x7d, 0xf7, 0x3b, 0xdf, 0xfd,
	0xc1, 0x57, 0xd8, 0x0f, 0xa8, 0x7f, 0xef, 0x5c, 0xd1, 0xe0, 0xc8, 0xb3, 0xd9, 0xcf, 0xf6, 0x9c,
	0xa3, 0x1b, 0xdf, 0xbb, 0xb2, 0x3d, 0xa7, 0xed, 0xf9, 0x6e, 0xe8, 0x62, 0x21, 0xee, 0xca, 0x07,
	0x50, 0x51, 0x28, 0xf5, 0xce, 0x9d, 0xf1, 0x8d, 0x3e, 0x09, 0xbd, 0x49, 0x88, 0x35, 0x58, 0xbd,
	0xb7, 0x47, 0x13, 0xda, 0x10, 0xf6, 0x84, 0x56, 0xd1, 0x88, 0x0b, 0xf9, 0xa7, 0x00, 0xf5, 0x3e,
	0x0d, 0xcf, 0x5d, 0x67, 0x1c, 0x9a, 0xb7, 0x3e, 0x0d, 0x6e, 0xdd, 0xd1, 0xb0, 0x37, 0x8e, 0x16,
	0x6c, 0xc0, 0xda, 0xd8, 0x1d, 0x52, 0xcb, 0x19, 0x26, 0x4b, 0x0a, 0x51, 0xd9, 0x1b, 0x46, 0xc0,
	0x24, 0xa0, 0x7e, 0x04, 0xe4, 0x62, 0x20, 0x2a, 0x7b, 0x43, 0xfc, 0x0a, 0x45, 0x67, 0x1c, 0x52,
	0xff, 0xde, 0x1e, 0x05, 0x8d, 0xfc, 0x5e, 0xbe, 0x55, 0xea, 0x6c, 0xb5, 0x63, 0x43, 0xed, 0xee,
	0xc8, 0xf6, 0xef, 0xfa, 0xa1, 0x1d, 0x4e, 0x82, 0x5e, 0xc2, 0x31, 0x1e, 0xd9, 0xf2, 0x26, 0x6c,
	0xcc, 0xd8, 0x88, 0x8d, 0xcb, 0x9f, 0xa0, 0x4e, 0x5e, 0xe6, 0x50, 0x1e, 0xc0, 0x06, 0xc9, 0x56,
	0xc3, 0x6f, 0x69, 0x8f, 0xd1, 0xaa, 0x52, 0x67, 0x7b, 0x81, 0xc7, 0x20, 0x6d, 0xf2, 0x1a, 0xaa,
	0xdc, 0x24, 0x67, 0x2d, 0x3c, 0xa8, 0x2f, 0x50, 0xb6, 0x23, 0x49, 0x2b, 0x60, 0x6c, 0x76, 0x5a,
	0x95, 0x4e, 0x35, 0x63, 0x9c, 0x51, 0xb2, 0x1f, 0x0b, 0xb9, 0x0e, 0xb5, 0xe9, 0x39, 0xc9, 0x49,
	0xb4, 0xa1, 0x4a, 0x5e, 0x30, 0x5f, 0xd6, 0xa0, 0x46, 0x32, 0x74, 0x66, 0x7c, 0x09, 0x4b, 0xfa,
	0xda, 0x82, 0xcd, 0x69, 0xbd, 0x7e, 0xe8, 0x53, 0xfb, 0x8e, 0xb9, 0x90, 0xef, 0xa0, 0x99, 0x05,
	0x26, 0x23, 0xff, 0xfb, 0x19, 0x15, 0x40, 0xbc, 0x70, 0x9d, 0xa1, 0xfc, 0x5b, 0x80, 0x6a, 0xc6,
	0xbd, 0xe1, 0x6b, 0x80, 0x11, 0xbd, 0x0e, 0xad, 0x4b, 0x77, 0x32, 0x8e, 0x67, 0x0a, 0x46, 0x31,
	0xea, 0x1c, 0x47, 0x0d, 0xdc, 0x85, 0x92, 0xef, 0xdc, 0xdc, 0x72, 0x3c, 0xc7, 0x70, 0x60, 0xad,
	0x98, 0xd0, 0x02, 0x31, 0x7c, 0xf0, 0x68, 0x23, 0xcf, 0xfc, 0xd4, 0xb8, 0x1f, 0xae, 0x6f, 0x3e,
	0x78, 0xd4, 0x60, 0x8c, 0x99, 0x1d, 0x88, 0x4b, 0xee, 0x80, 0x40, 0x2d, 0xeb, 0xc1, 0xe1, 0x11,
	0x88, 0x23, 0x27, 0x08, 0x1b, 0xc2, 0xf3, 0x7f, 0x20, 0x46, 0x3c, 0xd4, 0xa1, 0x94, 0x02, 0x11,
	0xa1, 0xa2, 0xe9, 0xa6, 0x75, 0xa2, 0x6b, 0xa7, 0x3d, 0x32, 0x30, 0x54, 0x45, 0x5a, 0xc1, 0x12,
	0xac, 0x69, 0xba, 0xa5, 0x74, 0xcd, 0xae, 0x24, 0xe0, 0x3a, 0x88, 0x44, 0xd7, 0x15, 0x29, 0x87,
	0x45, 0x58, 0xed, 0x9e, 0xa9, 0x86, 0x29, 0xe5, 0x11, 0xa0, 0xa0, 0x74, 0x35, 0xa2, 0x1a, 0x92,
	0x78, 0xf8, 0x2b, 0x07, 0xe5, 0xf4, 0x46, 0x51, 0x82, 0xf2, 0xb1, 0x3e, 0xd0, 0x14, 0x55, 0xb1,
	0xf4, 0x73, 0x55, 0x93, 0x56, 0xa2, 0x21, 0xbc, 0x73, 0x72, 0xa6, 0xf7, 0x55, 0x45, 0x12, 0x50,
	0x86, 0x1d, 0xde, 0x3b, 0x53, 0x4f, 0x4d, 0x46, 0xb5, 0x8c, 0x1e, 0xf9, 0x6e, 0x72, 0x4e, 0x6e,
	0x86, 0x13, 0x03, 0x09, 0x8b, 0x69, 0xe7, 0xf1, 0x1d, 0xbc, 0x61, 0xd8, 0x40, 0xe3, 0xd4, 0x18,
	0x9e, 0xae, 0x18, 0x59, 0xc4, 0x0f, 0xf0, 0x76, 0x09, 0x72, 0x32, 0x7f, 0x15, 0x0f, 0xe1, 0x80,
	0xd1, 0xa7, 0xe1, 0xc7, 0xc5, 0xff, 0x8c, 0x4b, 0x05, 0x7c, 0x0f, 0xad, 0xe7, 0xb9, 0x89, 0xf2,
	0x5a, 0xe7, 0x4f, 0x1e, 0x24, 0xf6, 0xfa, 0xd3, 0x77, 0xd1, 0x81, 0x75, 0x1e, 0xc3, 0x58, 0xe6,
	0x37, 0x19, 0xbd, 0xdb, 0x66, 0x9d, 0x57, 0xd3, 0x31, 0x2d, 0xaf, 0xe0, 0x05, 0xbc, 0x9a, 0x89,
	0x42, 0xdc, 0xe1, 0xf4, 0xec, 0xb0, 0x6e, 0xee, 0xce, 0xc5, 0xd3, 0xba, 0x64, 0xbe, 0x2e, 0x79,
	0x46, 0x97, 0xcc, 0xd5, 0xfd, 0x01, 0x95, 0xe9, 0xb4, 0xc2, 0xad, 0xa7, 0x66, 0x52, 0x69, 0xd5,
	0xdc, 0xce, 0x06, 0xd3, 0x72, 0x64, 0x8e, 0x1c, 0x59, 0x24, 0x47, 0xb2, 0xe5, 0xec, 0xa7, 0x19,
	0x18, 0xc7, 0x12, 0xee, 0x67, 0xaf, 0x4b, 0x25, 0x5a, 0x53, 0x5e, 0x44, 0xe1, 0x03, 0x3e, 0x0a,
	0x97, 0x05, 0xf6, 0xe9, 0xfd, 0xfc, 0x37, 0x00, 0x00, 0xff, 0xff, 0xff, 0xe2, 0xc2, 0x38, 0x9f,
	0x07, 0x00, 0x00,
}
