// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpcapi.proto

package iotgrpcapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TaskStatus int32

const (
	TaskStatus_NOT_SENT  TaskStatus = 0
	TaskStatus_SENT      TaskStatus = 1
	TaskStatus_RECEIVED  TaskStatus = 2
	TaskStatus_COMPLETED TaskStatus = 3
)

var TaskStatus_name = map[int32]string{
	0: "NOT_SENT",
	1: "SENT",
	2: "RECEIVED",
	3: "COMPLETED",
}
var TaskStatus_value = map[string]int32{
	"NOT_SENT":  0,
	"SENT":      1,
	"RECEIVED":  2,
	"COMPLETED": 3,
}

func (x TaskStatus) String() string {
	return proto.EnumName(TaskStatus_name, int32(x))
}
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_240fc39444bbded4, []int{0}
}

type NodeDataContentType int32

const (
	NodeDataContentType_DEFAULT          NodeDataContentType = 0
	NodeDataContentType_DATA_POINT       NodeDataContentType = 1
	NodeDataContentType_SPECTRUM         NodeDataContentType = 2
	NodeDataContentType_TIME_SERIES      NodeDataContentType = 3
	NodeDataContentType_NOTE             NodeDataContentType = 4
	NodeDataContentType_MEDIA            NodeDataContentType = 5
	NodeDataContentType_QUESTION_ANSWERS NodeDataContentType = 6
)

var NodeDataContentType_name = map[int32]string{
	0: "DEFAULT",
	1: "DATA_POINT",
	2: "SPECTRUM",
	3: "TIME_SERIES",
	4: "NOTE",
	5: "MEDIA",
	6: "QUESTION_ANSWERS",
}
var NodeDataContentType_value = map[string]int32{
	"DEFAULT":          0,
	"DATA_POINT":       1,
	"SPECTRUM":         2,
	"TIME_SERIES":      3,
	"NOTE":             4,
	"MEDIA":            5,
	"QUESTION_ANSWERS": 6,
}

func (x NodeDataContentType) String() string {
	return proto.EnumName(NodeDataContentType_name, int32(x))
}
func (NodeDataContentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_240fc39444bbded4, []int{1}
}

type TaskDescription struct {
	UserId                string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TaskId                string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskName              string                 `protobuf:"bytes,3,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	HierarchyId           string                 `protobuf:"bytes,4,opt,name=hierarchy_id,json=hierarchyId,proto3" json:"hierarchy_id,omitempty"`
	DueDateTimestamp      int64                  `protobuf:"varint,5,opt,name=due_date_timestamp,json=dueDateTimestamp,proto3" json:"due_date_timestamp,omitempty"`
	IsCompleted           bool                   `protobuf:"varint,6,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`
	FunctionalLocationIds *FunctionalLocationIds `protobuf:"bytes,7,opt,name=functional_location_ids,json=functionalLocationIds,proto3" json:"functional_location_ids,omitempty"`
	Status                TaskStatus             `protobuf:"varint,8,opt,name=status,proto3,enum=iotgrpcapi.TaskStatus" json:"status,omitempty"`
	ExternalTaskId        string                 `protobuf:"bytes,9,opt,name=external_task_id,json=externalTaskId,proto3" json:"external_task_id,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *TaskDescription) Reset()         { *m = TaskDescription{} }
func (m *TaskDescription) String() string { return proto.CompactTextString(m) }
func (*TaskDescription) ProtoMessage()    {}
func (*TaskDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_240fc39444bbded4, []int{0}
}
func (m *TaskDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskDescription.Unmarshal(m, b)
}
func (m *TaskDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskDescription.Marshal(b, m, deterministic)
}
func (dst *TaskDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskDescription.Merge(dst, src)
}
func (m *TaskDescription) XXX_Size() int {
	return xxx_messageInfo_TaskDescription.Size(m)
}
func (m *TaskDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskDescription.DiscardUnknown(m)
}

var xxx_messageInfo_TaskDescription proto.InternalMessageInfo

func (m *TaskDescription) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TaskDescription) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *TaskDescription) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

func (m *TaskDescription) GetHierarchyId() string {
	if m != nil {
		return m.HierarchyId
	}
	return ""
}

func (m *TaskDescription) GetDueDateTimestamp() int64 {
	if m != nil {
		return m.DueDateTimestamp
	}
	return 0
}

func (m *TaskDescription) GetIsCompleted() bool {
	if m != nil {
		return m.IsCompleted
	}
	return false
}

func (m *TaskDescription) GetFunctionalLocationIds() *FunctionalLocationIds {
	if m != nil {
		return m.FunctionalLocationIds
	}
	return nil
}

func (m *TaskDescription) GetStatus() TaskStatus {
	if m != nil {
		return m.Status
	}
	return TaskStatus_NOT_SENT
}

func (m *TaskDescription) GetExternalTaskId() string {
	if m != nil {
		return m.ExternalTaskId
	}
	return ""
}

type InitialTaskDescription struct {
	UserId                string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TaskName              string                 `protobuf:"bytes,2,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	HierarchyId           string                 `protobuf:"bytes,3,opt,name=hierarchy_id,json=hierarchyId,proto3" json:"hierarchy_id,omitempty"`
	DueDateTimestamp      int64                  `protobuf:"varint,4,opt,name=due_date_timestamp,json=dueDateTimestamp,proto3" json:"due_date_timestamp,omitempty"`
	FunctionalLocationIds *FunctionalLocationIds `protobuf:"bytes,5,opt,name=functional_location_ids,json=functionalLocationIds,proto3" json:"functional_location_ids,omitempty"`
	ExternalTaskId        string                 `protobuf:"bytes,6,opt,name=external_task_id,json=externalTaskId,proto3" json:"external_task_id,omitempty"`
	Status                TaskStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=iotgrpcapi.TaskStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *InitialTaskDescription) Reset()         { *m = InitialTaskDescription{} }
func (m *InitialTaskDescription) String() string { return proto.CompactTextString(m) }
func (*InitialTaskDescription) ProtoMessage()    {}
func (*InitialTaskDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_240fc39444bbded4, []int{1}
}
func (m *InitialTaskDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitialTaskDescription.Unmarshal(m, b)
}
func (m *InitialTaskDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitialTaskDescription.Marshal(b, m, deterministic)
}
func (dst *InitialTaskDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitialTaskDescription.Merge(dst, src)
}
func (m *InitialTaskDescription) XXX_Size() int {
	return xxx_messageInfo_InitialTaskDescription.Size(m)
}
func (m *InitialTaskDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_InitialTaskDescription.DiscardUnknown(m)
}

var xxx_messageInfo_InitialTaskDescription proto.InternalMessageInfo

func (m *InitialTaskDescription) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *InitialTaskDescription) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

func (m *InitialTaskDescription) GetHierarchyId() string {
	if m != nil {
		return m.HierarchyId
	}
	return ""
}

func (m *InitialTaskDescription) GetDueDateTimestamp() int64 {
	if m != nil {
		return m.DueDateTimestamp
	}
	return 0
}

func (m *InitialTaskDescription) GetFunctionalLocationIds() *FunctionalLocationIds {
	if m != nil {
		return m.FunctionalLocationIds
	}
	return nil
}

func (m *InitialTaskDescription) GetExternalTaskId() string {
	if m != nil {
		return m.ExternalTaskId
	}
	return ""
}

func (m *InitialTaskDescription) GetStatus() TaskStatus {
	if m != nil {
		return m.Status
	}
	return TaskStatus_NOT_SENT
}

type TaskUser struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TaskId               string   `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskUser) Reset()         { *m = TaskUser{} }
func (m *TaskUser) String() string { return proto.CompactTextString(m) }
func (*TaskUser) ProtoMessage()    {}
func (*TaskUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_240fc39444bbded4, []int{2}
}
func (m *TaskUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskUser.Unmarshal(m, b)
}
func (m *TaskUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskUser.Marshal(b, m, deterministic)
}
func (dst *TaskUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskUser.Merge(dst, src)
}
func (m *TaskUser) XXX_Size() int {
	return xxx_messageInfo_TaskUser.Size(m)
}
func (m *TaskUser) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskUser.DiscardUnknown(m)
}

var xxx_messageInfo_TaskUser proto.InternalMessageInfo

func (m *TaskUser) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TaskUser) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

type SetTaskStatusInput struct {
	TaskId               string     `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status               TaskStatus `protobuf:"varint,2,opt,name=status,proto3,enum=iotgrpcapi.TaskStatus" json:"status,omitempty"`
	UserId               string     `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SetTaskStatusInput) Reset()         { *m = SetTaskStatusInput{} }
func (m *SetTaskStatusInput) String() string { return proto.CompactTextString(m) }
func (*SetTaskStatusInput) ProtoMessage()    {}
func (*SetTaskStatusInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_240fc39444bbded4, []int{3}
}
func (m *SetTaskStatusInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTaskStatusInput.Unmarshal(m, b)
}
func (m *SetTaskStatusInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTaskStatusInput.Marshal(b, m, deterministic)
}
func (dst *SetTaskStatusInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTaskStatusInput.Merge(dst, src)
}
func (m *SetTaskStatusInput) XXX_Size() int {
	return xxx_messageInfo_SetTaskStatusInput.Size(m)
}
func (m *SetTaskStatusInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTaskStatusInput.DiscardUnknown(m)
}

var xxx_messageInfo_SetTaskStatusInput proto.InternalMessageInfo

func (m *SetTaskStatusInput) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *SetTaskStatusInput) GetStatus() TaskStatus {
	if m != nil {
		return m.Status
	}
	return TaskStatus_NOT_SENT
}

func (m *SetTaskStatusInput) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type TaskDescriptions struct {
	TaskDescriptionArr   []*TaskDescription `protobuf:"bytes,1,rep,name=task_description_arr,json=taskDescriptionArr,proto3" json:"task_description_arr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TaskDescriptions) Reset()         { *m = TaskDescriptions{} }
func (m *TaskDescriptions) String() string { return proto.CompactTextString(m) }
func (*TaskDescriptions) ProtoMessage()    {}
func (*TaskDescriptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_240fc39444bbded4, []int{4}
}
func (m *TaskDescriptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskDescriptions.Unmarshal(m, b)
}
func (m *TaskDescriptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskDescriptions.Marshal(b, m, deterministic)
}
func (dst *TaskDescriptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskDescriptions.Merge(dst, src)
}
func (m *TaskDescriptions) XXX_Size() int {
	return xxx_messageInfo_TaskDescriptions.Size(m)
}
func (m *TaskDescriptions) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskDescriptions.DiscardUnknown(m)
}

var xxx_messageInfo_TaskDescriptions proto.InternalMessageInfo

func (m *TaskDescriptions) GetTaskDescriptionArr() []*TaskDescription {
	if m != nil {
		return m.TaskDescriptionArr
	}
	return nil
}

type FunctionalLocationIds struct {
	IdArr                []string `protobuf:"bytes,1,rep,name=id_arr,json=idArr,proto3" json:"id_arr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FunctionalLocationIds) Reset()         { *m = FunctionalLocationIds{} }
func (m *FunctionalLocationIds) String() string { return proto.CompactTextString(m) }
func (*FunctionalLocationIds) ProtoMessage()    {}
func (*FunctionalLocationIds) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_240fc39444bbded4, []int{5}
}
func (m *FunctionalLocationIds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionalLocationIds.Unmarshal(m, b)
}
func (m *FunctionalLocationIds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionalLocationIds.Marshal(b, m, deterministic)
}
func (dst *FunctionalLocationIds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionalLocationIds.Merge(dst, src)
}
func (m *FunctionalLocationIds) XXX_Size() int {
	return xxx_messageInfo_FunctionalLocationIds.Size(m)
}
func (m *FunctionalLocationIds) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionalLocationIds.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionalLocationIds proto.InternalMessageInfo

func (m *FunctionalLocationIds) GetIdArr() []string {
	if m != nil {
		return m.IdArr
	}
	return nil
}

type PrimitiveString struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimitiveString) Reset()         { *m = PrimitiveString{} }
func (m *PrimitiveString) String() string { return proto.CompactTextString(m) }
func (*PrimitiveString) ProtoMessage()    {}
func (*PrimitiveString) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_240fc39444bbded4, []int{6}
}
func (m *PrimitiveString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimitiveString.Unmarshal(m, b)
}
func (m *PrimitiveString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimitiveString.Marshal(b, m, deterministic)
}
func (dst *PrimitiveString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimitiveString.Merge(dst, src)
}
func (m *PrimitiveString) XXX_Size() int {
	return xxx_messageInfo_PrimitiveString.Size(m)
}
func (m *PrimitiveString) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimitiveString.DiscardUnknown(m)
}

var xxx_messageInfo_PrimitiveString proto.InternalMessageInfo

func (m *PrimitiveString) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PrimitiveBool struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimitiveBool) Reset()         { *m = PrimitiveBool{} }
func (m *PrimitiveBool) String() string { return proto.CompactTextString(m) }
func (*PrimitiveBool) ProtoMessage()    {}
func (*PrimitiveBool) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_240fc39444bbded4, []int{7}
}
func (m *PrimitiveBool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimitiveBool.Unmarshal(m, b)
}
func (m *PrimitiveBool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimitiveBool.Marshal(b, m, deterministic)
}
func (dst *PrimitiveBool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimitiveBool.Merge(dst, src)
}
func (m *PrimitiveBool) XXX_Size() int {
	return xxx_messageInfo_PrimitiveBool.Size(m)
}
func (m *PrimitiveBool) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimitiveBool.DiscardUnknown(m)
}

var xxx_messageInfo_PrimitiveBool proto.InternalMessageInfo

func (m *PrimitiveBool) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type PrimitiveVoid struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimitiveVoid) Reset()         { *m = PrimitiveVoid{} }
func (m *PrimitiveVoid) String() string { return proto.CompactTextString(m) }
func (*PrimitiveVoid) ProtoMessage()    {}
func (*PrimitiveVoid) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_240fc39444bbded4, []int{8}
}
func (m *PrimitiveVoid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimitiveVoid.Unmarshal(m, b)
}
func (m *PrimitiveVoid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimitiveVoid.Marshal(b, m, deterministic)
}
func (dst *PrimitiveVoid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimitiveVoid.Merge(dst, src)
}
func (m *PrimitiveVoid) XXX_Size() int {
	return xxx_messageInfo_PrimitiveVoid.Size(m)
}
func (m *PrimitiveVoid) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimitiveVoid.DiscardUnknown(m)
}

var xxx_messageInfo_PrimitiveVoid proto.InternalMessageInfo

type NodeData struct {
	CreatedAt            int64               `protobuf:"varint,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ContentType          NodeDataContentType `protobuf:"varint,2,opt,name=content_type,json=contentType,proto3,enum=iotgrpcapi.NodeDataContentType" json:"content_type,omitempty"`
	DataPoint            *DataPoint          `protobuf:"bytes,3,opt,name=data_point,json=dataPoint,proto3" json:"data_point,omitempty"`
	Spectrum             *Spectrum           `protobuf:"bytes,4,opt,name=spectrum,proto3" json:"spectrum,omitempty"`
	TimeSeries           *TimeSeries         `protobuf:"bytes,5,opt,name=time_series,json=timeSeries,proto3" json:"time_series,omitempty"`
	Note                 string              `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	Media                []byte              `protobuf:"bytes,7,opt,name=media,proto3" json:"media,omitempty"`
	QuestionAnswers      []string            `protobuf:"bytes,8,rep,name=question_answers,json=questionAnswers,proto3" json:"question_answers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *NodeData) Reset()         { *m = NodeData{} }
func (m *NodeData) String() string { return proto.CompactTextString(m) }
func (*NodeData) ProtoMessage()    {}
func (*NodeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_240fc39444bbded4, []int{9}
}
func (m *NodeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeData.Unmarshal(m, b)
}
func (m *NodeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeData.Marshal(b, m, deterministic)
}
func (dst *NodeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeData.Merge(dst, src)
}
func (m *NodeData) XXX_Size() int {
	return xxx_messageInfo_NodeData.Size(m)
}
func (m *NodeData) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeData.DiscardUnknown(m)
}

var xxx_messageInfo_NodeData proto.InternalMessageInfo

func (m *NodeData) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *NodeData) GetContentType() NodeDataContentType {
	if m != nil {
		return m.ContentType
	}
	return NodeDataContentType_DEFAULT
}

func (m *NodeData) GetDataPoint() *DataPoint {
	if m != nil {
		return m.DataPoint
	}
	return nil
}

func (m *NodeData) GetSpectrum() *Spectrum {
	if m != nil {
		return m.Spectrum
	}
	return nil
}

func (m *NodeData) GetTimeSeries() *TimeSeries {
	if m != nil {
		return m.TimeSeries
	}
	return nil
}

func (m *NodeData) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *NodeData) GetMedia() []byte {
	if m != nil {
		return m.Media
	}
	return nil
}

func (m *NodeData) GetQuestionAnswers() []string {
	if m != nil {
		return m.QuestionAnswers
	}
	return nil
}

type Coordinate struct {
	X                    float64  `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinate) Reset()         { *m = Coordinate{} }
func (m *Coordinate) String() string { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()    {}
func (*Coordinate) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_240fc39444bbded4, []int{10}
}
func (m *Coordinate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinate.Unmarshal(m, b)
}
func (m *Coordinate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinate.Marshal(b, m, deterministic)
}
func (dst *Coordinate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinate.Merge(dst, src)
}
func (m *Coordinate) XXX_Size() int {
	return xxx_messageInfo_Coordinate.Size(m)
}
func (m *Coordinate) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinate.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinate proto.InternalMessageInfo

func (m *Coordinate) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Coordinate) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type DataPoint struct {
	Coordinate           *Coordinate `protobuf:"bytes,1,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	XUnit                string      `protobuf:"bytes,2,opt,name=x_unit,json=xUnit,proto3" json:"x_unit,omitempty"`
	YUnit                string      `protobuf:"bytes,3,opt,name=y_unit,json=yUnit,proto3" json:"y_unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DataPoint) Reset()         { *m = DataPoint{} }
func (m *DataPoint) String() string { return proto.CompactTextString(m) }
func (*DataPoint) ProtoMessage()    {}
func (*DataPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_240fc39444bbded4, []int{11}
}
func (m *DataPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataPoint.Unmarshal(m, b)
}
func (m *DataPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataPoint.Marshal(b, m, deterministic)
}
func (dst *DataPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataPoint.Merge(dst, src)
}
func (m *DataPoint) XXX_Size() int {
	return xxx_messageInfo_DataPoint.Size(m)
}
func (m *DataPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_DataPoint.DiscardUnknown(m)
}

var xxx_messageInfo_DataPoint proto.InternalMessageInfo

func (m *DataPoint) GetCoordinate() *Coordinate {
	if m != nil {
		return m.Coordinate
	}
	return nil
}

func (m *DataPoint) GetXUnit() string {
	if m != nil {
		return m.XUnit
	}
	return ""
}

func (m *DataPoint) GetYUnit() string {
	if m != nil {
		return m.YUnit
	}
	return ""
}

type Spectrum struct {
	Coordinates          []*Coordinate `protobuf:"bytes,1,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	XUnit                string        `protobuf:"bytes,2,opt,name=x_unit,json=xUnit,proto3" json:"x_unit,omitempty"`
	YUnit                string        `protobuf:"bytes,3,opt,name=y_unit,json=yUnit,proto3" json:"y_unit,omitempty"`
	WindowFunction       string        `protobuf:"bytes,4,opt,name=window_function,json=windowFunction,proto3" json:"window_function,omitempty"`
	SpeedRpm             float64       `protobuf:"fixed64,5,opt,name=speed_rpm,json=speedRpm,proto3" json:"speed_rpm,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Spectrum) Reset()         { *m = Spectrum{} }
func (m *Spectrum) String() string { return proto.CompactTextString(m) }
func (*Spectrum) ProtoMessage()    {}
func (*Spectrum) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_240fc39444bbded4, []int{12}
}
func (m *Spectrum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Spectrum.Unmarshal(m, b)
}
func (m *Spectrum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Spectrum.Marshal(b, m, deterministic)
}
func (dst *Spectrum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Spectrum.Merge(dst, src)
}
func (m *Spectrum) XXX_Size() int {
	return xxx_messageInfo_Spectrum.Size(m)
}
func (m *Spectrum) XXX_DiscardUnknown() {
	xxx_messageInfo_Spectrum.DiscardUnknown(m)
}

var xxx_messageInfo_Spectrum proto.InternalMessageInfo

func (m *Spectrum) GetCoordinates() []*Coordinate {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *Spectrum) GetXUnit() string {
	if m != nil {
		return m.XUnit
	}
	return ""
}

func (m *Spectrum) GetYUnit() string {
	if m != nil {
		return m.YUnit
	}
	return ""
}

func (m *Spectrum) GetWindowFunction() string {
	if m != nil {
		return m.WindowFunction
	}
	return ""
}

func (m *Spectrum) GetSpeedRpm() float64 {
	if m != nil {
		return m.SpeedRpm
	}
	return 0
}

type TimeSeries struct {
	Coordinates          []*Coordinate `protobuf:"bytes,1,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	XUnit                string        `protobuf:"bytes,2,opt,name=x_unit,json=xUnit,proto3" json:"x_unit,omitempty"`
	YUnit                string        `protobuf:"bytes,3,opt,name=y_unit,json=yUnit,proto3" json:"y_unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TimeSeries) Reset()         { *m = TimeSeries{} }
func (m *TimeSeries) String() string { return proto.CompactTextString(m) }
func (*TimeSeries) ProtoMessage()    {}
func (*TimeSeries) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_240fc39444bbded4, []int{13}
}
func (m *TimeSeries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeSeries.Unmarshal(m, b)
}
func (m *TimeSeries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeSeries.Marshal(b, m, deterministic)
}
func (dst *TimeSeries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeSeries.Merge(dst, src)
}
func (m *TimeSeries) XXX_Size() int {
	return xxx_messageInfo_TimeSeries.Size(m)
}
func (m *TimeSeries) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeSeries.DiscardUnknown(m)
}

var xxx_messageInfo_TimeSeries proto.InternalMessageInfo

func (m *TimeSeries) GetCoordinates() []*Coordinate {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *TimeSeries) GetXUnit() string {
	if m != nil {
		return m.XUnit
	}
	return ""
}

func (m *TimeSeries) GetYUnit() string {
	if m != nil {
		return m.YUnit
	}
	return ""
}

// IngestNodeData messages
type IngestNodeDataInput struct {
	NodeId               string    `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeData             *NodeData `protobuf:"bytes,2,opt,name=node_data,json=nodeData,proto3" json:"node_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *IngestNodeDataInput) Reset()         { *m = IngestNodeDataInput{} }
func (m *IngestNodeDataInput) String() string { return proto.CompactTextString(m) }
func (*IngestNodeDataInput) ProtoMessage()    {}
func (*IngestNodeDataInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_240fc39444bbded4, []int{14}
}
func (m *IngestNodeDataInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IngestNodeDataInput.Unmarshal(m, b)
}
func (m *IngestNodeDataInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IngestNodeDataInput.Marshal(b, m, deterministic)
}
func (dst *IngestNodeDataInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IngestNodeDataInput.Merge(dst, src)
}
func (m *IngestNodeDataInput) XXX_Size() int {
	return xxx_messageInfo_IngestNodeDataInput.Size(m)
}
func (m *IngestNodeDataInput) XXX_DiscardUnknown() {
	xxx_messageInfo_IngestNodeDataInput.DiscardUnknown(m)
}

var xxx_messageInfo_IngestNodeDataInput proto.InternalMessageInfo

func (m *IngestNodeDataInput) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *IngestNodeDataInput) GetNodeData() *NodeData {
	if m != nil {
		return m.NodeData
	}
	return nil
}

type IngestNodeDataOutput struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IngestNodeDataOutput) Reset()         { *m = IngestNodeDataOutput{} }
func (m *IngestNodeDataOutput) String() string { return proto.CompactTextString(m) }
func (*IngestNodeDataOutput) ProtoMessage()    {}
func (*IngestNodeDataOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_240fc39444bbded4, []int{15}
}
func (m *IngestNodeDataOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IngestNodeDataOutput.Unmarshal(m, b)
}
func (m *IngestNodeDataOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IngestNodeDataOutput.Marshal(b, m, deterministic)
}
func (dst *IngestNodeDataOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IngestNodeDataOutput.Merge(dst, src)
}
func (m *IngestNodeDataOutput) XXX_Size() int {
	return xxx_messageInfo_IngestNodeDataOutput.Size(m)
}
func (m *IngestNodeDataOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_IngestNodeDataOutput.DiscardUnknown(m)
}

var xxx_messageInfo_IngestNodeDataOutput proto.InternalMessageInfo

// IngestNodeDataStream messages
type IngestNodeDataStreamInput struct {
	NodeId               string      `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeDataList         []*NodeData `protobuf:"bytes,2,rep,name=node_data_list,json=nodeDataList,proto3" json:"node_data_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *IngestNodeDataStreamInput) Reset()         { *m = IngestNodeDataStreamInput{} }
func (m *IngestNodeDataStreamInput) String() string { return proto.CompactTextString(m) }
func (*IngestNodeDataStreamInput) ProtoMessage()    {}
func (*IngestNodeDataStreamInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_240fc39444bbded4, []int{16}
}
func (m *IngestNodeDataStreamInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IngestNodeDataStreamInput.Unmarshal(m, b)
}
func (m *IngestNodeDataStreamInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IngestNodeDataStreamInput.Marshal(b, m, deterministic)
}
func (dst *IngestNodeDataStreamInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IngestNodeDataStreamInput.Merge(dst, src)
}
func (m *IngestNodeDataStreamInput) XXX_Size() int {
	return xxx_messageInfo_IngestNodeDataStreamInput.Size(m)
}
func (m *IngestNodeDataStreamInput) XXX_DiscardUnknown() {
	xxx_messageInfo_IngestNodeDataStreamInput.DiscardUnknown(m)
}

var xxx_messageInfo_IngestNodeDataStreamInput proto.InternalMessageInfo

func (m *IngestNodeDataStreamInput) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *IngestNodeDataStreamInput) GetNodeDataList() []*NodeData {
	if m != nil {
		return m.NodeDataList
	}
	return nil
}

type IngestNodeDataStreamOutput struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IngestNodeDataStreamOutput) Reset()         { *m = IngestNodeDataStreamOutput{} }
func (m *IngestNodeDataStreamOutput) String() string { return proto.CompactTextString(m) }
func (*IngestNodeDataStreamOutput) ProtoMessage()    {}
func (*IngestNodeDataStreamOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_240fc39444bbded4, []int{17}
}
func (m *IngestNodeDataStreamOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IngestNodeDataStreamOutput.Unmarshal(m, b)
}
func (m *IngestNodeDataStreamOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IngestNodeDataStreamOutput.Marshal(b, m, deterministic)
}
func (dst *IngestNodeDataStreamOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IngestNodeDataStreamOutput.Merge(dst, src)
}
func (m *IngestNodeDataStreamOutput) XXX_Size() int {
	return xxx_messageInfo_IngestNodeDataStreamOutput.Size(m)
}
func (m *IngestNodeDataStreamOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_IngestNodeDataStreamOutput.DiscardUnknown(m)
}

var xxx_messageInfo_IngestNodeDataStreamOutput proto.InternalMessageInfo

// GetNodeData messages
type GetNodeDataInput struct {
	NodeId               string              `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp            int64               `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ContentType          NodeDataContentType `protobuf:"varint,3,opt,name=content_type,json=contentType,proto3,enum=iotgrpcapi.NodeDataContentType" json:"content_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetNodeDataInput) Reset()         { *m = GetNodeDataInput{} }
func (m *GetNodeDataInput) String() string { return proto.CompactTextString(m) }
func (*GetNodeDataInput) ProtoMessage()    {}
func (*GetNodeDataInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_240fc39444bbded4, []int{18}
}
func (m *GetNodeDataInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeDataInput.Unmarshal(m, b)
}
func (m *GetNodeDataInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeDataInput.Marshal(b, m, deterministic)
}
func (dst *GetNodeDataInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeDataInput.Merge(dst, src)
}
func (m *GetNodeDataInput) XXX_Size() int {
	return xxx_messageInfo_GetNodeDataInput.Size(m)
}
func (m *GetNodeDataInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeDataInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeDataInput proto.InternalMessageInfo

func (m *GetNodeDataInput) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *GetNodeDataInput) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GetNodeDataInput) GetContentType() NodeDataContentType {
	if m != nil {
		return m.ContentType
	}
	return NodeDataContentType_DEFAULT
}

type GetNodeDataOutput struct {
	NodeDataList         []*NodeData `protobuf:"bytes,1,rep,name=node_data_list,json=nodeDataList,proto3" json:"node_data_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetNodeDataOutput) Reset()         { *m = GetNodeDataOutput{} }
func (m *GetNodeDataOutput) String() string { return proto.CompactTextString(m) }
func (*GetNodeDataOutput) ProtoMessage()    {}
func (*GetNodeDataOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_240fc39444bbded4, []int{19}
}
func (m *GetNodeDataOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeDataOutput.Unmarshal(m, b)
}
func (m *GetNodeDataOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeDataOutput.Marshal(b, m, deterministic)
}
func (dst *GetNodeDataOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeDataOutput.Merge(dst, src)
}
func (m *GetNodeDataOutput) XXX_Size() int {
	return xxx_messageInfo_GetNodeDataOutput.Size(m)
}
func (m *GetNodeDataOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeDataOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeDataOutput proto.InternalMessageInfo

func (m *GetNodeDataOutput) GetNodeDataList() []*NodeData {
	if m != nil {
		return m.NodeDataList
	}
	return nil
}

// GetNodeDataStream messages
type GetNodeDataStreamInput struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeDataStreamInput) Reset()         { *m = GetNodeDataStreamInput{} }
func (m *GetNodeDataStreamInput) String() string { return proto.CompactTextString(m) }
func (*GetNodeDataStreamInput) ProtoMessage()    {}
func (*GetNodeDataStreamInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_240fc39444bbded4, []int{20}
}
func (m *GetNodeDataStreamInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeDataStreamInput.Unmarshal(m, b)
}
func (m *GetNodeDataStreamInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeDataStreamInput.Marshal(b, m, deterministic)
}
func (dst *GetNodeDataStreamInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeDataStreamInput.Merge(dst, src)
}
func (m *GetNodeDataStreamInput) XXX_Size() int {
	return xxx_messageInfo_GetNodeDataStreamInput.Size(m)
}
func (m *GetNodeDataStreamInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeDataStreamInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeDataStreamInput proto.InternalMessageInfo

type GetNodeDataStreamOutput struct {
	NodeId               string    `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeData             *NodeData `protobuf:"bytes,2,opt,name=node_data,json=nodeData,proto3" json:"node_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetNodeDataStreamOutput) Reset()         { *m = GetNodeDataStreamOutput{} }
func (m *GetNodeDataStreamOutput) String() string { return proto.CompactTextString(m) }
func (*GetNodeDataStreamOutput) ProtoMessage()    {}
func (*GetNodeDataStreamOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_240fc39444bbded4, []int{21}
}
func (m *GetNodeDataStreamOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeDataStreamOutput.Unmarshal(m, b)
}
func (m *GetNodeDataStreamOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeDataStreamOutput.Marshal(b, m, deterministic)
}
func (dst *GetNodeDataStreamOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeDataStreamOutput.Merge(dst, src)
}
func (m *GetNodeDataStreamOutput) XXX_Size() int {
	return xxx_messageInfo_GetNodeDataStreamOutput.Size(m)
}
func (m *GetNodeDataStreamOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeDataStreamOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeDataStreamOutput proto.InternalMessageInfo

func (m *GetNodeDataStreamOutput) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *GetNodeDataStreamOutput) GetNodeData() *NodeData {
	if m != nil {
		return m.NodeData
	}
	return nil
}

type GetTaskStreamInput struct {
	HierarchyId          string   `protobuf:"bytes,1,opt,name=hierarchy_id,json=hierarchyId,proto3" json:"hierarchy_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTaskStreamInput) Reset()         { *m = GetTaskStreamInput{} }
func (m *GetTaskStreamInput) String() string { return proto.CompactTextString(m) }
func (*GetTaskStreamInput) ProtoMessage()    {}
func (*GetTaskStreamInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_240fc39444bbded4, []int{22}
}
func (m *GetTaskStreamInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskStreamInput.Unmarshal(m, b)
}
func (m *GetTaskStreamInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskStreamInput.Marshal(b, m, deterministic)
}
func (dst *GetTaskStreamInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskStreamInput.Merge(dst, src)
}
func (m *GetTaskStreamInput) XXX_Size() int {
	return xxx_messageInfo_GetTaskStreamInput.Size(m)
}
func (m *GetTaskStreamInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskStreamInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskStreamInput proto.InternalMessageInfo

func (m *GetTaskStreamInput) GetHierarchyId() string {
	if m != nil {
		return m.HierarchyId
	}
	return ""
}

type GetTaskStreamOutput struct {
	Task                 *TaskDescription `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetTaskStreamOutput) Reset()         { *m = GetTaskStreamOutput{} }
func (m *GetTaskStreamOutput) String() string { return proto.CompactTextString(m) }
func (*GetTaskStreamOutput) ProtoMessage()    {}
func (*GetTaskStreamOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_240fc39444bbded4, []int{23}
}
func (m *GetTaskStreamOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskStreamOutput.Unmarshal(m, b)
}
func (m *GetTaskStreamOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskStreamOutput.Marshal(b, m, deterministic)
}
func (dst *GetTaskStreamOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskStreamOutput.Merge(dst, src)
}
func (m *GetTaskStreamOutput) XXX_Size() int {
	return xxx_messageInfo_GetTaskStreamOutput.Size(m)
}
func (m *GetTaskStreamOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskStreamOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskStreamOutput proto.InternalMessageInfo

func (m *GetTaskStreamOutput) GetTask() *TaskDescription {
	if m != nil {
		return m.Task
	}
	return nil
}

func init() {
	proto.RegisterType((*TaskDescription)(nil), "iotgrpcapi.TaskDescription")
	proto.RegisterType((*InitialTaskDescription)(nil), "iotgrpcapi.InitialTaskDescription")
	proto.RegisterType((*TaskUser)(nil), "iotgrpcapi.TaskUser")
	proto.RegisterType((*SetTaskStatusInput)(nil), "iotgrpcapi.SetTaskStatusInput")
	proto.RegisterType((*TaskDescriptions)(nil), "iotgrpcapi.TaskDescriptions")
	proto.RegisterType((*FunctionalLocationIds)(nil), "iotgrpcapi.FunctionalLocationIds")
	proto.RegisterType((*PrimitiveString)(nil), "iotgrpcapi.PrimitiveString")
	proto.RegisterType((*PrimitiveBool)(nil), "iotgrpcapi.PrimitiveBool")
	proto.RegisterType((*PrimitiveVoid)(nil), "iotgrpcapi.PrimitiveVoid")
	proto.RegisterType((*NodeData)(nil), "iotgrpcapi.NodeData")
	proto.RegisterType((*Coordinate)(nil), "iotgrpcapi.Coordinate")
	proto.RegisterType((*DataPoint)(nil), "iotgrpcapi.DataPoint")
	proto.RegisterType((*Spectrum)(nil), "iotgrpcapi.Spectrum")
	proto.RegisterType((*TimeSeries)(nil), "iotgrpcapi.TimeSeries")
	proto.RegisterType((*IngestNodeDataInput)(nil), "iotgrpcapi.IngestNodeDataInput")
	proto.RegisterType((*IngestNodeDataOutput)(nil), "iotgrpcapi.IngestNodeDataOutput")
	proto.RegisterType((*IngestNodeDataStreamInput)(nil), "iotgrpcapi.IngestNodeDataStreamInput")
	proto.RegisterType((*IngestNodeDataStreamOutput)(nil), "iotgrpcapi.IngestNodeDataStreamOutput")
	proto.RegisterType((*GetNodeDataInput)(nil), "iotgrpcapi.GetNodeDataInput")
	proto.RegisterType((*GetNodeDataOutput)(nil), "iotgrpcapi.GetNodeDataOutput")
	proto.RegisterType((*GetNodeDataStreamInput)(nil), "iotgrpcapi.GetNodeDataStreamInput")
	proto.RegisterType((*GetNodeDataStreamOutput)(nil), "iotgrpcapi.GetNodeDataStreamOutput")
	proto.RegisterType((*GetTaskStreamInput)(nil), "iotgrpcapi.GetTaskStreamInput")
	proto.RegisterType((*GetTaskStreamOutput)(nil), "iotgrpcapi.GetTaskStreamOutput")
	proto.RegisterEnum("iotgrpcapi.TaskStatus", TaskStatus_name, TaskStatus_value)
	proto.RegisterEnum("iotgrpcapi.NodeDataContentType", NodeDataContentType_name, NodeDataContentType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IoTClient is the client API for IoT service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IoTClient interface {
	DeepPing(ctx context.Context, in *PrimitiveVoid, opts ...grpc.CallOption) (*PrimitiveString, error)
	CreateTask(ctx context.Context, in *InitialTaskDescription, opts ...grpc.CallOption) (*PrimitiveString, error)
	GetAllTasks(ctx context.Context, in *PrimitiveString, opts ...grpc.CallOption) (*TaskDescriptions, error)
	GetUncompletedTasks(ctx context.Context, in *PrimitiveString, opts ...grpc.CallOption) (*TaskDescriptions, error)
	SetTaskCompleted(ctx context.Context, in *TaskUser, opts ...grpc.CallOption) (*PrimitiveVoid, error)
	DeleteTask(ctx context.Context, in *TaskUser, opts ...grpc.CallOption) (*PrimitiveVoid, error)
	GetUncompletedTasksByHierarchy(ctx context.Context, in *PrimitiveString, opts ...grpc.CallOption) (*TaskDescriptions, error)
	SetTaskStatus(ctx context.Context, in *SetTaskStatusInput, opts ...grpc.CallOption) (*PrimitiveVoid, error)
	GetTaskStream(ctx context.Context, in *GetTaskStreamInput, opts ...grpc.CallOption) (IoT_GetTaskStreamClient, error)
	IngestNodeData(ctx context.Context, in *IngestNodeDataInput, opts ...grpc.CallOption) (*IngestNodeDataOutput, error)
	IngestNodeDataStream(ctx context.Context, opts ...grpc.CallOption) (IoT_IngestNodeDataStreamClient, error)
	GetNodeData(ctx context.Context, in *GetNodeDataInput, opts ...grpc.CallOption) (*GetNodeDataOutput, error)
	GetNodeDataStream(ctx context.Context, in *GetNodeDataStreamInput, opts ...grpc.CallOption) (IoT_GetNodeDataStreamClient, error)
}

type ioTClient struct {
	cc *grpc.ClientConn
}

func NewIoTClient(cc *grpc.ClientConn) IoTClient {
	return &ioTClient{cc}
}

func (c *ioTClient) DeepPing(ctx context.Context, in *PrimitiveVoid, opts ...grpc.CallOption) (*PrimitiveString, error) {
	out := new(PrimitiveString)
	err := c.cc.Invoke(ctx, "/iotgrpcapi.IoT/DeepPing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioTClient) CreateTask(ctx context.Context, in *InitialTaskDescription, opts ...grpc.CallOption) (*PrimitiveString, error) {
	out := new(PrimitiveString)
	err := c.cc.Invoke(ctx, "/iotgrpcapi.IoT/CreateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioTClient) GetAllTasks(ctx context.Context, in *PrimitiveString, opts ...grpc.CallOption) (*TaskDescriptions, error) {
	out := new(TaskDescriptions)
	err := c.cc.Invoke(ctx, "/iotgrpcapi.IoT/GetAllTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioTClient) GetUncompletedTasks(ctx context.Context, in *PrimitiveString, opts ...grpc.CallOption) (*TaskDescriptions, error) {
	out := new(TaskDescriptions)
	err := c.cc.Invoke(ctx, "/iotgrpcapi.IoT/GetUncompletedTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioTClient) SetTaskCompleted(ctx context.Context, in *TaskUser, opts ...grpc.CallOption) (*PrimitiveVoid, error) {
	out := new(PrimitiveVoid)
	err := c.cc.Invoke(ctx, "/iotgrpcapi.IoT/SetTaskCompleted", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioTClient) DeleteTask(ctx context.Context, in *TaskUser, opts ...grpc.CallOption) (*PrimitiveVoid, error) {
	out := new(PrimitiveVoid)
	err := c.cc.Invoke(ctx, "/iotgrpcapi.IoT/DeleteTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioTClient) GetUncompletedTasksByHierarchy(ctx context.Context, in *PrimitiveString, opts ...grpc.CallOption) (*TaskDescriptions, error) {
	out := new(TaskDescriptions)
	err := c.cc.Invoke(ctx, "/iotgrpcapi.IoT/GetUncompletedTasksByHierarchy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioTClient) SetTaskStatus(ctx context.Context, in *SetTaskStatusInput, opts ...grpc.CallOption) (*PrimitiveVoid, error) {
	out := new(PrimitiveVoid)
	err := c.cc.Invoke(ctx, "/iotgrpcapi.IoT/SetTaskStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioTClient) GetTaskStream(ctx context.Context, in *GetTaskStreamInput, opts ...grpc.CallOption) (IoT_GetTaskStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_IoT_serviceDesc.Streams[0], "/iotgrpcapi.IoT/GetTaskStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &ioTGetTaskStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type IoT_GetTaskStreamClient interface {
	Recv() (*GetTaskStreamOutput, error)
	grpc.ClientStream
}

type ioTGetTaskStreamClient struct {
	grpc.ClientStream
}

func (x *ioTGetTaskStreamClient) Recv() (*GetTaskStreamOutput, error) {
	m := new(GetTaskStreamOutput)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ioTClient) IngestNodeData(ctx context.Context, in *IngestNodeDataInput, opts ...grpc.CallOption) (*IngestNodeDataOutput, error) {
	out := new(IngestNodeDataOutput)
	err := c.cc.Invoke(ctx, "/iotgrpcapi.IoT/IngestNodeData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioTClient) IngestNodeDataStream(ctx context.Context, opts ...grpc.CallOption) (IoT_IngestNodeDataStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_IoT_serviceDesc.Streams[1], "/iotgrpcapi.IoT/IngestNodeDataStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &ioTIngestNodeDataStreamClient{stream}
	return x, nil
}

type IoT_IngestNodeDataStreamClient interface {
	Send(*IngestNodeDataStreamInput) error
	CloseAndRecv() (*IngestNodeDataStreamOutput, error)
	grpc.ClientStream
}

type ioTIngestNodeDataStreamClient struct {
	grpc.ClientStream
}

func (x *ioTIngestNodeDataStreamClient) Send(m *IngestNodeDataStreamInput) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ioTIngestNodeDataStreamClient) CloseAndRecv() (*IngestNodeDataStreamOutput, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(IngestNodeDataStreamOutput)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ioTClient) GetNodeData(ctx context.Context, in *GetNodeDataInput, opts ...grpc.CallOption) (*GetNodeDataOutput, error) {
	out := new(GetNodeDataOutput)
	err := c.cc.Invoke(ctx, "/iotgrpcapi.IoT/GetNodeData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioTClient) GetNodeDataStream(ctx context.Context, in *GetNodeDataStreamInput, opts ...grpc.CallOption) (IoT_GetNodeDataStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_IoT_serviceDesc.Streams[2], "/iotgrpcapi.IoT/GetNodeDataStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &ioTGetNodeDataStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type IoT_GetNodeDataStreamClient interface {
	Recv() (*GetNodeDataStreamOutput, error)
	grpc.ClientStream
}

type ioTGetNodeDataStreamClient struct {
	grpc.ClientStream
}

func (x *ioTGetNodeDataStreamClient) Recv() (*GetNodeDataStreamOutput, error) {
	m := new(GetNodeDataStreamOutput)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// IoTServer is the server API for IoT service.
type IoTServer interface {
	DeepPing(context.Context, *PrimitiveVoid) (*PrimitiveString, error)
	CreateTask(context.Context, *InitialTaskDescription) (*PrimitiveString, error)
	GetAllTasks(context.Context, *PrimitiveString) (*TaskDescriptions, error)
	GetUncompletedTasks(context.Context, *PrimitiveString) (*TaskDescriptions, error)
	SetTaskCompleted(context.Context, *TaskUser) (*PrimitiveVoid, error)
	DeleteTask(context.Context, *TaskUser) (*PrimitiveVoid, error)
	GetUncompletedTasksByHierarchy(context.Context, *PrimitiveString) (*TaskDescriptions, error)
	SetTaskStatus(context.Context, *SetTaskStatusInput) (*PrimitiveVoid, error)
	GetTaskStream(*GetTaskStreamInput, IoT_GetTaskStreamServer) error
	IngestNodeData(context.Context, *IngestNodeDataInput) (*IngestNodeDataOutput, error)
	IngestNodeDataStream(IoT_IngestNodeDataStreamServer) error
	GetNodeData(context.Context, *GetNodeDataInput) (*GetNodeDataOutput, error)
	GetNodeDataStream(*GetNodeDataStreamInput, IoT_GetNodeDataStreamServer) error
}

func RegisterIoTServer(s *grpc.Server, srv IoTServer) {
	s.RegisterService(&_IoT_serviceDesc, srv)
}

func _IoT_DeepPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimitiveVoid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoTServer).DeepPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iotgrpcapi.IoT/DeepPing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoTServer).DeepPing(ctx, req.(*PrimitiveVoid))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoT_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitialTaskDescription)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoTServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iotgrpcapi.IoT/CreateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoTServer).CreateTask(ctx, req.(*InitialTaskDescription))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoT_GetAllTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimitiveString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoTServer).GetAllTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iotgrpcapi.IoT/GetAllTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoTServer).GetAllTasks(ctx, req.(*PrimitiveString))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoT_GetUncompletedTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimitiveString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoTServer).GetUncompletedTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iotgrpcapi.IoT/GetUncompletedTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoTServer).GetUncompletedTasks(ctx, req.(*PrimitiveString))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoT_SetTaskCompleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoTServer).SetTaskCompleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iotgrpcapi.IoT/SetTaskCompleted",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoTServer).SetTaskCompleted(ctx, req.(*TaskUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoT_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoTServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iotgrpcapi.IoT/DeleteTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoTServer).DeleteTask(ctx, req.(*TaskUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoT_GetUncompletedTasksByHierarchy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimitiveString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoTServer).GetUncompletedTasksByHierarchy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iotgrpcapi.IoT/GetUncompletedTasksByHierarchy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoTServer).GetUncompletedTasksByHierarchy(ctx, req.(*PrimitiveString))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoT_SetTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTaskStatusInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoTServer).SetTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iotgrpcapi.IoT/SetTaskStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoTServer).SetTaskStatus(ctx, req.(*SetTaskStatusInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoT_GetTaskStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetTaskStreamInput)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IoTServer).GetTaskStream(m, &ioTGetTaskStreamServer{stream})
}

type IoT_GetTaskStreamServer interface {
	Send(*GetTaskStreamOutput) error
	grpc.ServerStream
}

type ioTGetTaskStreamServer struct {
	grpc.ServerStream
}

func (x *ioTGetTaskStreamServer) Send(m *GetTaskStreamOutput) error {
	return x.ServerStream.SendMsg(m)
}

func _IoT_IngestNodeData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestNodeDataInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoTServer).IngestNodeData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iotgrpcapi.IoT/IngestNodeData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoTServer).IngestNodeData(ctx, req.(*IngestNodeDataInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoT_IngestNodeDataStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IoTServer).IngestNodeDataStream(&ioTIngestNodeDataStreamServer{stream})
}

type IoT_IngestNodeDataStreamServer interface {
	SendAndClose(*IngestNodeDataStreamOutput) error
	Recv() (*IngestNodeDataStreamInput, error)
	grpc.ServerStream
}

type ioTIngestNodeDataStreamServer struct {
	grpc.ServerStream
}

func (x *ioTIngestNodeDataStreamServer) SendAndClose(m *IngestNodeDataStreamOutput) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ioTIngestNodeDataStreamServer) Recv() (*IngestNodeDataStreamInput, error) {
	m := new(IngestNodeDataStreamInput)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _IoT_GetNodeData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeDataInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoTServer).GetNodeData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iotgrpcapi.IoT/GetNodeData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoTServer).GetNodeData(ctx, req.(*GetNodeDataInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoT_GetNodeDataStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetNodeDataStreamInput)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IoTServer).GetNodeDataStream(m, &ioTGetNodeDataStreamServer{stream})
}

type IoT_GetNodeDataStreamServer interface {
	Send(*GetNodeDataStreamOutput) error
	grpc.ServerStream
}

type ioTGetNodeDataStreamServer struct {
	grpc.ServerStream
}

func (x *ioTGetNodeDataStreamServer) Send(m *GetNodeDataStreamOutput) error {
	return x.ServerStream.SendMsg(m)
}

var _IoT_serviceDesc = grpc.ServiceDesc{
	ServiceName: "iotgrpcapi.IoT",
	HandlerType: (*IoTServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeepPing",
			Handler:    _IoT_DeepPing_Handler,
		},
		{
			MethodName: "CreateTask",
			Handler:    _IoT_CreateTask_Handler,
		},
		{
			MethodName: "GetAllTasks",
			Handler:    _IoT_GetAllTasks_Handler,
		},
		{
			MethodName: "GetUncompletedTasks",
			Handler:    _IoT_GetUncompletedTasks_Handler,
		},
		{
			MethodName: "SetTaskCompleted",
			Handler:    _IoT_SetTaskCompleted_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _IoT_DeleteTask_Handler,
		},
		{
			MethodName: "GetUncompletedTasksByHierarchy",
			Handler:    _IoT_GetUncompletedTasksByHierarchy_Handler,
		},
		{
			MethodName: "SetTaskStatus",
			Handler:    _IoT_SetTaskStatus_Handler,
		},
		{
			MethodName: "IngestNodeData",
			Handler:    _IoT_IngestNodeData_Handler,
		},
		{
			MethodName: "GetNodeData",
			Handler:    _IoT_GetNodeData_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTaskStream",
			Handler:       _IoT_GetTaskStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "IngestNodeDataStream",
			Handler:       _IoT_IngestNodeDataStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetNodeDataStream",
			Handler:       _IoT_GetNodeDataStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpcapi.proto",
}

func init() { proto.RegisterFile("grpcapi.proto", fileDescriptor_grpcapi_240fc39444bbded4) }

var fileDescriptor_grpcapi_240fc39444bbded4 = []byte{
	// 1333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xeb, 0x72, 0xdb, 0x44,
	0x14, 0x8e, 0xec, 0xd8, 0x91, 0x8f, 0x73, 0x11, 0xdb, 0x24, 0x75, 0xd3, 0xb4, 0x75, 0xc5, 0x94,
	0x9a, 0x0e, 0x13, 0x4a, 0x60, 0x28, 0xc3, 0x30, 0xc3, 0xb8, 0xb6, 0x5a, 0xc4, 0x24, 0x76, 0x90,
	0xe4, 0x32, 0xfc, 0x60, 0x84, 0xf0, 0x6e, 0xdb, 0x9d, 0xda, 0x92, 0x2a, 0xad, 0xda, 0x78, 0x86,
	0x17, 0xe0, 0x07, 0xef, 0x03, 0xef, 0xc1, 0x1b, 0xf0, 0x22, 0xcc, 0xae, 0xee, 0x8e, 0x9d, 0x0b,
	0xed, 0xf0, 0x4f, 0x7b, 0x6e, 0xfb, 0xed, 0x77, 0xce, 0x9e, 0xb3, 0x82, 0x8d, 0x17, 0x81, 0x3f,
	0x76, 0x7c, 0x7a, 0xe0, 0x07, 0x1e, 0xf3, 0x10, 0x50, 0x8f, 0x25, 0x12, 0xf5, 0xf7, 0x2a, 0x6c,
	0x59, 0x4e, 0xf8, 0xaa, 0x4f, 0xc2, 0x71, 0x40, 0x7d, 0x46, 0x3d, 0x17, 0x5d, 0x87, 0xb5, 0x28,
	0x24, 0x81, 0x4d, 0x71, 0x4b, 0x6a, 0x4b, 0x9d, 0x86, 0x51, 0xe7, 0x4b, 0x1d, 0x73, 0x05, 0x73,
	0xc2, 0x57, 0x5c, 0x51, 0x89, 0x15, 0x7c, 0xa9, 0x63, 0x74, 0x13, 0x1a, 0x42, 0xe1, 0x3a, 0x53,
	0xd2, 0xaa, 0x0a, 0x95, 0xcc, 0x05, 0x03, 0x67, 0x4a, 0xd0, 0x5d, 0x58, 0x7f, 0x49, 0x49, 0xe0,
	0x04, 0xe3, 0x97, 0x33, 0xee, 0xba, 0x2a, 0xf4, 0xcd, 0x4c, 0xa6, 0x63, 0xf4, 0x09, 0x20, 0x1c,
	0x11, 0x1b, 0x3b, 0x8c, 0xd8, 0x8c, 0x4e, 0x49, 0xc8, 0x9c, 0xa9, 0xdf, 0xaa, 0xb5, 0xa5, 0x4e,
	0xd5, 0x50, 0x70, 0x44, 0xfa, 0x0e, 0x23, 0x56, 0x2a, 0xe7, 0x01, 0x69, 0x68, 0x8f, 0xbd, 0xa9,
	0x3f, 0x21, 0x8c, 0xe0, 0x56, 0xbd, 0x2d, 0x75, 0x64, 0xa3, 0x49, 0xc3, 0x5e, 0x2a, 0x42, 0x3f,
	0xc1, 0xf5, 0xe7, 0x91, 0x3b, 0xe6, 0xc7, 0x71, 0x26, 0xf6, 0xc4, 0x1b, 0x3b, 0xfc, 0xd3, 0xa6,
	0x38, 0x6c, 0xad, 0xb5, 0xa5, 0x4e, 0xf3, 0xf0, 0xee, 0x41, 0x4e, 0xc2, 0xc1, 0x93, 0xcc, 0xf4,
	0x28, 0xb1, 0xd4, 0x71, 0x68, 0xec, 0x3c, 0x5f, 0x24, 0x46, 0x07, 0x50, 0x0f, 0x99, 0xc3, 0xa2,
	0xb0, 0x25, 0xb7, 0xa5, 0xce, 0xe6, 0xe1, 0x6e, 0x31, 0x12, 0xa7, 0xd2, 0x14, 0x5a, 0x23, 0xb1,
	0x42, 0x1d, 0x50, 0xc8, 0x29, 0x23, 0x01, 0x07, 0x92, 0xb2, 0xd7, 0x10, 0x14, 0x6c, 0xa6, 0x72,
	0x4b, 0xb0, 0xa8, 0xfe, 0x5d, 0x81, 0x5d, 0xdd, 0xa5, 0x8c, 0xc6, 0x92, 0x4b, 0xa5, 0xa4, 0xc4,
	0x7c, 0xe5, 0x02, 0xe6, 0xab, 0x97, 0x65, 0x7e, 0x75, 0x09, 0xf3, 0xe7, 0xd0, 0x5a, 0x7b, 0x47,
	0x5a, 0x17, 0xd1, 0x54, 0x5f, 0x44, 0x53, 0x21, 0x01, 0x6b, 0x97, 0x49, 0x80, 0xfa, 0x0d, 0xc8,
	0x5c, 0x3a, 0x0a, 0x49, 0x70, 0xf5, 0xd2, 0x56, 0xdf, 0x00, 0x32, 0x09, 0xcb, 0xc3, 0xea, 0xae,
	0x1f, 0xb1, 0xa2, 0xb9, 0x54, 0xba, 0x09, 0x39, 0xb8, 0xca, 0xa5, 0xaa, 0xa3, 0x00, 0xa8, 0x5a,
	0x04, 0xa4, 0x3a, 0xa0, 0xcc, 0x15, 0x41, 0x88, 0x8e, 0x61, 0x5b, 0xec, 0x8a, 0x73, 0xa1, 0xed,
	0x04, 0x41, 0x4b, 0x6a, 0x57, 0x3b, 0xcd, 0xc3, 0x9b, 0xf3, 0x5b, 0x15, 0x7c, 0x0d, 0xc4, 0xca,
	0x82, 0x6e, 0x10, 0xa8, 0x07, 0xb0, 0xb3, 0x30, 0x45, 0x68, 0x07, 0xea, 0x14, 0x67, 0x91, 0x1b,
	0x46, 0x8d, 0x62, 0x6e, 0x7f, 0x1f, 0xb6, 0x4e, 0x02, 0x3a, 0xa5, 0x8c, 0xbe, 0x21, 0x26, 0x0b,
	0xa8, 0xfb, 0x02, 0x6d, 0x43, 0xed, 0x8d, 0x33, 0x89, 0x48, 0xc2, 0x42, 0xbc, 0x50, 0xef, 0xc1,
	0x46, 0x66, 0xf8, 0xd8, 0xf3, 0x26, 0x65, 0x33, 0x39, 0x35, 0xdb, 0x2a, 0x98, 0x3d, 0xf3, 0x28,
	0x56, 0xff, 0xa9, 0x80, 0x3c, 0xf0, 0x30, 0x2f, 0x3a, 0x07, 0xdd, 0x02, 0x18, 0x07, 0xc4, 0x61,
	0x04, 0xdb, 0x0e, 0x13, 0x8e, 0x55, 0xa3, 0x91, 0x48, 0xba, 0x0c, 0x3d, 0x86, 0xf5, 0xb1, 0xe7,
	0x32, 0xe2, 0x32, 0x9b, 0xcd, 0x7c, 0x92, 0xd0, 0x7d, 0xa7, 0xc8, 0x41, 0x1a, 0xaa, 0x17, 0xdb,
	0x59, 0x33, 0x9f, 0x18, 0xcd, 0x71, 0xbe, 0x40, 0x5f, 0x00, 0x60, 0x87, 0x39, 0xb6, 0xef, 0x51,
	0x97, 0x09, 0xfe, 0x9b, 0x87, 0x3b, 0xc5, 0x08, 0xdc, 0xfb, 0x84, 0x2b, 0x8d, 0x06, 0x4e, 0x3f,
	0xd1, 0x43, 0x90, 0x43, 0x9f, 0x8c, 0x59, 0x10, 0x4d, 0xc5, 0x45, 0x69, 0x1e, 0x6e, 0x17, 0x7d,
	0xcc, 0x44, 0x67, 0x64, 0x56, 0xe8, 0x11, 0x34, 0xf9, 0xdd, 0xb2, 0x43, 0x12, 0x50, 0x92, 0x5e,
	0x95, 0x72, 0x65, 0xd0, 0x29, 0x31, 0x85, 0xd6, 0x00, 0x96, 0x7d, 0x23, 0x04, 0xab, 0xae, 0xc7,
	0x48, 0x72, 0x11, 0xc4, 0x37, 0xe7, 0x72, 0x4a, 0x30, 0x75, 0x44, 0xf5, 0xaf, 0x1b, 0xf1, 0x02,
	0x7d, 0x0c, 0xca, 0xeb, 0x88, 0x84, 0x71, 0x49, 0xb8, 0xe1, 0x5b, 0x12, 0xf0, 0xfe, 0xc4, 0x93,
	0xb7, 0x95, 0xca, 0xbb, 0xb1, 0x58, 0xed, 0x00, 0xf4, 0x3c, 0x2f, 0xc0, 0xd4, 0x75, 0x18, 0x41,
	0xeb, 0x20, 0x9d, 0x0a, 0x76, 0x25, 0x43, 0x3a, 0xe5, 0xab, 0x99, 0xa0, 0x52, 0x32, 0xa4, 0x99,
	0xfa, 0x1a, 0x1a, 0x19, 0x03, 0xe8, 0x4b, 0x80, 0x71, 0xe6, 0x26, 0x3c, 0xe6, 0xce, 0x90, 0x07,
	0x35, 0x0a, 0x96, 0xbc, 0x98, 0x4e, 0xed, 0xc8, 0xa5, 0x2c, 0xb9, 0x58, 0xb5, 0xd3, 0x91, 0x4b,
	0x19, 0x17, 0xcf, 0x62, 0x71, 0x5c, 0xf7, 0xb5, 0x19, 0x17, 0xab, 0x7f, 0x4a, 0x20, 0xa7, 0x0c,
	0xa2, 0xaf, 0xa0, 0x99, 0x07, 0x0a, 0x93, 0x32, 0x5f, 0xb6, 0x67, 0xd1, 0xf4, 0x6a, 0x9b, 0xa2,
	0xfb, 0xb0, 0xf5, 0x96, 0xba, 0xd8, 0x7b, 0x6b, 0xa7, 0xbd, 0x29, 0x19, 0x52, 0x9b, 0xb1, 0x38,
	0xbd, 0x25, 0xbc, 0xdb, 0x86, 0x3e, 0x21, 0xd8, 0x0e, 0xfc, 0xa9, 0x48, 0xa3, 0x24, 0xb2, 0x4c,
	0xb0, 0xe1, 0x4f, 0x55, 0x06, 0x90, 0xa7, 0xf1, 0xff, 0xc2, 0xae, 0x3a, 0x70, 0x4d, 0x77, 0x5f,
	0x90, 0x90, 0xa5, 0xd5, 0x9e, 0x35, 0x28, 0xd7, 0xc3, 0xa4, 0xd0, 0xa0, 0xf8, 0x52, 0xc7, 0xe8,
	0x33, 0x68, 0x08, 0x05, 0xaf, 0x67, 0xb1, 0xc1, 0x5c, 0xf9, 0xa6, 0x61, 0x0c, 0xd9, 0x4d, 0xbe,
	0xd4, 0x5d, 0xd8, 0x2e, 0x6f, 0x31, 0x8c, 0x98, 0x1f, 0x31, 0xd5, 0x87, 0x1b, 0x65, 0xb9, 0xc9,
	0x02, 0xe2, 0x4c, 0x2f, 0x00, 0xf0, 0x35, 0x6c, 0x66, 0x00, 0xec, 0x09, 0x0d, 0xf9, 0x31, 0xab,
	0x4b, 0x51, 0xac, 0xa7, 0x28, 0x8e, 0x68, 0xc8, 0xd4, 0x7d, 0xd8, 0x5b, 0xb4, 0x63, 0x82, 0xe7,
	0x0f, 0x09, 0x94, 0xa7, 0xe4, 0xb2, 0x44, 0xec, 0x43, 0x23, 0x1f, 0x78, 0x95, 0xb8, 0xbd, 0x64,
	0x82, 0x33, 0xed, 0xa5, 0x7a, 0xf5, 0xf6, 0xa2, 0x0e, 0xe1, 0x83, 0x02, 0x9c, 0x18, 0xe4, 0x82,
	0xe3, 0x4b, 0x97, 0x3e, 0x7e, 0x0b, 0x76, 0x0b, 0x01, 0x0b, 0x6c, 0xab, 0x04, 0xae, 0x9f, 0xd1,
	0x24, 0x1b, 0xbe, 0xcf, 0x4a, 0x78, 0x04, 0xe8, 0x69, 0x3a, 0x0c, 0xf3, 0x54, 0xcf, 0x3f, 0x33,
	0xa4, 0x33, 0xcf, 0x0c, 0xf5, 0x09, 0x5c, 0x2b, 0x39, 0x26, 0xd8, 0x3e, 0x85, 0x55, 0x3e, 0x97,
	0x92, 0x6e, 0x72, 0xee, 0x00, 0x13, 0x86, 0x0f, 0xba, 0x00, 0xf9, 0x10, 0x45, 0xeb, 0x20, 0x0f,
	0x86, 0x96, 0x6d, 0x6a, 0x03, 0x4b, 0x59, 0x41, 0x32, 0xac, 0x8a, 0x2f, 0x89, 0xcb, 0x0d, 0xad,
	0xa7, 0xe9, 0xcf, 0xb4, 0xbe, 0x52, 0x41, 0x1b, 0xd0, 0xe8, 0x0d, 0x8f, 0x4f, 0x8e, 0x34, 0x4b,
	0xeb, 0x2b, 0xd5, 0x07, 0xbf, 0xc1, 0xb5, 0x05, 0x99, 0x43, 0x4d, 0x58, 0xeb, 0x6b, 0x4f, 0xba,
	0xa3, 0x23, 0x1e, 0x6a, 0x13, 0xa0, 0xdf, 0xb5, 0xba, 0xf6, 0xc9, 0x50, 0x4f, 0x03, 0x9a, 0x27,
	0x5a, 0xcf, 0x32, 0x46, 0xc7, 0x4a, 0x05, 0x6d, 0x41, 0xd3, 0xd2, 0x8f, 0x35, 0xdb, 0xd4, 0x0c,
	0x5d, 0x33, 0x95, 0x2a, 0xdf, 0x79, 0x30, 0xb4, 0x34, 0x65, 0x15, 0x35, 0xa0, 0x76, 0xac, 0xf5,
	0xf5, 0xae, 0x52, 0x43, 0xdb, 0xa0, 0xfc, 0x30, 0xd2, 0x4c, 0x4b, 0x1f, 0x0e, 0xec, 0xee, 0xc0,
	0xfc, 0x51, 0x33, 0x4c, 0xa5, 0x7e, 0xf8, 0x97, 0x0c, 0x55, 0xdd, 0xb3, 0x50, 0x1f, 0xe4, 0x3e,
	0x21, 0xfe, 0x09, 0x1f, 0xa2, 0x37, 0x8a, 0xe7, 0x2e, 0x4d, 0xc4, 0xbd, 0x9b, 0x0b, 0x55, 0xf1,
	0xf0, 0x55, 0x57, 0xd0, 0x10, 0xa0, 0x27, 0x26, 0x22, 0x27, 0x05, 0xa9, 0x45, 0xe3, 0xc5, 0x0f,
	0xc9, 0x8b, 0x02, 0x7e, 0x0f, 0xcd, 0xa7, 0x84, 0x75, 0x27, 0xc2, 0x2f, 0x44, 0xe7, 0x59, 0xef,
	0xed, 0x9f, 0x93, 0xae, 0x50, 0x5d, 0x41, 0x86, 0xc8, 0xf9, 0xc8, 0xcd, 0x1e, 0xea, 0xef, 0x21,
	0xa6, 0x06, 0x4a, 0xf2, 0x1a, 0xcb, 0xdf, 0xfa, 0xdb, 0xf3, 0x3e, 0xfc, 0xa5, 0xb7, 0xb7, 0x9c,
	0x54, 0x75, 0x05, 0x7d, 0x0b, 0xd0, 0x27, 0xdc, 0x5b, 0xf0, 0xf6, 0x1f, 0x02, 0xfc, 0x0c, 0xb7,
	0x17, 0x9c, 0xed, 0xf1, 0xec, 0xbb, 0xb4, 0xe6, 0xdf, 0xed, 0x98, 0x47, 0xb0, 0x51, 0x7a, 0x74,
	0xa2, 0xdb, 0xa5, 0x17, 0xc6, 0x99, 0xf7, 0xe8, 0xf9, 0x60, 0x2d, 0xd8, 0x28, 0x5d, 0xbe, 0x72,
	0xb4, 0xb3, 0x17, 0x7a, 0xef, 0xce, 0x52, 0x7d, 0xd2, 0x69, 0x57, 0x1e, 0x4a, 0x68, 0x04, 0x9b,
	0xe5, 0x5e, 0x8c, 0xee, 0x94, 0xeb, 0xef, 0xcc, 0x50, 0xda, 0x6b, 0x2f, 0x37, 0x48, 0x03, 0x23,
	0x3a, 0x3f, 0x6c, 0x12, 0xcc, 0xf7, 0x96, 0xfb, 0x16, 0xa1, 0x7f, 0x74, 0x91, 0x59, 0xba, 0x51,
	0x47, 0x42, 0x47, 0xa2, 0xd8, 0x33, 0xf8, 0xfb, 0x73, 0xa7, 0x2e, 0x63, 0xbf, 0xb5, 0x44, 0x9b,
	0x01, 0xff, 0xa5, 0xd4, 0xed, 0x13, 0xd4, 0xea, 0x12, 0xaf, 0x22, 0xe4, 0x0f, 0xcf, 0xb5, 0xc9,
	0x19, 0xff, 0xb5, 0x2e, 0x7e, 0xdf, 0x3f, 0xff, 0x37, 0x00, 0x00, 0xff, 0xff, 0xc2, 0xf3, 0xff,
	0x78, 0xcf, 0x0f, 0x00, 0x00,
}
