// Code generated by protoc-gen-go. DO NOT EDIT.
// source: reportsgrpcapi/grpcapi.proto

package reportsgrpcapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeepPingOutput struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeepPingOutput) Reset()         { *m = DeepPingOutput{} }
func (m *DeepPingOutput) String() string { return proto.CompactTextString(m) }
func (*DeepPingOutput) ProtoMessage()    {}
func (*DeepPingOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_1ebb880ddca36d1d, []int{0}
}
func (m *DeepPingOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeepPingOutput.Unmarshal(m, b)
}
func (m *DeepPingOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeepPingOutput.Marshal(b, m, deterministic)
}
func (dst *DeepPingOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeepPingOutput.Merge(dst, src)
}
func (m *DeepPingOutput) XXX_Size() int {
	return xxx_messageInfo_DeepPingOutput.Size(m)
}
func (m *DeepPingOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_DeepPingOutput.DiscardUnknown(m)
}

var xxx_messageInfo_DeepPingOutput proto.InternalMessageInfo

func (m *DeepPingOutput) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PrimitiveVoid struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimitiveVoid) Reset()         { *m = PrimitiveVoid{} }
func (m *PrimitiveVoid) String() string { return proto.CompactTextString(m) }
func (*PrimitiveVoid) ProtoMessage()    {}
func (*PrimitiveVoid) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_1ebb880ddca36d1d, []int{1}
}
func (m *PrimitiveVoid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimitiveVoid.Unmarshal(m, b)
}
func (m *PrimitiveVoid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimitiveVoid.Marshal(b, m, deterministic)
}
func (dst *PrimitiveVoid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimitiveVoid.Merge(dst, src)
}
func (m *PrimitiveVoid) XXX_Size() int {
	return xxx_messageInfo_PrimitiveVoid.Size(m)
}
func (m *PrimitiveVoid) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimitiveVoid.DiscardUnknown(m)
}

var xxx_messageInfo_PrimitiveVoid proto.InternalMessageInfo

// GET ASSET HEALTH
type GetAssetHealthInput struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAssetHealthInput) Reset()         { *m = GetAssetHealthInput{} }
func (m *GetAssetHealthInput) String() string { return proto.CompactTextString(m) }
func (*GetAssetHealthInput) ProtoMessage()    {}
func (*GetAssetHealthInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_1ebb880ddca36d1d, []int{2}
}
func (m *GetAssetHealthInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAssetHealthInput.Unmarshal(m, b)
}
func (m *GetAssetHealthInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAssetHealthInput.Marshal(b, m, deterministic)
}
func (dst *GetAssetHealthInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAssetHealthInput.Merge(dst, src)
}
func (m *GetAssetHealthInput) XXX_Size() int {
	return xxx_messageInfo_GetAssetHealthInput.Size(m)
}
func (m *GetAssetHealthInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAssetHealthInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetAssetHealthInput proto.InternalMessageInfo

func (m *GetAssetHealthInput) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

type GetAssetHealthOutput struct {
	HealthStatus         string   `protobuf:"bytes,1,opt,name=health_status,json=healthStatus,proto3" json:"health_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAssetHealthOutput) Reset()         { *m = GetAssetHealthOutput{} }
func (m *GetAssetHealthOutput) String() string { return proto.CompactTextString(m) }
func (*GetAssetHealthOutput) ProtoMessage()    {}
func (*GetAssetHealthOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_1ebb880ddca36d1d, []int{3}
}
func (m *GetAssetHealthOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAssetHealthOutput.Unmarshal(m, b)
}
func (m *GetAssetHealthOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAssetHealthOutput.Marshal(b, m, deterministic)
}
func (dst *GetAssetHealthOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAssetHealthOutput.Merge(dst, src)
}
func (m *GetAssetHealthOutput) XXX_Size() int {
	return xxx_messageInfo_GetAssetHealthOutput.Size(m)
}
func (m *GetAssetHealthOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAssetHealthOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetAssetHealthOutput proto.InternalMessageInfo

func (m *GetAssetHealthOutput) GetHealthStatus() string {
	if m != nil {
		return m.HealthStatus
	}
	return ""
}

// GET FL HEALTH
type GetFunctionalLocationHealthInput struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFunctionalLocationHealthInput) Reset()         { *m = GetFunctionalLocationHealthInput{} }
func (m *GetFunctionalLocationHealthInput) String() string { return proto.CompactTextString(m) }
func (*GetFunctionalLocationHealthInput) ProtoMessage()    {}
func (*GetFunctionalLocationHealthInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_1ebb880ddca36d1d, []int{4}
}
func (m *GetFunctionalLocationHealthInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFunctionalLocationHealthInput.Unmarshal(m, b)
}
func (m *GetFunctionalLocationHealthInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFunctionalLocationHealthInput.Marshal(b, m, deterministic)
}
func (dst *GetFunctionalLocationHealthInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFunctionalLocationHealthInput.Merge(dst, src)
}
func (m *GetFunctionalLocationHealthInput) XXX_Size() int {
	return xxx_messageInfo_GetFunctionalLocationHealthInput.Size(m)
}
func (m *GetFunctionalLocationHealthInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFunctionalLocationHealthInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetFunctionalLocationHealthInput proto.InternalMessageInfo

func (m *GetFunctionalLocationHealthInput) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

type GetFunctionalLocationHealthOutput struct {
	HealthStatus         string   `protobuf:"bytes,1,opt,name=health_status,json=healthStatus,proto3" json:"health_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFunctionalLocationHealthOutput) Reset()         { *m = GetFunctionalLocationHealthOutput{} }
func (m *GetFunctionalLocationHealthOutput) String() string { return proto.CompactTextString(m) }
func (*GetFunctionalLocationHealthOutput) ProtoMessage()    {}
func (*GetFunctionalLocationHealthOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_1ebb880ddca36d1d, []int{5}
}
func (m *GetFunctionalLocationHealthOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFunctionalLocationHealthOutput.Unmarshal(m, b)
}
func (m *GetFunctionalLocationHealthOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFunctionalLocationHealthOutput.Marshal(b, m, deterministic)
}
func (dst *GetFunctionalLocationHealthOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFunctionalLocationHealthOutput.Merge(dst, src)
}
func (m *GetFunctionalLocationHealthOutput) XXX_Size() int {
	return xxx_messageInfo_GetFunctionalLocationHealthOutput.Size(m)
}
func (m *GetFunctionalLocationHealthOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFunctionalLocationHealthOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetFunctionalLocationHealthOutput proto.InternalMessageInfo

func (m *GetFunctionalLocationHealthOutput) GetHealthStatus() string {
	if m != nil {
		return m.HealthStatus
	}
	return ""
}

type GetComplianceLogInput struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetComplianceLogInput) Reset()         { *m = GetComplianceLogInput{} }
func (m *GetComplianceLogInput) String() string { return proto.CompactTextString(m) }
func (*GetComplianceLogInput) ProtoMessage()    {}
func (*GetComplianceLogInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_1ebb880ddca36d1d, []int{6}
}
func (m *GetComplianceLogInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetComplianceLogInput.Unmarshal(m, b)
}
func (m *GetComplianceLogInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetComplianceLogInput.Marshal(b, m, deterministic)
}
func (dst *GetComplianceLogInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetComplianceLogInput.Merge(dst, src)
}
func (m *GetComplianceLogInput) XXX_Size() int {
	return xxx_messageInfo_GetComplianceLogInput.Size(m)
}
func (m *GetComplianceLogInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetComplianceLogInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetComplianceLogInput proto.InternalMessageInfo

func (m *GetComplianceLogInput) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

type GetComplianceLogOutput struct {
	ComplianceList       []*ComplianceItem `protobuf:"bytes,1,rep,name=compliance_list,json=complianceList,proto3" json:"compliance_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetComplianceLogOutput) Reset()         { *m = GetComplianceLogOutput{} }
func (m *GetComplianceLogOutput) String() string { return proto.CompactTextString(m) }
func (*GetComplianceLogOutput) ProtoMessage()    {}
func (*GetComplianceLogOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_1ebb880ddca36d1d, []int{7}
}
func (m *GetComplianceLogOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetComplianceLogOutput.Unmarshal(m, b)
}
func (m *GetComplianceLogOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetComplianceLogOutput.Marshal(b, m, deterministic)
}
func (dst *GetComplianceLogOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetComplianceLogOutput.Merge(dst, src)
}
func (m *GetComplianceLogOutput) XXX_Size() int {
	return xxx_messageInfo_GetComplianceLogOutput.Size(m)
}
func (m *GetComplianceLogOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetComplianceLogOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetComplianceLogOutput proto.InternalMessageInfo

func (m *GetComplianceLogOutput) GetComplianceList() []*ComplianceItem {
	if m != nil {
		return m.ComplianceList
	}
	return nil
}

type ComplianceItem struct {
	AssetClassId         string   `protobuf:"bytes,1,opt,name=asset_class_id,json=assetClassId,proto3" json:"asset_class_id,omitempty"`
	IsCompliant          bool     `protobuf:"varint,2,opt,name=is_compliant,json=isCompliant,proto3" json:"is_compliant,omitempty"`
	ComplianceNote       string   `protobuf:"bytes,3,opt,name=compliance_note,json=complianceNote,proto3" json:"compliance_note,omitempty"`
	Created              int64    `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComplianceItem) Reset()         { *m = ComplianceItem{} }
func (m *ComplianceItem) String() string { return proto.CompactTextString(m) }
func (*ComplianceItem) ProtoMessage()    {}
func (*ComplianceItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcapi_1ebb880ddca36d1d, []int{8}
}
func (m *ComplianceItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComplianceItem.Unmarshal(m, b)
}
func (m *ComplianceItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComplianceItem.Marshal(b, m, deterministic)
}
func (dst *ComplianceItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComplianceItem.Merge(dst, src)
}
func (m *ComplianceItem) XXX_Size() int {
	return xxx_messageInfo_ComplianceItem.Size(m)
}
func (m *ComplianceItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ComplianceItem.DiscardUnknown(m)
}

var xxx_messageInfo_ComplianceItem proto.InternalMessageInfo

func (m *ComplianceItem) GetAssetClassId() string {
	if m != nil {
		return m.AssetClassId
	}
	return ""
}

func (m *ComplianceItem) GetIsCompliant() bool {
	if m != nil {
		return m.IsCompliant
	}
	return false
}

func (m *ComplianceItem) GetComplianceNote() string {
	if m != nil {
		return m.ComplianceNote
	}
	return ""
}

func (m *ComplianceItem) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func init() {
	proto.RegisterType((*DeepPingOutput)(nil), "reportsgrpcapi.DeepPingOutput")
	proto.RegisterType((*PrimitiveVoid)(nil), "reportsgrpcapi.PrimitiveVoid")
	proto.RegisterType((*GetAssetHealthInput)(nil), "reportsgrpcapi.GetAssetHealthInput")
	proto.RegisterType((*GetAssetHealthOutput)(nil), "reportsgrpcapi.GetAssetHealthOutput")
	proto.RegisterType((*GetFunctionalLocationHealthInput)(nil), "reportsgrpcapi.GetFunctionalLocationHealthInput")
	proto.RegisterType((*GetFunctionalLocationHealthOutput)(nil), "reportsgrpcapi.GetFunctionalLocationHealthOutput")
	proto.RegisterType((*GetComplianceLogInput)(nil), "reportsgrpcapi.GetComplianceLogInput")
	proto.RegisterType((*GetComplianceLogOutput)(nil), "reportsgrpcapi.GetComplianceLogOutput")
	proto.RegisterType((*ComplianceItem)(nil), "reportsgrpcapi.ComplianceItem")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReportsClient is the client API for Reports service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReportsClient interface {
	DeepPing(ctx context.Context, in *PrimitiveVoid, opts ...grpc.CallOption) (*DeepPingOutput, error)
	GetAssetHealth(ctx context.Context, in *GetAssetHealthInput, opts ...grpc.CallOption) (*GetAssetHealthOutput, error)
	GetFunctionalLocationHealth(ctx context.Context, in *GetFunctionalLocationHealthInput, opts ...grpc.CallOption) (*GetFunctionalLocationHealthOutput, error)
	GetComplianceLog(ctx context.Context, in *GetComplianceLogInput, opts ...grpc.CallOption) (*GetComplianceLogOutput, error)
}

type reportsClient struct {
	cc *grpc.ClientConn
}

func NewReportsClient(cc *grpc.ClientConn) ReportsClient {
	return &reportsClient{cc}
}

func (c *reportsClient) DeepPing(ctx context.Context, in *PrimitiveVoid, opts ...grpc.CallOption) (*DeepPingOutput, error) {
	out := new(DeepPingOutput)
	err := c.cc.Invoke(ctx, "/reportsgrpcapi.Reports/DeepPing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportsClient) GetAssetHealth(ctx context.Context, in *GetAssetHealthInput, opts ...grpc.CallOption) (*GetAssetHealthOutput, error) {
	out := new(GetAssetHealthOutput)
	err := c.cc.Invoke(ctx, "/reportsgrpcapi.Reports/GetAssetHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportsClient) GetFunctionalLocationHealth(ctx context.Context, in *GetFunctionalLocationHealthInput, opts ...grpc.CallOption) (*GetFunctionalLocationHealthOutput, error) {
	out := new(GetFunctionalLocationHealthOutput)
	err := c.cc.Invoke(ctx, "/reportsgrpcapi.Reports/GetFunctionalLocationHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportsClient) GetComplianceLog(ctx context.Context, in *GetComplianceLogInput, opts ...grpc.CallOption) (*GetComplianceLogOutput, error) {
	out := new(GetComplianceLogOutput)
	err := c.cc.Invoke(ctx, "/reportsgrpcapi.Reports/GetComplianceLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportsServer is the server API for Reports service.
type ReportsServer interface {
	DeepPing(context.Context, *PrimitiveVoid) (*DeepPingOutput, error)
	GetAssetHealth(context.Context, *GetAssetHealthInput) (*GetAssetHealthOutput, error)
	GetFunctionalLocationHealth(context.Context, *GetFunctionalLocationHealthInput) (*GetFunctionalLocationHealthOutput, error)
	GetComplianceLog(context.Context, *GetComplianceLogInput) (*GetComplianceLogOutput, error)
}

func RegisterReportsServer(s *grpc.Server, srv ReportsServer) {
	s.RegisterService(&_Reports_serviceDesc, srv)
}

func _Reports_DeepPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimitiveVoid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportsServer).DeepPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reportsgrpcapi.Reports/DeepPing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportsServer).DeepPing(ctx, req.(*PrimitiveVoid))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reports_GetAssetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssetHealthInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportsServer).GetAssetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reportsgrpcapi.Reports/GetAssetHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportsServer).GetAssetHealth(ctx, req.(*GetAssetHealthInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reports_GetFunctionalLocationHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFunctionalLocationHealthInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportsServer).GetFunctionalLocationHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reportsgrpcapi.Reports/GetFunctionalLocationHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportsServer).GetFunctionalLocationHealth(ctx, req.(*GetFunctionalLocationHealthInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reports_GetComplianceLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetComplianceLogInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportsServer).GetComplianceLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reportsgrpcapi.Reports/GetComplianceLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportsServer).GetComplianceLog(ctx, req.(*GetComplianceLogInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _Reports_serviceDesc = grpc.ServiceDesc{
	ServiceName: "reportsgrpcapi.Reports",
	HandlerType: (*ReportsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeepPing",
			Handler:    _Reports_DeepPing_Handler,
		},
		{
			MethodName: "GetAssetHealth",
			Handler:    _Reports_GetAssetHealth_Handler,
		},
		{
			MethodName: "GetFunctionalLocationHealth",
			Handler:    _Reports_GetFunctionalLocationHealth_Handler,
		},
		{
			MethodName: "GetComplianceLog",
			Handler:    _Reports_GetComplianceLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reportsgrpcapi/grpcapi.proto",
}

func init() {
	proto.RegisterFile("reportsgrpcapi/grpcapi.proto", fileDescriptor_grpcapi_1ebb880ddca36d1d)
}

var fileDescriptor_grpcapi_1ebb880ddca36d1d = []byte{
	// 434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x04, 0x9a, 0x32, 0x4d, 0x5d, 0xb4, 0x14, 0xb0, 0xc2, 0x8f, 0x5c, 0xb7, 0x94, 0x9c,
	0x4c, 0x29, 0xc7, 0x9e, 0x50, 0x11, 0xae, 0x45, 0x04, 0x95, 0x91, 0xb8, 0x21, 0x6b, 0x59, 0x8f,
	0xd2, 0x95, 0x1c, 0xaf, 0xe5, 0x1d, 0xf7, 0x09, 0x78, 0x0c, 0x2e, 0xbc, 0x29, 0xb2, 0x63, 0x27,
	0xac, 0x1b, 0xb9, 0xcd, 0x29, 0x99, 0xcf, 0xf3, 0xfd, 0xec, 0xfa, 0x93, 0xe1, 0x65, 0x81, 0xb9,
	0x2a, 0x48, 0xcf, 0x8a, 0x5c, 0xf0, 0x5c, 0xbe, 0x6b, 0x7e, 0xfd, 0xbc, 0x50, 0xa4, 0x98, 0x6d,
	0x3e, 0xf5, 0x8e, 0xc1, 0xfe, 0x84, 0x98, 0x5f, 0xca, 0x6c, 0xf6, 0xad, 0xa4, 0xbc, 0x24, 0xb6,
	0x0f, 0x0f, 0xaf, 0x79, 0x5a, 0xa2, 0x63, 0xb9, 0xd6, 0xe4, 0x51, 0xb4, 0x18, 0xbc, 0x3d, 0xd8,
	0xbd, 0x2c, 0xe4, 0x5c, 0x92, 0xbc, 0xc6, 0x1f, 0x4a, 0x26, 0x9e, 0x0f, 0x4f, 0x02, 0xa4, 0x8f,
	0x5a, 0x23, 0x5d, 0x20, 0x4f, 0xe9, 0x2a, 0xcc, 0x2a, 0xf6, 0x73, 0x18, 0x66, 0x2a, 0xc1, 0x58,
	0x26, 0x0d, 0x7f, 0xab, 0x1a, 0xc3, 0xc4, 0x3b, 0x83, 0x7d, 0x73, 0xbf, 0xb1, 0x3b, 0x84, 0xdd,
	0xab, 0x7a, 0x8e, 0x35, 0x71, 0x2a, 0x75, 0x43, 0x1b, 0x2d, 0xc0, 0xef, 0x35, 0xe6, 0x9d, 0x81,
	0x1b, 0x20, 0x7d, 0x2e, 0x33, 0x41, 0x52, 0x65, 0x3c, 0x9d, 0x2a, 0xc1, 0xab, 0x7f, 0x77, 0x72,
	0xbe, 0x80, 0x83, 0x1e, 0xf2, 0x26, 0x31, 0x4e, 0xe0, 0x69, 0x80, 0x74, 0xae, 0xe6, 0x79, 0x2a,
	0x79, 0x26, 0x70, 0xaa, 0x66, 0xb7, 0x78, 0x73, 0x78, 0xd6, 0x65, 0x34, 0x86, 0x01, 0xec, 0x89,
	0x25, 0x1c, 0xa7, 0x52, 0x93, 0x63, 0xb9, 0x83, 0xc9, 0xce, 0xe9, 0x6b, 0xdf, 0x7c, 0x45, 0xfe,
	0x8a, 0x1d, 0x12, 0xce, 0x23, 0x7b, 0x45, 0x9b, 0x4a, 0x4d, 0xde, 0x1f, 0x0b, 0x6c, 0x73, 0x85,
	0x1d, 0x81, 0xcd, 0xab, 0x8b, 0x8e, 0x45, 0xca, 0xb5, 0x5e, 0xa5, 0x1a, 0xd5, 0xe8, 0x79, 0x05,
	0x86, 0x09, 0x3b, 0x80, 0x91, 0xd4, 0x71, 0xab, 0x46, 0xce, 0x7d, 0xd7, 0x9a, 0x6c, 0x47, 0x3b,
	0x52, 0xb7, 0x6a, 0xc4, 0xde, 0x1a, 0x21, 0x33, 0x45, 0xe8, 0x0c, 0x6a, 0xa5, 0xff, 0x42, 0x7c,
	0x55, 0x84, 0xcc, 0x81, 0xa1, 0x28, 0x90, 0x13, 0x26, 0xce, 0x03, 0xd7, 0x9a, 0x0c, 0xa2, 0x76,
	0x3c, 0xfd, 0x3b, 0x80, 0x61, 0xb4, 0x38, 0x10, 0xfb, 0x02, 0xdb, 0x6d, 0xd9, 0xd8, 0xab, 0xee,
	0x31, 0x8d, 0x7a, 0x8d, 0x6f, 0xdc, 0x82, 0xd9, 0x52, 0xef, 0x1e, 0xfb, 0x09, 0xb6, 0x59, 0x28,
	0x76, 0xd8, 0xe5, 0xac, 0x29, 0xe8, 0xf8, 0xa8, 0x7f, 0x69, 0x29, 0xff, 0xdb, 0x82, 0x17, 0x3d,
	0xb5, 0x61, 0x27, 0x6b, 0x74, 0x7a, 0x0b, 0x3a, 0x7e, 0xbf, 0x01, 0x63, 0x19, 0x43, 0xc0, 0xe3,
	0x6e, 0x81, 0xd8, 0x9b, 0x35, 0x42, 0x37, 0x4b, 0x39, 0x3e, 0xbe, 0x6d, 0xad, 0x35, 0xf9, 0xb5,
	0x55, 0x7f, 0x1b, 0x3e, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x1f, 0x13, 0xa8, 0x3b, 0x04,
	0x00, 0x00,
}
