name: Validate v2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
        id: go

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52
          args: --disable wsl,govet
          working-directory: v2/

      - name: Test
        run: |
          go clean
          go test -short -count=1 ./...
        working-directory: v2/
